<?php

namespace Database\Seeders;

use App\Models\AccountHolder;
use Illuminate\Database\Seeder;

class AccountHolderSeeder extends Seeder
{
    public function run(): void
    {
        $currencies = \App\Models\Currency::pluck('id', 'currency_code')->toArray();

        $accountHolders = [
            ['account_type' => 1, 'account_name' => 'John Smith', 'company_name' => 'Smith Enterprises', 'business_number' => 'BN001234', 'tax_id_no' => 'TX001234', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '123', 'street_number' => 'Main Street', 'city' => 'New York', 'state' => 'NY', 'country' => 'US', 'zip_code' => '10001', 'office_phone' => '+1 (555) 123-4567', 'cell_phone' => '+1 (555) 123-4568', 'email' => 'john.smith@smithenterprises.com', 'website' => 'https://smithenterprises.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-001', 'linked_transaction_purchase' => 'PUR-001', 'status_active' => true],
            ['account_type' => 1, 'account_name' => 'Maria Garcia', 'company_name' => 'Garcia Industries', 'business_number' => 'BN001235', 'tax_id_no' => 'TX001235', 'currency_id' => $currencies['EUR'] ?? 1, 'house_number' => '456', 'street_number' => 'Oak Avenue', 'city' => 'Miami', 'state' => 'FL', 'country' => 'US', 'zip_code' => '33101', 'office_phone' => '+1 (555) 234-5678', 'cell_phone' => '+1 (555) 234-5679', 'email' => 'maria.garcia@garciaindustries.com', 'website' => 'https://garciaindustries.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-002', 'linked_transaction_purchase' => 'PUR-002', 'status_active' => true],
            ['account_type' => 1, 'account_name' => 'Robert Johnson', 'company_name' => 'Johnson Corp', 'business_number' => 'BN001236', 'tax_id_no' => 'TX001236', 'currency_id' => $currencies['GBP'] ?? 1, 'house_number' => '789', 'street_number' => 'High Street', 'city' => 'London', 'state' => 'ENG', 'country' => 'GB', 'zip_code' => 'SW1A 1AA', 'office_phone' => '+44 20 7946 0958', 'cell_phone' => '+44 7700 900123', 'email' => 'r.johnson@johnsoncorp.co.uk', 'website' => 'https://johnsoncorp.co.uk', 'prefer_contact_method' => 1, 'linked_transaction_sales' => 'SAL-003', 'linked_transaction_purchase' => 'PUR-003', 'status_active' => true],
            ['account_type' => 1, 'account_name' => 'Sarah Williams', 'company_name' => 'Williams Trading Co', 'business_number' => 'BN001237', 'tax_id_no' => 'TX001237', 'currency_id' => $currencies['AUD'] ?? 1, 'house_number' => '321', 'street_number' => 'George Street', 'city' => 'Sydney', 'state' => 'NSW', 'country' => 'AU', 'zip_code' => '2000', 'office_phone' => '+61 2 9876 5432', 'cell_phone' => '+61 401 234 567', 'email' => 'sarah@williamstrading.com.au', 'website' => 'https://williamstrading.com.au', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-004', 'linked_transaction_purchase' => 'PUR-004', 'status_active' => true],
            ['account_type' => 1, 'account_name' => 'Michael Brown', 'company_name' => 'Brown & Associates', 'business_number' => 'BN001238', 'tax_id_no' => 'TX001238', 'currency_id' => $currencies['CAD'] ?? 1, 'house_number' => '555', 'street_number' => 'Yonge Street', 'city' => 'Toronto', 'state' => 'ON', 'country' => 'CA', 'zip_code' => 'M5V 2T4', 'office_phone' => '+1 (416) 555-1234', 'cell_phone' => '+1 (416) 555-1235', 'email' => 'mbrown@brownassociates.ca', 'website' => 'https://brownassociates.ca', 'prefer_contact_method' => 1, 'linked_transaction_sales' => 'SAL-005', 'linked_transaction_purchase' => 'PUR-005', 'status_active' => true],

            ['account_type' => 2, 'account_name' => 'Tech Solutions Ltd', 'company_name' => 'Tech Solutions Ltd', 'business_number' => 'BN002001', 'tax_id_no' => 'TX002001', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '100', 'street_number' => 'Tech Park Drive', 'city' => 'San Francisco', 'state' => 'CA', 'country' => 'US', 'zip_code' => '94105', 'office_phone' => '+1 (415) 555-0100', 'cell_phone' => '+1 (415) 555-0101', 'email' => 'sales@techsolutions.com', 'website' => 'https://techsolutions.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-006', 'linked_transaction_purchase' => 'PUR-006', 'status_active' => true],
            ['account_type' => 2, 'account_name' => 'Global Supplies Inc', 'company_name' => 'Global Supplies Inc', 'business_number' => 'BN002002', 'tax_id_no' => 'TX002002', 'currency_id' => $currencies['EUR'] ?? 1, 'house_number' => '200', 'street_number' => 'Industriestraße', 'city' => 'Munich', 'state' => 'BY', 'country' => 'DE', 'zip_code' => '80331', 'office_phone' => '+49 89 12345678', 'cell_phone' => '+49 151 12345678', 'email' => 'contact@globalsupplies.de', 'website' => 'https://globalsupplies.de', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-007', 'linked_transaction_purchase' => 'PUR-007', 'status_active' => true],
            ['account_type' => 2, 'account_name' => 'Pacific Traders', 'company_name' => 'Pacific Traders', 'business_number' => 'BN002003', 'tax_id_no' => 'TX002003', 'currency_id' => $currencies['SGD'] ?? 1, 'house_number' => '75', 'street_number' => 'Marina Bay', 'city' => 'Singapore', 'state' => 'SG', 'country' => 'SG', 'zip_code' => '018956', 'office_phone' => '+65 6222 3333', 'cell_phone' => '+65 9123 4567', 'email' => 'info@pacifictraders.sg', 'website' => 'https://pacifictraders.sg', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-008', 'linked_transaction_purchase' => 'PUR-008', 'status_active' => true],
            ['account_type' => 2, 'account_name' => 'Euro Components GmbH', 'company_name' => 'Euro Components GmbH', 'business_number' => 'BN002004', 'tax_id_no' => 'TX002004', 'currency_id' => $currencies['EUR'] ?? 1, 'house_number' => '50', 'street_number' => 'Hauptstraße', 'city' => 'Berlin', 'state' => 'BE', 'country' => 'DE', 'zip_code' => '10115', 'office_phone' => '+49 30 12345678', 'cell_phone' => '+49 151 23456789', 'email' => 'sales@eucomponents.de', 'website' => 'https://eucomponents.de', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-009', 'linked_transaction_purchase' => 'PUR-009', 'status_active' => true],
            ['account_type' => 2, 'account_name' => 'Orient Exports', 'company_name' => 'Orient Exports', 'business_number' => 'BN002005', 'tax_id_no' => 'TX002005', 'currency_id' => $currencies['JPY'] ?? 1, 'house_number' => '88', 'street_number' => 'Shibuya', 'city' => 'Tokyo', 'state' => 'TG', 'country' => 'JP', 'zip_code' => '150-0002', 'office_phone' => '+81 3 1234 5678', 'cell_phone' => '+81 90 1234 5678', 'email' => 'export@orientexports.jp', 'website' => 'https://orientexports.jp', 'prefer_contact_method' => 1, 'linked_transaction_sales' => 'SAL-010', 'linked_transaction_purchase' => 'PUR-010', 'status_active' => true],

            ['account_type' => 3, 'account_name' => 'Quick Fix Services', 'company_name' => 'Quick Fix Services', 'business_number' => 'BN003001', 'tax_id_no' => 'TX003001', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '300', 'street_number' => 'Service Lane', 'city' => 'Chicago', 'state' => 'IL', 'country' => 'US', 'zip_code' => '60601', 'office_phone' => '+1 (312) 555-0300', 'cell_phone' => '+1 (312) 555-0301', 'email' => 'service@quickfix.com', 'website' => 'https://quickfixservices.com', 'prefer_contact_method' => 1, 'linked_transaction_sales' => 'SAL-011', 'linked_transaction_purchase' => 'PUR-011', 'status_active' => true],
            ['account_type' => 3, 'account_name' => 'Elite Maintenance Co', 'company_name' => 'Elite Maintenance Co', 'business_number' => 'BN003002', 'tax_id_no' => 'TX003002', 'currency_id' => $currencies['GBP'] ?? 1, 'house_number' => '150', 'street_number' => 'Industrial Estate', 'city' => 'Birmingham', 'state' => 'ENG', 'country' => 'GB', 'zip_code' => 'B1 2AA', 'office_phone' => '+44 121 555 0300', 'cell_phone' => '+44 7700 900456', 'email' => 'maintenance@elitemc.co.uk', 'website' => 'https://elitemaintenance.co.uk', 'prefer_contact_method' => 1, 'linked_transaction_sales' => 'SAL-012', 'linked_transaction_purchase' => 'PUR-012', 'status_active' => true],
            ['account_type' => 3, 'account_name' => 'Professional Cleaners', 'company_name' => 'Professional Cleaners', 'business_number' => 'BN003003', 'tax_id_no' => 'TX003003', 'currency_id' => $currencies['AUD'] ?? 1, 'house_number' => '45', 'street_number' => 'Clean Street', 'city' => 'Melbourne', 'state' => 'VIC', 'country' => 'AU', 'zip_code' => '3000', 'office_phone' => '+61 3 9876 5432', 'cell_phone' => '+61 401 234 567', 'email' => 'clean@procleaners.com.au', 'website' => 'https://professionalcleaners.com.au', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-013', 'linked_transaction_purchase' => 'PUR-013', 'status_active' => true],
            ['account_type' => 3, 'account_name' => 'Digital Tech Support', 'company_name' => 'Digital Tech Support', 'business_number' => 'BN003004', 'tax_id_no' => 'TX003004', 'currency_id' => $currencies['INR'] ?? 1, 'house_number' => '25', 'street_number' => 'Tech Nagar', 'city' => 'Bangalore', 'state' => 'KA', 'country' => 'IN', 'zip_code' => '560001', 'office_phone' => '+91 80 1234 5678', 'cell_phone' => '+91 98765 12345', 'email' => 'support@digitaltech.in', 'website' => 'https://digitaltechsupport.in', 'prefer_contact_method' => 2, 'linked_transaction_sales' => 'SAL-014', 'linked_transaction_purchase' => 'PUR-014', 'status_active' => true],
            ['account_type' => 3, 'account_name' => 'Home Repair Experts', 'company_name' => 'Home Repair Experts', 'business_number' => 'BN003005', 'tax_id_no' => 'TX003005', 'currency_id' => $currencies['CAD'] ?? 1, 'house_number' => '88', 'street_number' => 'Handyman Ave', 'city' => 'Vancouver', 'state' => 'BC', 'country' => 'CA', 'zip_code' => 'V6B 1A1', 'office_phone' => '+1 (604) 555-0888', 'cell_phone' => '+1 (604) 555-0889', 'email' => 'repairs@homerepair.ca', 'website' => 'https://homerepairexperts.ca', 'prefer_contact_method' => 1, 'linked_transaction_sales' => 'SAL-015', 'linked_transaction_purchase' => 'PUR-015', 'status_active' => true],

            ['account_type' => 4, 'account_name' => 'Jennifer Adams', 'company_name' => 'Internal', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '10', 'street_number' => 'Corporate HQ', 'city' => 'Boston', 'state' => 'MA', 'country' => 'US', 'zip_code' => '02101', 'office_phone' => '+1 (617) 555-0100', 'cell_phone' => '+1 (617) 555-0101', 'email' => 'j.adams@company.com', 'website' => '', 'prefer_contact_method' => 1, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 4, 'account_name' => 'David Chen', 'company_name' => 'Internal', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '10', 'street_number' => 'Corporate HQ', 'city' => 'Boston', 'state' => 'MA', 'country' => 'US', 'zip_code' => '02101', 'office_phone' => '+1 (617) 555-0102', 'cell_phone' => '+1 (617) 555-0103', 'email' => 'd.chen@company.com', 'website' => '', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 4, 'account_name' => 'Emily Wilson', 'company_name' => 'Internal', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '10', 'street_number' => 'Corporate HQ', 'city' => 'Boston', 'state' => 'MA', 'country' => 'US', 'zip_code' => '02101', 'office_phone' => '+1 (617) 555-0104', 'cell_phone' => '+1 (617) 555-0105', 'email' => 'e.wilson@company.com', 'website' => '', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 4, 'account_name' => 'James Taylor', 'company_name' => 'Internal', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '10', 'street_number' => 'Corporate HQ', 'city' => 'Boston', 'state' => 'MA', 'country' => 'US', 'zip_code' => '02101', 'office_phone' => '+1 (617) 555-0106', 'cell_phone' => '+1 (617) 555-0107', 'email' => 'j.taylor@company.com', 'website' => '', 'prefer_contact_method' => 1, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 4, 'account_name' => 'Lisa Martinez', 'company_name' => 'Internal', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '10', 'street_number' => 'Corporate HQ', 'city' => 'Boston', 'state' => 'MA', 'country' => 'US', 'zip_code' => '02101', 'office_phone' => '+1 (617) 555-0108', 'cell_phone' => '+1 (617) 555-0109', 'email' => 'l.martinez@company.com', 'website' => '', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],

            ['account_type' => 5, 'account_name' => 'First National Bank', 'company_name' => 'First National Bank', 'business_number' => 'BN005001', 'tax_id_no' => 'TX005001', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '1000', 'street_number' => 'Financial District', 'city' => 'New York', 'state' => 'NY', 'country' => 'US', 'zip_code' => '10004', 'office_phone' => '+1 (212) 555-1000', 'cell_phone' => '', 'email' => 'contact@firstnationalbank.com', 'website' => 'https://firstnationalbank.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 5, 'account_name' => 'International Trust', 'company_name' => 'International Trust Bank', 'business_number' => 'BN005002', 'tax_id_no' => 'TX005002', 'currency_id' => $currencies['EUR'] ?? 1, 'house_number' => '500', 'street_number' => 'Bank Street', 'city' => 'Zurich', 'state' => 'ZH', 'country' => 'CH', 'zip_code' => '8001', 'office_phone' => '+41 44 123 4567', 'cell_phone' => '', 'email' => 'info@internationaltrust.ch', 'website' => 'https://internationaltrust.ch', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 5, 'account_name' => 'City Bank', 'company_name' => 'City Bank', 'business_number' => 'BN005003', 'tax_id_no' => 'TX005003', 'currency_id' => $currencies['GBP'] ?? 1, 'house_number' => '25', 'street_number' => 'Thames Gateway', 'city' => 'London', 'state' => 'ENG', 'country' => 'GB', 'zip_code' => 'EC1V 9AB', 'office_phone' => '+44 20 7946 0123', 'cell_phone' => '', 'email' => 'support@citybank.co.uk', 'website' => 'https://citybank.co.uk', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 5, 'account_name' => 'Asian Pacific Bank', 'company_name' => 'Asian Pacific Bank', 'business_number' => 'BN005004', 'tax_id_no' => 'TX005004', 'currency_id' => $currencies['HKD'] ?? 1, 'house_number' => '88', 'street_number' => 'Central Avenue', 'city' => 'Hong Kong', 'state' => 'HK', 'country' => 'HK', 'zip_code' => '0000', 'office_phone' => '+852 2255 5888', 'cell_phone' => '', 'email' => 'enquiry@asianpacificbank.hk', 'website' => 'https://asianpacificbank.hk', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 5, 'account_name' => 'Regional Credit Union', 'company_name' => 'Regional Credit Union', 'business_number' => 'BN005005', 'tax_id_no' => 'TX005005', 'currency_id' => $currencies['CAD'] ?? 1, 'house_number' => '250', 'street_number' => 'Credit Union Drive', 'city' => 'Montreal', 'state' => 'QC', 'country' => 'CA', 'zip_code' => 'H2Y 1A1', 'office_phone' => '+1 (514) 555-0250', 'cell_phone' => '', 'email' => 'info@regionalcu.ca', 'website' => 'https://regionalcreditunion.ca', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],

            ['account_type' => 6, 'account_name' => 'Visa Platinum Card', 'company_name' => 'Visa', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '', 'street_number' => '', 'city' => '', 'state' => '', 'country' => 'US', 'zip_code' => '', 'office_phone' => '', 'cell_phone' => '+1 (800) 555-0123', 'email' => 'support@visa.com', 'website' => 'https://visa.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 6, 'account_name' => 'Mastercard Gold', 'company_name' => 'Mastercard', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '', 'street_number' => '', 'city' => '', 'state' => '', 'country' => 'US', 'zip_code' => '', 'office_phone' => '', 'cell_phone' => '+1 (800) 555-0124', 'email' => 'support@mastercard.com', 'website' => 'https://mastercard.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 6, 'account_name' => 'American Express', 'company_name' => 'American Express', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '200', 'street_number' => 'Vesey Street', 'city' => 'New York', 'state' => 'NY', 'country' => 'US', 'zip_code' => '10281', 'office_phone' => '+1 (212) 555-0200', 'cell_phone' => '', 'email' => 'support@americanexpress.com', 'website' => 'https://americanexpress.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 6, 'account_name' => 'Discover Card', 'company_name' => 'Discover', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '', 'street_number' => '', 'city' => 'Chicago', 'state' => 'IL', 'country' => 'US', 'zip_code' => '', 'office_phone' => '+1 (224) 555-0300', 'cell_phone' => '', 'email' => 'support@discover.com', 'website' => 'https://discover.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 6, 'account_name' => 'Corporate Credit Card', 'company_name' => 'Corporate Cards Inc', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '', 'street_number' => '', 'city' => '', 'state' => '', 'country' => 'US', 'zip_code' => '', 'office_phone' => '', 'cell_phone' => '+1 (800) 555-0125', 'email' => 'cards@corporate.com', 'website' => 'https://corporatecreditcards.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],

            ['account_type' => 7, 'account_name' => 'Federal Tax Department', 'company_name' => 'Government - Federal', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '1500', 'street_number' => 'Constitution Ave', 'city' => 'Washington', 'state' => 'DC', 'country' => 'US', 'zip_code' => '20220', 'office_phone' => '+1 (202) 555-1500', 'cell_phone' => '', 'email' => 'contact@fedtax.gov', 'website' => 'https://irs.gov', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 7, 'account_name' => 'State Revenue Department', 'company_name' => 'Government - State', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '100', 'street_number' => 'State Capitol', 'city' => 'Austin', 'state' => 'TX', 'country' => 'US', 'zip_code' => '78701', 'office_phone' => '+1 (512) 555-0100', 'cell_phone' => '', 'email' => 'revenue@statetax.gov', 'website' => 'https://statetax.gov', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 7, 'account_name' => 'City Revenue Office', 'company_name' => 'Government - City', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '50', 'street_number' => 'City Hall', 'city' => 'Philadelphia', 'state' => 'PA', 'country' => 'US', 'zip_code' => '19102', 'office_phone' => '+1 (215) 555-0050', 'cell_phone' => '', 'email' => 'tax@cityrevenue.gov', 'website' => 'https://cityrevenue.gov', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 7, 'account_name' => 'HM Revenue & Customs', 'company_name' => 'Government - UK', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['GBP'] ?? 1, 'house_number' => '100', 'street_number' => 'Parliament Street', 'city' => 'London', 'state' => 'ENG', 'country' => 'GB', 'zip_code' => 'SW1A 2BB', 'office_phone' => '+44 20 7946 0100', 'cell_phone' => '', 'email' => 'enquiries@hmrc.gov.uk', 'website' => 'https://hmrc.gov.uk', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 7, 'account_name' => 'Inland Revenue', 'company_name' => 'Government - New Zealand', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['NZD'] ?? 1, 'house_number' => '180', 'street_number' => 'Wellington Street', 'city' => 'Wellington', 'state' => 'WGN', 'country' => 'NZ', 'zip_code' => '6011', 'office_phone' => '+64 4 555 0180', 'cell_phone' => '', 'email' => 'support@ird.govt.nz', 'website' => 'https://ird.govt.nz', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],

            ['account_type' => 8, 'account_name' => 'National Tax Office', 'company_name' => 'Tax Office', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '2000', 'street_number' => 'Tax Plaza', 'city' => 'Washington', 'state' => 'DC', 'country' => 'US', 'zip_code' => '20220', 'office_phone' => '+1 (202) 555-2000', 'cell_phone' => '', 'email' => 'info@nationaltaxoffice.gov', 'website' => 'https://nationaltaxoffice.gov', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 8, 'account_name' => 'State Tax Commission', 'company_name' => 'Tax Commission', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '300', 'street_number' => 'Tax Building', 'city' => 'Sacramento', 'state' => 'CA', 'country' => 'US', 'zip_code' => '94203', 'office_phone' => '+1 (916) 555-0300', 'cell_phone' => '', 'email' => 'contact@statetaxcom.gov', 'website' => 'https://statetaxcommission.gov', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 8, 'account_name' => 'Tax Assessment Bureau', 'company_name' => 'Assessment Bureau', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['CAD'] ?? 1, 'house_number' => '75', 'street_number' => 'Assessment Way', 'city' => 'Ottawa', 'state' => 'ON', 'country' => 'CA', 'zip_code' => 'K1P 5W1', 'office_phone' => '+1 (613) 555-0075', 'cell_phone' => '', 'email' => 'assess@taxbureau.ca', 'website' => 'https://taxassessmentbureau.ca', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 8, 'account_name' => 'Federal Tax Agency', 'company_name' => 'Tax Agency', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['EUR'] ?? 1, 'house_number' => '50', 'street_number' => 'Tax Strasse', 'city' => 'Berlin', 'state' => 'BE', 'country' => 'DE', 'zip_code' => '10115', 'office_phone' => '+49 30 5550 050', 'cell_phone' => '', 'email' => 'info@taxagentur.de', 'website' => 'https://federaltaxagency.de', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 8, 'account_name' => 'Revenue Commissioners', 'company_name' => 'Revenue Office', 'business_number' => '', 'tax_id_no' => '', 'currency_id' => $currencies['EUR'] ?? 1, 'house_number' => '25', 'street_number' => 'Tax Row', 'city' => 'Dublin', 'state' => 'D', 'country' => 'IE', 'zip_code' => 'D02 XK37', 'office_phone' => '+353 1 555 0025', 'cell_phone' => '', 'email' => 'query@revenue.ie', 'website' => 'https://revenue.ie', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],

            ['account_type' => 9, 'account_name' => 'Alpha Investments LLC', 'company_name' => 'Alpha Investments LLC', 'business_number' => 'BN009001', 'tax_id_no' => 'TX009001', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '500', 'street_number' => 'Investor Way', 'city' => 'New York', 'state' => 'NY', 'country' => 'US', 'zip_code' => '10005', 'office_phone' => '+1 (212) 555-0500', 'cell_phone' => '', 'email' => 'invest@alphainvest.com', 'website' => 'https://alphainvestments.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 9, 'account_name' => 'Beta Holdings Ltd', 'company_name' => 'Beta Holdings Ltd', 'business_number' => 'BN009002', 'tax_id_no' => 'TX009002', 'currency_id' => $currencies['GBP'] ?? 1, 'house_number' => '100', 'street_number' => 'Exchange Square', 'city' => 'London', 'state' => 'ENG', 'country' => 'GB', 'zip_code' => 'EC2A 2AB', 'office_phone' => '+44 20 7946 0100', 'cell_phone' => '', 'email' => 'shareholders@betaholdings.co.uk', 'website' => 'https://betaholdings.co.uk', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 9, 'account_name' => 'Gamma Partners', 'company_name' => 'Gamma Partners', 'business_number' => 'BN009003', 'tax_id_no' => 'TX009003', 'currency_id' => $currencies['EUR'] ?? 1, 'house_number' => '75', 'street_number' => 'Bourse Street', 'city' => 'Amsterdam', 'state' => 'NH', 'country' => 'NL', 'zip_code' => '1012 DK', 'office_phone' => '+31 20 555 0075', 'cell_phone' => '', 'email' => 'partners@gamma.nl', 'website' => 'https://gammapartners.nl', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 9, 'account_name' => 'Delta Capital', 'company_name' => 'Delta Capital Group', 'business_number' => 'BN009004', 'tax_id_no' => 'TX009004', 'currency_id' => $currencies['SGD'] ?? 1, 'house_number' => '200', 'street_number' => 'Capital Plaza', 'city' => 'Singapore', 'state' => 'SG', 'country' => 'SG', 'zip_code' => '018956', 'office_phone' => '+65 6222 0200', 'cell_phone' => '', 'email' => 'capital@deltacapital.sg', 'website' => 'https://deltacapital.sg', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
            ['account_type' => 9, 'account_name' => 'Omega Ventures', 'company_name' => 'Omega Ventures Inc', 'business_number' => 'BN009005', 'tax_id_no' => 'TX009005', 'currency_id' => $currencies['USD'] ?? 1, 'house_number' => '350', 'street_number' => 'Venture Drive', 'city' => 'San Jose', 'state' => 'CA', 'country' => 'US', 'zip_code' => '95110', 'office_phone' => '+1 (408) 555-0350', 'cell_phone' => '', 'email' => 'ventures@omegavc.com', 'website' => 'https://omegaventures.com', 'prefer_contact_method' => 2, 'linked_transaction_sales' => '', 'linked_transaction_purchase' => '', 'status_active' => true],
        ];

        $suffixes = \App\Models\AccountHolderSuffix::pluck('id', 'suffix')->toArray();

        $countryMapping = [
            'US' => 236, 'GB' => 235, 'AU' => 13, 'CA' => 39, 'DE' => 83,
            'SG' => 199, 'JP' => 112, 'IN' => 102, 'CH' => 215, 'HK' => 99,
            'NZ' => 157, 'NL' => 155, 'IE' => 106,
        ];

        foreach ($accountHolders as $index => $data) {
            $systemNo = str_pad($index + 1, 5, '0', STR_PAD_LEFT);
            $countryCode = $data['country'];
            $countryId = $countryMapping[$countryCode] ?? $countryCode;

            AccountHolder::updateOrCreate(
                ['system_no' => 'AH'.$systemNo],
                array_merge($data, [
                    'project_id' => 1,
                    'system_prefix' => 'AH',
                    'system_no' => 'AH'.$systemNo,
                    'country' => $countryId,
                    'inserted_by' => 0,
                    'updated_by' => 0,
                    'is_deleted' => false,
                ])
            );
        }
    }
}
