<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'vehicle_number' => 'BG-001',
                'make_brand' => 'Toyota',
                'model' => 'Camry',
                'vehicle_type' => 'Sedan',
                'vehicle_year' => 2020,
                'color' => 'Silver',
                'vin' => '1HGCM82633A004352',
                'fuel_type' => 'Gasoline',
                'vehicle_keys_tag_no' => 'VT-00987',
                'plate_number' => 'ABC-1234',
                'plate_expiry_date' => '2026-12-31',
                'assignment_start_date' => '2026-01-05',
                'purchase_date' => '2020-02-20',
                'purchase_price' => 3978.33,
                'purchase_invoice_number' => 'IV-2025-0158',
                'invoice_date' => '2026-01-03',
                'sales_tax' => 2200.00,
                'subtotal' => 22000.00,
                'total_paid' => 23870.00,
                'number_of_installments' => 6,
                'first_installment_amount' => 3978.33,
                'first_installment_date' => '2026-01-15',
                'last_installment_amount' => 11935.00,
                'last_installment_date' => '2026-06-15',
                'current_mileage' => 45234,
                'insurance_provider' => 'Allianz Insurance',
                'policy_number' => 'POL-9467',
                'insurance_start_date' => '2026-01-01',
                'insurance_expiry_date' => '2026-12-31',
                'insurance_expired' => false,
                'assigned_driver' => 'John Smith',
                'in_service' => true,
                'seller_name' => 'Michael Brown',
                'seller_company_name' => 'AutoHub Motors',
                'seller_phone' => '+1 555 987-6543',
                'seller_email' => 'michael.brown@autohub.com',
                'seller_website' => 'www.autohubmotors.com',
                'car_photos' => ['camry-front.jpg', 'camry-side.jpg'],
                'driver_profiles' => [[
                    'name' => 'John Smith',
                    'phone' => '(555) 123-4567',
                    'email' => 'john_smith@example.com',
                    'address' => '123 Main St, Springfield, IL 62701',
                    'license_number' => 'D12345789',
                    'license_expiry_date' => '2027-05-01',
                    'license_expired' => false,
                ]],
                'insurance_documents' => [[
                    'insurance_company' => 'State Insurance',
                    'policy_number' => 'POL-5567',
                    'policy_start_date' => '2026-01-01',
                    'policy_expiry_date' => '2026-12-31',
                    'expired' => false,
                    'document_name' => 'state_policy_2024.pdf',
                ]],
                'safety_equipments' => $this->defaultSafetyEquipment(),
                'status' => 1,
                'last_maintenance_date' => '2026-03-02',
                'next_maintenance_date' => '2026-07-02',
                'notes' => 'Primary office sedan assigned to site coordination.',
            ],
            [
                'vehicle_number' => 'BG-002',
                'make_brand' => 'Honda',
                'model' => 'Civic',
                'vehicle_type' => 'Sedan',
                'vehicle_year' => 2021,
                'color' => 'White',
                'vin' => '2HGCM82633A004353',
                'fuel_type' => 'Diesel',
                'vehicle_keys_tag_no' => 'VT-00988',
                'plate_number' => 'XYZ-5678',
                'plate_expiry_date' => '2026-11-28',
                'assignment_start_date' => '2026-02-01',
                'purchase_date' => '2021-04-14',
                'purchase_price' => 4962.50,
                'purchase_invoice_number' => 'IV-2025-0161',
                'invoice_date' => '2026-02-03',
                'sales_tax' => 1800.00,
                'subtotal' => 18050.00,
                'total_paid' => 19850.00,
                'number_of_installments' => 4,
                'first_installment_amount' => 4962.50,
                'first_installment_date' => '2026-02-05',
                'last_installment_amount' => 4962.50,
                'last_installment_date' => '2026-05-05',
                'current_mileage' => 32145,
                'insurance_provider' => 'Liberty Mutual',
                'policy_number' => 'POL-8321',
                'insurance_start_date' => '2026-02-01',
                'insurance_expiry_date' => '2027-01-31',
                'insurance_expired' => false,
                'assigned_driver' => 'Sarah Johnson',
                'in_service' => false,
                'seller_name' => 'Sarah Johnson',
                'seller_company_name' => 'Metro Vehicle Center',
                'seller_phone' => '+1 555 897-2121',
                'seller_email' => 'sales@metrovehiclecenter.com',
                'seller_website' => 'www.metrovehiclecenter.com',
                'car_photos' => ['civic-front.jpg'],
                'driver_profiles' => [[
                    'name' => 'Sarah Johnson',
                    'phone' => '(555) 323-4567',
                    'email' => 'sarah.johnson@example.com',
                    'address' => '456 Oak Ave, Chicago, IL 60611',
                    'license_number' => 'S98765432',
                    'license_expiry_date' => '2027-08-14',
                    'license_expired' => false,
                ]],
                'insurance_documents' => [[
                    'insurance_company' => 'State Insurance',
                    'policy_number' => 'POL-8321',
                    'policy_start_date' => '2026-02-01',
                    'policy_expiry_date' => '2027-01-31',
                    'expired' => false,
                    'document_name' => 'civic_policy.pdf',
                ]],
                'safety_equipments' => $this->defaultSafetyEquipment(),
                'status' => 2,
                'last_maintenance_date' => '2026-04-01',
                'next_maintenance_date' => '2026-08-01',
                'notes' => 'Available pool car for admin visits.',
            ],
            [
                'vehicle_number' => 'BG-003',
                'make_brand' => 'Ford',
                'model' => 'F-150',
                'vehicle_type' => 'Truck',
                'vehicle_year' => 2022,
                'color' => 'Blue',
                'vin' => '3HGCM82633A004354',
                'fuel_type' => 'Gasoline',
                'vehicle_keys_tag_no' => 'VT-00989',
                'plate_number' => 'DEF-9012',
                'plate_expiry_date' => '2026-10-15',
                'assignment_start_date' => '2026-01-10',
                'purchase_date' => '2022-06-01',
                'purchase_price' => 3905.00,
                'purchase_invoice_number' => 'IV-2025-0172',
                'invoice_date' => '2026-01-08',
                'sales_tax' => 2980.00,
                'subtotal' => 28260.00,
                'total_paid' => 31240.00,
                'number_of_installments' => 8,
                'first_installment_amount' => 3905.00,
                'first_installment_date' => '2026-01-20',
                'last_installment_amount' => 3905.00,
                'last_installment_date' => '2026-08-20',
                'current_mileage' => 28901,
                'insurance_provider' => 'Travelers Fleet',
                'policy_number' => 'POL-7720',
                'insurance_start_date' => '2026-01-01',
                'insurance_expiry_date' => '2026-12-31',
                'insurance_expired' => false,
                'assigned_driver' => 'Mike Wilson',
                'in_service' => true,
                'seller_name' => 'David Brown',
                'seller_company_name' => 'Blue Ridge Autos',
                'seller_phone' => '+1 555 712-9000',
                'seller_email' => 'fleet@blueridgeautos.com',
                'seller_website' => 'www.blueridgeautos.com',
                'car_photos' => ['f150-front.jpg', 'f150-bed.jpg'],
                'driver_profiles' => [[
                    'name' => 'Mike Wilson',
                    'phone' => '(555) 445-9088',
                    'email' => 'mike.wilson@example.com',
                    'address' => '221 W Fulton, Chicago, IL 60607',
                    'license_number' => 'T33445566',
                    'license_expiry_date' => '2028-01-12',
                    'license_expired' => false,
                ]],
                'insurance_documents' => [[
                    'insurance_company' => 'Travelers Fleet',
                    'policy_number' => 'POL-7720',
                    'policy_start_date' => '2026-01-01',
                    'policy_expiry_date' => '2026-12-31',
                    'expired' => false,
                    'document_name' => 'travelers_f150.pdf',
                ]],
                'safety_equipments' => $this->defaultSafetyEquipment(),
                'status' => 1,
                'last_maintenance_date' => '2026-03-15',
                'next_maintenance_date' => '2026-07-15',
                'notes' => 'Assigned to heavy material runs.',
            ],
            [
                'vehicle_number' => 'BG-004',
                'make_brand' => 'Chevrolet',
                'model' => 'Silverado',
                'vehicle_type' => 'Truck',
                'vehicle_year' => 2023,
                'color' => 'Black',
                'vin' => '4HGCM82633A004355',
                'fuel_type' => 'Diesel',
                'vehicle_keys_tag_no' => 'VT-00990',
                'plate_number' => 'GHI-3456',
                'plate_expiry_date' => '2027-01-30',
                'assignment_start_date' => '2026-03-01',
                'purchase_date' => '2023-01-09',
                'purchase_price' => 3562.00,
                'purchase_invoice_number' => 'IV-2026-0011',
                'invoice_date' => '2026-03-02',
                'sales_tax' => 3100.00,
                'subtotal' => 32520.00,
                'total_paid' => 35620.00,
                'number_of_installments' => 10,
                'first_installment_amount' => 3562.00,
                'first_installment_date' => '2026-03-05',
                'last_installment_amount' => 3562.00,
                'last_installment_date' => '2026-12-05',
                'current_mileage' => 15678,
                'insurance_provider' => 'Allianz Insurance',
                'policy_number' => 'POL-6610',
                'insurance_start_date' => '2026-03-01',
                'insurance_expiry_date' => '2027-02-28',
                'insurance_expired' => false,
                'assigned_driver' => 'Emily Davis',
                'in_service' => false,
                'seller_name' => 'Emily Davis',
                'seller_company_name' => 'Fleet House',
                'seller_phone' => '+1 555 321-1000',
                'seller_email' => 'sales@fleethouse.com',
                'seller_website' => 'www.fleethouse.com',
                'car_photos' => ['silverado-left.jpg'],
                'driver_profiles' => [[
                    'name' => 'Emily Davis',
                    'phone' => '(555) 882-1133',
                    'email' => 'emily.davis@example.com',
                    'address' => '89 Lakeview, Milwaukee, WI 53202',
                    'license_number' => 'C11122334',
                    'license_expiry_date' => '2027-09-01',
                    'license_expired' => false,
                ]],
                'insurance_documents' => [[
                    'insurance_company' => 'Allianz Insurance',
                    'policy_number' => 'POL-6610',
                    'policy_start_date' => '2026-03-01',
                    'policy_expiry_date' => '2027-02-28',
                    'expired' => false,
                    'document_name' => 'silverado-insurance.pdf',
                ]],
                'safety_equipments' => $this->defaultSafetyEquipment(),
                'status' => 2,
                'last_maintenance_date' => '2026-04-11',
                'next_maintenance_date' => '2026-08-11',
                'notes' => 'Reserved for overflow haulage.',
            ],
            [
                'vehicle_number' => 'BG-005',
                'make_brand' => 'Nissan',
                'model' => 'Patrol',
                'vehicle_type' => 'SUV',
                'vehicle_year' => 2021,
                'color' => 'Gray',
                'vin' => '5HGCM82633A004356',
                'fuel_type' => 'Gasoline',
                'vehicle_keys_tag_no' => 'VT-00991',
                'plate_number' => 'JKL-7890',
                'plate_expiry_date' => '2026-09-18',
                'assignment_start_date' => '2026-01-25',
                'purchase_date' => '2021-10-19',
                'purchase_price' => 4361.75,
                'purchase_invoice_number' => 'IV-2025-0214',
                'invoice_date' => '2026-01-25',
                'sales_tax' => 4410.00,
                'subtotal' => 47931.00,
                'total_paid' => 52341.00,
                'number_of_installments' => 12,
                'first_installment_amount' => 4361.75,
                'first_installment_date' => '2026-01-28',
                'last_installment_amount' => 4361.75,
                'last_installment_date' => '2026-12-28',
                'current_mileage' => 52341,
                'insurance_provider' => 'Nationwide Fleet',
                'policy_number' => 'POL-6101',
                'insurance_start_date' => '2026-01-01',
                'insurance_expiry_date' => '2026-12-31',
                'insurance_expired' => false,
                'assigned_driver' => 'David Brown',
                'in_service' => false,
                'seller_name' => 'Robert Taylor',
                'seller_company_name' => 'Peak Motors',
                'seller_phone' => '+1 555 224-6789',
                'seller_email' => 'hello@peakmotors.com',
                'seller_website' => 'www.peakmotors.com',
                'car_photos' => ['patrol-main.jpg'],
                'driver_profiles' => [[
                    'name' => 'David Brown',
                    'phone' => '(555) 707-1100',
                    'email' => 'david.brown@example.com',
                    'address' => '31 Pine Road, Madison, WI 53703',
                    'license_number' => 'N66778890',
                    'license_expiry_date' => '2027-04-19',
                    'license_expired' => false,
                ]],
                'insurance_documents' => [[
                    'insurance_company' => 'Nationwide Fleet',
                    'policy_number' => 'POL-6101',
                    'policy_start_date' => '2026-01-01',
                    'policy_expiry_date' => '2026-12-31',
                    'expired' => false,
                    'document_name' => 'patrol-insurance.pdf',
                ]],
                'safety_equipments' => $this->defaultSafetyEquipment(),
                'status' => 3,
                'last_maintenance_date' => '2026-05-01',
                'next_maintenance_date' => '2026-05-26',
                'notes' => 'Currently in scheduled maintenance.',
            ],
            [
                'vehicle_number' => 'BG-006',
                'make_brand' => 'Toyota',
                'model' => 'Prado',
                'vehicle_type' => 'SUV',
                'vehicle_year' => 2022,
                'color' => 'Pearl White',
                'vin' => '6HGCM82633A004357',
                'fuel_type' => 'Diesel',
                'vehicle_keys_tag_no' => 'VT-00992',
                'plate_number' => 'MNO-1234',
                'plate_expiry_date' => '2027-03-22',
                'assignment_start_date' => '2026-02-15',
                'purchase_date' => '2022-05-12',
                'purchase_price' => 4776.25,
                'purchase_invoice_number' => 'IV-2026-0032',
                'invoice_date' => '2026-02-20',
                'sales_tax' => 2950.00,
                'subtotal' => 35260.00,
                'total_paid' => 38210.00,
                'number_of_installments' => 8,
                'first_installment_amount' => 4776.25,
                'first_installment_date' => '2026-02-20',
                'last_installment_amount' => 4776.25,
                'last_installment_date' => '2026-09-20',
                'current_mileage' => 38210,
                'insurance_provider' => 'Travelers Fleet',
                'policy_number' => 'POL-8822',
                'insurance_start_date' => '2026-02-01',
                'insurance_expiry_date' => '2027-01-31',
                'insurance_expired' => false,
                'assigned_driver' => 'Lisa Anderson',
                'in_service' => true,
                'seller_name' => 'Lisa Anderson',
                'seller_company_name' => 'Premier Wheels',
                'seller_phone' => '+1 555 778-1123',
                'seller_email' => 'fleet@premierwheels.com',
                'seller_website' => 'www.premierwheels.com',
                'car_photos' => ['prado-front.jpg'],
                'driver_profiles' => [[
                    'name' => 'Lisa Anderson',
                    'phone' => '(555) 505-1200',
                    'email' => 'lisa.anderson@example.com',
                    'address' => '90 Jackson St, Aurora, IL 60505',
                    'license_number' => 'P00998877',
                    'license_expiry_date' => '2028-06-10',
                    'license_expired' => false,
                ]],
                'insurance_documents' => [[
                    'insurance_company' => 'Travelers Fleet',
                    'policy_number' => 'POL-8822',
                    'policy_start_date' => '2026-02-01',
                    'policy_expiry_date' => '2027-01-31',
                    'expired' => false,
                    'document_name' => 'prado-coverage.pdf',
                ]],
                'safety_equipments' => $this->defaultSafetyEquipment(),
                'status' => 1,
                'last_maintenance_date' => '2026-04-04',
                'next_maintenance_date' => '2026-08-04',
                'notes' => 'Regional supervisor transport.',
            ],
            [
                'vehicle_number' => 'BG-007',
                'make_brand' => 'Mitsubishi',
                'model' => 'Pajero',
                'vehicle_type' => 'SUV',
                'vehicle_year' => 2020,
                'color' => 'Graphite',
                'vin' => '7HGCM82633A004358',
                'fuel_type' => 'Gasoline',
                'vehicle_keys_tag_no' => 'VT-00993',
                'plate_number' => 'PQR-5678',
                'plate_expiry_date' => '2026-08-17',
                'assignment_start_date' => '2026-04-01',
                'purchase_date' => '2020-09-01',
                'purchase_price' => 5127.00,
                'purchase_invoice_number' => 'IV-2026-0059',
                'invoice_date' => '2026-04-03',
                'sales_tax' => 4800.00,
                'subtotal' => 56724.00,
                'total_paid' => 61524.00,
                'number_of_installments' => 12,
                'first_installment_amount' => 5127.00,
                'first_installment_date' => '2026-04-10',
                'last_installment_amount' => 5127.00,
                'last_installment_date' => '2027-03-10',
                'current_mileage' => 61524,
                'insurance_provider' => 'State Insurance',
                'policy_number' => 'POL-9017',
                'insurance_start_date' => '2026-04-01',
                'insurance_expiry_date' => '2027-03-31',
                'insurance_expired' => false,
                'assigned_driver' => 'Robert Taylor',
                'in_service' => false,
                'seller_name' => 'Robert Taylor',
                'seller_company_name' => 'Metro SUV Traders',
                'seller_phone' => '+1 555 455-9911',
                'seller_email' => 'sales@metrosuv.com',
                'seller_website' => 'www.metrosuv.com',
                'car_photos' => ['pajero-main.jpg'],
                'driver_profiles' => [[
                    'name' => 'Robert Taylor',
                    'phone' => '(555) 213-4455',
                    'email' => 'robert.taylor@example.com',
                    'address' => '18 North St, Green Bay, WI 54301',
                    'license_number' => 'M45670123',
                    'license_expiry_date' => '2028-02-11',
                    'license_expired' => false,
                ]],
                'insurance_documents' => [[
                    'insurance_company' => 'State Insurance',
                    'policy_number' => 'POL-9017',
                    'policy_start_date' => '2026-04-01',
                    'policy_expiry_date' => '2027-03-31',
                    'expired' => false,
                    'document_name' => 'pajero-policy.pdf',
                ]],
                'safety_equipments' => $this->defaultSafetyEquipment(),
                'status' => 2,
                'last_maintenance_date' => '2026-04-18',
                'next_maintenance_date' => '2026-08-18',
                'notes' => 'Ready for reassignment.',
            ],
            [
                'vehicle_number' => 'BG-008',
                'make_brand' => 'Honda',
                'model' => 'Accord',
                'vehicle_type' => 'Sedan',
                'vehicle_year' => 2023,
                'color' => 'Blue',
                'vin' => '8HGCM82633A004359',
                'fuel_type' => 'Diesel',
                'vehicle_keys_tag_no' => 'VT-00994',
                'plate_number' => 'STU-9012',
                'plate_expiry_date' => '2027-02-10',
                'assignment_start_date' => '2026-05-01',
                'purchase_date' => '2023-02-12',
                'purchase_price' => 4152.00,
                'purchase_invoice_number' => 'IV-2026-0072',
                'invoice_date' => '2026-05-02',
                'sales_tax' => 1150.00,
                'subtotal' => 11306.00,
                'total_paid' => 12456.00,
                'number_of_installments' => 3,
                'first_installment_amount' => 4152.00,
                'first_installment_date' => '2026-05-10',
                'last_installment_amount' => 4152.00,
                'last_installment_date' => '2026-07-10',
                'current_mileage' => 12456,
                'insurance_provider' => 'Allianz Insurance',
                'policy_number' => 'POL-3451',
                'insurance_start_date' => '2026-05-01',
                'insurance_expiry_date' => '2027-04-30',
                'insurance_expired' => false,
                'assigned_driver' => 'Jennifer White',
                'in_service' => false,
                'seller_name' => 'Jennifer White',
                'seller_company_name' => 'Cityline Auto',
                'seller_phone' => '+1 555 111-7090',
                'seller_email' => 'fleet@citylineauto.com',
                'seller_website' => 'www.citylineauto.com',
                'car_photos' => ['accord-main.jpg'],
                'driver_profiles' => [[
                    'name' => 'Jennifer White',
                    'phone' => '(555) 331-7890',
                    'email' => 'jennifer.white@example.com',
                    'address' => '8 South Blvd, Naperville, IL 60540',
                    'license_number' => 'A99887766',
                    'license_expiry_date' => '2028-04-22',
                    'license_expired' => false,
                ]],
                'insurance_documents' => [[
                    'insurance_company' => 'Allianz Insurance',
                    'policy_number' => 'POL-3451',
                    'policy_start_date' => '2026-05-01',
                    'policy_expiry_date' => '2027-04-30',
                    'expired' => false,
                    'document_name' => 'accord_policy.pdf',
                ]],
                'safety_equipments' => $this->defaultSafetyEquipment(),
                'status' => 3,
                'last_maintenance_date' => '2026-05-05',
                'next_maintenance_date' => '2026-05-27',
                'notes' => 'Temporary maintenance due to brake check.',
            ],
        ];

        $currentYear = date('Y');

        foreach ($items as $index => $data) {
            $vehicleCode = sprintf('VEH-%s-%03d', $currentYear, $index + 1);
            $payload = array_merge($data, [
                'project_id' => 1,
                'vehicle_code' => $vehicleCode,
                'inserted_by' => 0,
                'updated_by' => 0,
                'is_deleted' => 0,
            ]);

            $vehicle = Vehicle::query()
                ->where('vehicle_number', $data['vehicle_number'])
                ->orWhere('vehicle_code', $vehicleCode)
                ->first();

            if ($vehicle) {
                $vehicle->update($payload);
                continue;
            }

            Vehicle::create($payload);
        }
    }

    protected function defaultSafetyEquipment(): array
    {
        return [
            ['equipment' => 'Dashcam', 'available' => true, 'condition' => 'Good', 'notes' => 'Front & Rear'],
            ['equipment' => 'Fire Extinguisher', 'available' => true, 'condition' => 'Good', 'notes' => '2.5 kg ABC'],
            ['equipment' => 'First Aid Kit', 'available' => true, 'condition' => 'Good', 'notes' => 'Complete'],
            ['equipment' => 'Reflective Triangles', 'available' => true, 'condition' => 'Good', 'notes' => 'Set of 3'],
            ['equipment' => 'GPS Tracker', 'available' => true, 'condition' => 'Good', 'notes' => 'Installed'],
        ];
    }
}
