<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\AccountMessage; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage;
class AccountMessageController extends Controller {
 public function index(Request $r){$folder=$r->input('folder','inbox'); abort_unless(in_array($folder,['inbox','sent','trash']),422); $q=$this->query($r)->where('folder',$folder); if($r->filled('search')){$s=$r->string('search')->trim();$q->where(fn($x)=>$x->where('subject','like',"%$s%")->orWhere('from_name','like',"%$s%")->orWhere('to_name','like',"%$s%"));} return ['success'=>true,'data'=>$q->latest('sent_at')->get()->map(fn($m)=>$this->item($m)),'counts'=>$this->counts($r)]; }
 public function show(Request $r, AccountMessage $message){$this->guard($r,$message); if($message->folder==='inbox'&&$message->status==='unread')$message->update(['status'=>'read','read_at'=>now()]); return ['success'=>true,'data'=>$this->item($message->fresh(),true),'counts'=>$this->counts($r)];}
 public function store(Request $r){$d=$r->validate(['to_name'=>'required|string|max:150','subject'=>'required|string|max:255','message'=>'required|string','attachments.*'=>'file|max:10240|mimes:pdf,doc,docx,xls,xlsx,jpg,jpeg,png']); $u=$r->user(); $files=[]; foreach($r->file('attachments',[]) as $f){$path=$f->store('account-messages/'.$u->project_id,'public');$files[]=['name'=>$f->getClientOriginalName(),'path'=>$path,'size'=>$f->getSize()];} $m=AccountMessage::create(['project_id'=>$u->project_id,'user_id'=>$u->id,'message_no'=>$this->nextNo($u->project_id,'OUT'),'direction'=>'out','folder'=>'sent','status'=>'sent','from_name'=>$u->company_name?:$u->name,'to_name'=>$d['to_name'],'subject'=>$d['subject'],'message'=>$d['message'],'attachments'=>$files,'sent_at'=>now()]); return response()->json(['success'=>true,'data'=>$this->item($m,true),'message'=>'Message sent.'],201);}
 public function trash(Request $r,AccountMessage $message){$this->guard($r,$message);$message->update(['deleted_from'=>$message->folder,'folder'=>'trash','deleted_at'=>now()]);return ['success'=>true,'counts'=>$this->counts($r)];}
 public function restore(Request $r,AccountMessage $message){$this->guard($r,$message);abort_unless($message->folder==='trash',422);$message->update(['folder'=>$message->deleted_from?:($message->direction==='out'?'sent':'inbox'),'deleted_at'=>null,'deleted_from'=>null]);return ['success'=>true,'counts'=>$this->counts($r)];}
 public function destroy(Request $r,AccountMessage $message){$this->guard($r,$message);abort_unless($message->folder==='trash',422);foreach($message->attachments??[] as $a)if(!empty($a['path']))Storage::disk('public')->delete($a['path']);$message->delete();return ['success'=>true,'counts'=>$this->counts($r)];}
 private function query(Request $r){return AccountMessage::where('project_id',$r->user()->project_id)->where('user_id',$r->user()->id);} private function guard(Request $r,AccountMessage $m){abort_unless((int)$m->project_id===(int)$r->user()->project_id&&(int)$m->user_id===(int)$r->user()->id,404);} private function counts(Request $r){return ['inbox'=>$this->query($r)->where('folder','inbox')->count(),'sent'=>$this->query($r)->where('folder','sent')->count(),'trash'=>$this->query($r)->where('folder','trash')->count()];} private function nextNo($p,$dir){$n=AccountMessage::where('project_id',$p)->count()+1;return "MSG-$dir-".now()->format('Y').'-'.str_pad((string)$n,4,'0',STR_PAD_LEFT);} private function item($m,$full=false){return ['id'=>$m->id,'message_no'=>$m->message_no,'direction'=>$m->direction,'folder'=>$m->folder,'status'=>$m->status,'from_name'=>$m->from_name,'to_name'=>$m->to_name,'subject'=>$m->subject,'message'=>$full?$m->message:null,'attachments'=>$m->attachments??[],'sent_at'=>$m->sent_at?->toIso8601String(),'deleted_at'=>$m->deleted_at?->toIso8601String(),'deleted_from'=>$m->deleted_from];}
}
