<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\EmployeeProfile; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class EmployeeProfileController extends Controller {
 public function index(Request $r){$q=EmployeeProfile::where('project_id',$r->user()->project_id)->where('is_deleted',false);if($r->filled('search')){$s=$r->string('search')->trim();$q->where(fn($x)=>$x->where('account_name','like',"%$s%")->orWhere('employee_id','like',"%$s%")->orWhere('department','like',"%$s%"));}if($r->filled('status'))$q->where('status_active',$r->boolean('status'));$rows=$q->latest()->get()->map(fn($e)=>$this->present($e));return response()->json(['success'=>true,'data'=>$rows,'summary'=>['total'=>$rows->count(),'active'=>$rows->where('status_active',true)->count(),'inactive'=>$rows->where('status_active',false)->count(),'expired'=>$rows->filter(fn($e)=>$e['screening_expired'])->count()]]);}
 public function show(Request $r,EmployeeProfile $employee){$this->auth($r,$employee);return response()->json(['success'=>true,'data'=>$this->present($employee)]);}
 public function store(Request $r){$p=$r->user()->project_id;$e=DB::transaction(function()use($r,$p){$d=$this->valid($r);$n='EMP-'.str_pad((string)(EmployeeProfile::where('project_id',$p)->count()+1),6,'0',STR_PAD_LEFT);$d['employee_id']=$d['employee_id']??'EID-'.substr($n,4);return EmployeeProfile::create($d+['project_id'=>$p,'account_type'=>4,'system_prefix'=>'EMP','system_no'=>$n,'inserted_by'=>$r->user()->id,'updated_by'=>$r->user()->id,'is_deleted'=>false]);});return response()->json(['success'=>true,'data'=>$this->present($e),'message'=>'Employee created.'],201);}
 public function update(Request $r,EmployeeProfile $employee){$this->auth($r,$employee);$employee->update($this->valid($r)+['updated_by'=>$r->user()->id]);return response()->json(['success'=>true,'data'=>$this->present($employee->fresh()),'message'=>'Employee updated.']);}
 public function destroy(Request $r,EmployeeProfile $employee){$this->auth($r,$employee);$employee->update(['is_deleted'=>true,'updated_by'=>$r->user()->id]);return response()->json(['success'=>true,'message'=>'Employee deleted.']);}
 private function valid(Request $r):array{return $r->validate(['account_name'=>'required|string|max:255','employee_id'=>'nullable|string|max:60','department'=>'required|string|max:100','position'=>'required|string|max:100','hire_date'=>'required|date','account_no'=>'nullable|string|max:60','cell_phone'=>'nullable|string|max:50','email'=>'nullable|email|max:255','status_active'=>'required|boolean','screening_expires_at'=>'nullable|date']);} private function auth(Request $r,EmployeeProfile $e):void{abort_unless((int)$e->project_id===(int)$r->user()->project_id,404);} private function present(EmployeeProfile $e):array{return ['id'=>$e->id,'employee_no'=>$e->system_no,'employee_id'=>$e->employee_id,'full_name'=>$e->account_name,'department'=>$e->department,'position'=>$e->position,'hire_date'=>$e->hire_date?->format('Y-m-d'),'account_no'=>$e->account_no,'phone'=>$e->cell_phone,'email'=>$e->email,'status_active'=>$e->status_active,'screening_expires_at'=>$e->screening_expires_at?->format('Y-m-d'),'screening_expired'=>$e->screening_expires_at&&$e->screening_expires_at->isPast()];}}
