import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import App from './App.vue'
import 'bootstrap/dist/css/bootstrap.min.css'
import './assets/app.css'
import 'bootstrap/dist/js/bootstrap.bundle.min.js'
import { i18n, initI18n } from './i18n'
import { initPageTranslator } from './i18n/pageTranslator'
import { initAuth, loadMe, clearToken } from './api/auth'
import { authState, setUser } from './store/auth'
import client from './api/client'
import { setFlash } from './store/flash'
import { FLASH } from './config/messages'
import { formatPlanLabel, getRequiredPlan, hasPlanFeature } from './config/planFeatures'
import { hasUserPermission } from './config/permissions'

import Home from './pages/Home.vue'
import About from './pages/About.vue'
import Plans from './pages/Plans.vue'
import Contact from './pages/Contact.vue'
import Login from './pages/Login.vue'
import Register from './pages/Register.vue'
import ForgotPassword from './pages/ForgotPassword.vue'
import ForgotUsername from './pages/ForgotUsername.vue'
import Terms from './pages/Terms.vue'
import Verify from './pages/Verify.vue'
import AccountSetup from './pages/AccountSetup.vue'
import AccountSetupSuccess from './pages/AccountSetupSuccess.vue'
import Dashboard from './pages/Dashboard.vue'
import TodoList from './pages/TodoList.vue'
import TodoEntry from './pages/TodoEntry.vue'
import Parcels from './pages/Parcels.vue'
import Users from './pages/Users.vue'
import NotificationLogs from './pages/NotificationLogs.vue'
import NotificationParcelArrival from './pages/NotificationParcelArrival.vue'
import NotificationPickupRequest from './pages/NotificationPickupRequest.vue'
import NotificationParcelReturn from './pages/NotificationParcelReturn.vue'
import DeliveryStatus from './pages/DeliveryStatus.vue'
import DeliveryNewArrival from './pages/DeliveryNewArrival.vue'
import DeliveryPickUp from './pages/DeliveryPickUp.vue'
import DeliveryDelivered from './pages/DeliveryDelivered.vue'
import DeliveryRejected from './pages/DeliveryRejected.vue'
import DeliveryLostDamaged from './pages/DeliveryLostDamaged.vue'
import DeliveryExpired from './pages/DeliveryExpired.vue'
import AccountProfile from './pages/AccountProfile.vue'
import AccountStatus from './pages/AccountStatus.vue'
import AccountBilling from './pages/AccountBilling.vue'
import AccountSecurity from './pages/AccountSecurity.vue'
import AccountRecovery from './pages/AccountRecovery.vue'
import PlanHistory from './pages/PlanHistory.vue'
import Calendar from './pages/Calendar.vue'
import Announcements from './pages/Announcements.vue'
import FacilitiesProperty from './pages/FacilitiesProperty.vue'
import LockerList from './pages/LockerList.vue'
import LockerAccess from './pages/LockerAccess.vue'
import LockerFacilityOwned from './pages/LockerFacilityOwned.vue'
import LockerThirdPartyOwned from './pages/LockerThirdPartyOwned.vue'
import ParcelStorage from './pages/ParcelStorage.vue'
import ParcelStorageList from './pages/ParcelStorageList.vue'
import Recipients from './pages/Recipients.vue'
import RecipientList from './pages/RecipientList.vue'
import Couriers from './pages/Couriers.vue'
import CourierList from './pages/CourierList.vue'
import DeliveryItems from './pages/DeliveryItems.vue'
import DeliveryItemList from './pages/DeliveryItemList.vue'
import DeliveryMethods from './pages/DeliveryMethods.vue'
import DeliveryMethodList from './pages/DeliveryMethodList.vue'
import Sellers from './pages/Sellers.vue'
import SellerList from './pages/SellerList.vue'
import DateTimeSettings from './pages/DateTimeSettings.vue'
import ThemeSettings from './pages/ThemeSettings.vue'
import LanguageSettings from './pages/LanguageSettings.vue'
import ParcelHoldingLimits from './pages/ParcelHoldingLimits.vue'
import NotificationSettings from './pages/NotificationSettings.vue'
import ApprovalSettings from './pages/ApprovalSettings.vue'
import ApprovalSlaDashboard from './pages/ApprovalSlaDashboard.vue'
import EmailInbox from './email/pages/EmailInbox.vue'
import EmailSent from './email/pages/EmailSent.vue'
import EmailDrafts from './email/pages/EmailDrafts.vue'
import EmailTrash from './email/pages/EmailTrash.vue'
import EmailCompose from './email/pages/EmailCompose.vue'
import EmailDetail from './email/pages/EmailDetail.vue'
import EmailTemplates from './email/pages/EmailTemplates.vue'
import EmailSettings from './email/pages/EmailSettings.vue'
import EmailThread from './email/pages/EmailThread.vue'
import EmailDashboard from './email/pages/EmailDashboard.vue'
import WorkforceDailyReports from './pages/WorkforceDailyReports.vue'
import WorkforceIncidentReports from './pages/WorkforceIncidentReports.vue'
import WorkforceTimesheets from './pages/WorkforceTimesheets.vue'
import PickupFrontDesk from './pages/PickupFrontDesk.vue'
import PickupFacilityLocker from './pages/PickupFacilityLocker.vue'
import PickupExternalLocker from './pages/PickupExternalLocker.vue'
import PickupCounterStaff from './pages/PickupCounterStaff.vue'
import PickupSlaDashboard from './pages/PickupSlaDashboard.vue'
import ParcelReportPending from './pages/ParcelReportPending.vue'
import ParcelReportPickedUp from './pages/ParcelReportPickedUp.vue'
import ParcelReportDelivered from './pages/ParcelReportDelivered.vue'
import ParcelReportRejected from './pages/ParcelReportRejected.vue'
import ParcelReportLostDamaged from './pages/ParcelReportLostDamaged.vue'
import ParcelReportExpired from './pages/ParcelReportExpired.vue'
import AccountHolder from './pages/AccountHolder.vue'
import AccountHolders from './pages/AccountHolder.vue'
import PaymentMethods from './pages/PaymentMethod.vue'
import SalesTax from './pages/SalesTax.vue'
import InvoiceTerms from './pages/InvoiceTerms.vue'
import InventoryItems from './pages/InventoryItems.vue'
import ServiceItems from './pages/ServiceItems.vue'
import JobSites from './pages/JobSites.vue'
import Estimation from './pages/Estimation.vue'
import Quotation from './pages/Quotation.vue'
import JobOrders from './pages/JobOrders.vue'
import JobOrderDailyWorkLog from './pages/JobOrderDailyWorkLog.vue'
import JobOrderShortStatus from './pages/JobOrderShortStatus.vue'
import JobOrderFullStatus from './pages/JobOrderFullStatus.vue'
import JobOrderTracker from './pages/JobOrderTracker.vue'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    { path: '/', name: 'home', component: Home },
