<?php

use App\Http\Controllers\Api\AccountController;
use App\Http\Controllers\Api\AccountSecurityController;
use App\Http\Controllers\Api\AccountMessageController;
use App\Http\Controllers\Api\AccountNotificationController;
use App\Http\Controllers\Api\SupportTicketController;
use App\Http\Controllers\Api\AccountHolderController;
use App\Http\Controllers\Api\AccountSetupController;
use App\Http\Controllers\Api\CompanyProfileController;
use App\Http\Controllers\Api\AnnouncementController;
use App\Http\Controllers\Api\AccidentReportController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BillingController;
use App\Http\Controllers\Api\BankProfileController;
use App\Http\Controllers\Api\CalendarEventController;
use App\Http\Controllers\Api\CaptchaController;
use App\Http\Controllers\Api\ContactController;
use App\Http\Controllers\Api\CreditCardController;
use App\Http\Controllers\Api\CountryController;
use App\Http\Controllers\Api\CourierController;
use App\Http\Controllers\Api\CurrencyController;
use App\Http\Controllers\Api\CustomerProfileController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\DateTimeSettingsController;
use App\Http\Controllers\Api\DailyLogController;
use App\Http\Controllers\Api\DeliveryItemController;
use App\Http\Controllers\Api\DeliveryMethodController;
use App\Http\Controllers\Api\DriverController;
use App\Http\Controllers\Api\EmailMessageController;
use App\Http\Controllers\Api\EmailSettingsController;
use App\Http\Controllers\Api\EmailStatsController;
use App\Http\Controllers\Api\EmailTemplateController;
use App\Http\Controllers\Api\EmployeeProfileController;
use App\Http\Controllers\Api\EmailWebhookController;
use App\Http\Controllers\Api\EstimationController;
use App\Http\Controllers\Api\QuotationController;
use App\Http\Controllers\Api\FacilityController;
use App\Http\Controllers\Api\InvoiceTermController;
use App\Http\Controllers\Api\ItemController;
use App\Http\Controllers\Api\InsurancePolicyController;
use App\Http\Controllers\Api\FuelRecordController;
use App\Http\Controllers\Api\RepairMaintenanceRecordController;
use App\Http\Controllers\Api\PurchaseOrderController;
use App\Http\Controllers\Api\PurchaseInvoiceController;
use App\Http\Controllers\Api\PurchaseReturnController;
use App\Http\Controllers\Api\SellerDebitNoteController;
use App\Http\Controllers\Api\SellerCreditNoteController;
use App\Http\Controllers\Api\BillPaymentController;
use App\Http\Controllers\Api\SalesOrderController;
use App\Http\Controllers\Api\SalesInvoiceController;
use App\Http\Controllers\Api\SalesReturnController;
use App\Http\Controllers\Api\CustomerCreditNoteController;
use App\Http\Controllers\Api\InsuranceCompanyController;
use App\Http\Controllers\Api\FixedAssetController;
use App\Http\Controllers\Api\AccountGroupController;
use App\Http\Controllers\Api\ChartOfAccountController;
use App\Http\Controllers\Api\JobOrderController;
use App\Http\Controllers\Api\JobOrderDailyWorkLogController;
use App\Http\Controllers\Api\JobSiteController;
use App\Http\Controllers\Api\LanguageSettingsController;
use App\Http\Controllers\Api\LockerAccessController;
use App\Http\Controllers\Api\LockerController;
use App\Http\Controllers\Api\NotificationLogController;
use App\Http\Controllers\Api\NotificationSettingsController;
use App\Http\Controllers\Api\ParcelController;
use App\Http\Controllers\Api\ParcelHoldingLimitsController;
use App\Http\Controllers\Api\ParcelStorageController;
use App\Http\Controllers\Api\PaymentMethodController;
use App\Http\Controllers\Api\PickupRuleController;
use App\Http\Controllers\Api\PlanController;
use App\Http\Controllers\Api\PlanHistoryController;
use App\Http\Controllers\Api\RecipientController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\SalesChatController;
use App\Http\Controllers\Api\SalesTaxController;
use App\Http\Controllers\Api\SellerController;
use App\Http\Controllers\Api\ServiceItemController;
use App\Http\Controllers\Api\StripeWebhookController;
use App\Http\Controllers\Api\ThemeSettingsController;
use App\Http\Controllers\Api\TodoController;
use App\Http\Controllers\Api\UiTranslationController;
use App\Http\Controllers\Api\UserAdminController;
use App\Http\Controllers\Api\VehicleController;
use App\Http\Controllers\Api\ViolationTicketController;
use App\Http\Controllers\Api\WorkforceApprovalController;
use App\Http\Controllers\Api\WorkforceApprovalSettingsController;
use App\Http\Controllers\Api\WorkforceDailyReportController;
use App\Http\Controllers\Api\WorkforceIncidentReportController;
use App\Http\Controllers\Api\WorkforceStaffAttendanceController;
use App\Http\Controllers\Api\WorkforceStaffRequestController;
use App\Http\Controllers\Api\WorkforceTaskAssignmentController;
use App\Http\Controllers\Api\WorkforceTimesheetController;
use App\Http\Controllers\Api\WorkforceWorkScheduleController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('email/webhooks/bounce', [EmailWebhookController::class, 'bounce']);
    Route::get('captcha', [CaptchaController::class, 'show']);
    Route::get('countries', [CountryController::class, 'index']);
    Route::post('contact', [ContactController::class, 'store']);
    Route::post('stripe/webhook', [StripeWebhookController::class, 'handle']);

    Route::post('register', [AuthController::class, 'register'])->middleware('throttle:5,1');
    Route::post('register/verification-code', [AuthController::class, 'requestRegisterVerificationCode'])->middleware('throttle:3,1');
    // Route::post('login', [AuthController::class, 'login'])->middleware('throttle:10,1');
    Route::post('login', [AuthController::class, 'login']);
    Route::post('login/verification-code', [AuthController::class, 'requestLoginVerificationCode'])->middleware('throttle:3,1');
    Route::post('translations/ui', [UiTranslationController::class, 'translate'])->middleware('throttle:120,1');
    Route::post('verify', [AuthController::class, 'verify'])->middleware('throttle:10,1');
    Route::post('verify/resend', [AuthController::class, 'resendVerification'])->middleware('throttle:3,1');
    Route::post('forgot-password/request', [AuthController::class, 'forgotPasswordRequest'])->middleware('throttle:5,1');
    Route::post('forgot-password/reset', [AuthController::class, 'forgotPasswordReset'])->middleware('throttle:10,1');
    Route::post('forgot-username/request', [AuthController::class, 'forgotUsernameRequest'])->middleware('throttle:5,1');

    Route::get('verify/email/{id}/{hash}', [AuthController::class, 'verifyEmailLink'])
        ->name('api.verify.email')
        ->middleware('throttle:20,1');
    Route::post('sales-chat/reply', [SalesChatController::class, 'reply'])->middleware('throttle:12,1');
    Route::post('website-visits', [\App\Http\Controllers\Api\WebsiteVisitController::class, 'track'])->middleware('throttle:120,1');

    Route::middleware(['auth:sanctum', 'security.activity', 'customer.panel'])->group(function () {
        Route::get('me', [AuthController::class, 'me']);
        Route::post('logout', [AuthController::class, 'logout']);
        Route::post('verify/email/resend', [AuthController::class, 'resendEmailVerification'])->middleware('throttle:6,1');
        Route::get('account-setup', [AccountSetupController::class, 'show']);
        Route::post('account-setup', [AccountSetupController::class, 'store']);
        Route::post('account-setup/logo', [AccountSetupController::class, 'uploadLogo']);
        Route::post('account-setup/insurance-certificate', [AccountSetupController::class, 'uploadInsuranceCertificate']);
        Route::post('account-setup/complete', [AccountSetupController::class, 'complete']);

        Route::get('dashboard', [DashboardController::class, 'summary']);
        Route::get('notifications', [NotificationLogController::class, 'index'])->middleware(['plan.feature:notification_center', 'permission:notifications,read']);
        Route::post('billing/checkout', [BillingController::class, 'checkout']);
        Route::post('billing/portal', [BillingController::class, 'portal']);
        Route::get('super-admin/dashboard', [\App\Http\Controllers\Api\SuperAdminController::class, 'dashboard'])->middleware('platform.admin');
        Route::get('super-admin/customers', [\App\Http\Controllers\Api\SuperAdminController::class, 'customers'])->middleware('platform.admin');
        Route::get('super-admin/customers/{user}', [\App\Http\Controllers\Api\SuperAdminController::class, 'customer'])->middleware('platform.admin');
        Route::patch('super-admin/customers/{user}/status', [\App\Http\Controllers\Api\SuperAdminController::class, 'updateCustomerStatus'])->middleware('platform.admin');
        Route::get('super-admin/customer-users', [\App\Http\Controllers\Api\SuperAdminController::class, 'customerUsers'])->middleware('platform.admin');
        Route::get('super-admin/customer-users/{user}/list', [\App\Http\Controllers\Api\SuperAdminController::class, 'customerUserList'])->middleware('platform.admin');
        Route::get('super-admin/customer-users/{user}/behaviour', [\App\Http\Controllers\Api\SuperAdminController::class, 'userBehaviour'])->middleware('platform.admin');
        Route::get('super-admin/billing', [\App\Http\Controllers\Api\SuperAdminController::class, 'billing'])->middleware('platform.admin');
        Route::get('super-admin/tax-report', [\App\Http\Controllers\Api\SuperAdminController::class, 'taxReport'])->middleware('platform.admin');
        Route::get('super-admin/pending-accounts', [\App\Http\Controllers\Api\SuperAdminController::class, 'pendingAccounts'])->middleware('platform.admin');
        Route::post('super-admin/pending-accounts/{user}/approve', [\App\Http\Controllers\Api\SuperAdminController::class, 'approvePendingAccount'])->middleware('platform.admin');
        Route::get('super-admin/tickets', [\App\Http\Controllers\Api\SuperAdminController::class, 'tickets'])->middleware('platform.admin');
        Route::get('super-admin/tickets/{ticket}', [\App\Http\Controllers\Api\SuperAdminController::class, 'ticket'])->middleware('platform.admin');
        Route::post('super-admin/tickets/{ticket}/actions', [\App\Http\Controllers\Api\SuperAdminController::class, 'ticketAction'])->middleware('platform.admin');
        Route::get('super-admin/audit-logs', [\App\Http\Controllers\Api\SuperAdminController::class, 'auditLogs'])->middleware('platform.admin');
        Route::get('super-admin/calendar', [\App\Http\Controllers\Api\SuperAdminController::class, 'calendar'])->middleware('platform.admin');
        Route::post('super-admin/calendar', [\App\Http\Controllers\Api\SuperAdminController::class, 'storeCalendarEvent'])->middleware('platform.admin');
        Route::get('super-admin/announcements', [\App\Http\Controllers\Api\SuperAdminController::class, 'announcements'])->middleware('platform.admin');
        Route::post('super-admin/announcements', [\App\Http\Controllers\Api\SuperAdminController::class, 'storeAnnouncement'])->middleware('platform.admin');
        Route::get('super-admin/website-visitors', [\App\Http\Controllers\Api\SuperAdminController::class, 'websiteVisitors'])->middleware('platform.admin');
        Route::get('super-admin/emergency-shutdowns', [\App\Http\Controllers\Api\SuperAdminController::class, 'shutdowns'])->middleware('platform.admin');
        Route::post('super-admin/emergency-shutdowns', [\App\Http\Controllers\Api\SuperAdminController::class, 'createShutdown'])->middleware('platform.admin');
        Route::post('super-admin/emergency-shutdowns/{shutdown}/restore', [\App\Http\Controllers\Api\SuperAdminController::class, 'restoreShutdown'])->middleware('platform.admin');
        Route::get('super-admin/external-security', [\App\Http\Controllers\Api\SuperAdminController::class, 'externalSecurity'])->middleware('platform.admin');
        Route::get('super-admin/system-monitoring', [\App\Http\Controllers\Api\SuperAdminController::class, 'systemMonitoring'])->middleware('platform.admin');
        Route::post('super-admin/payment-gateway/import', [\App\Http\Controllers\Api\SuperAdminController::class, 'importPaymentGateway'])->middleware('platform.admin');
        Route::get('super-admin/notifications', [\App\Http\Controllers\Api\SuperAdminController::class, 'notifications'])->middleware('platform.admin');
        Route::post('super-admin/notifications', [\App\Http\Controllers\Api\SuperAdminController::class, 'createNotification'])->middleware('platform.admin');
        Route::get('super-admin/reports/account-status', [\App\Http\Controllers\Api\SuperAdminController::class, 'accountStatusReport'])->middleware('platform.admin');
        Route::get('super-admin/reports/login-history', [\App\Http\Controllers\Api\SuperAdminController::class, 'loginHistoryReport'])->middleware('platform.admin');
        Route::get('super-admin/reports/users-monitoring', [\App\Http\Controllers\Api\SuperAdminController::class, 'usersMonitoringReport'])->middleware('platform.admin');
        Route::get('super-admin/reports/data/{report}', [\App\Http\Controllers\Api\SuperAdminController::class, 'advancedReport'])->middleware('platform.admin');
        Route::get('account/messages', [AccountMessageController::class, 'index'])->middleware('permission:account,read');
        Route::get('account/notifications', [AccountNotificationController::class, 'show'])->middleware('permission:account,read');
        Route::put('account/notifications', [AccountNotificationController::class, 'update'])->middleware('permission:account,edit');
        Route::get('account/support-tickets', [SupportTicketController::class, 'index'])->middleware('permission:account,read');
        Route::post('account/support-tickets', [SupportTicketController::class, 'store'])->middleware('permission:account,edit');
        Route::get('account/support-tickets/{ticket}', [SupportTicketController::class, 'show'])->middleware('permission:account,read');
        Route::post('account/messages', [AccountMessageController::class, 'store'])->middleware('permission:account,edit');
        Route::get('account/messages/{message}', [AccountMessageController::class, 'show'])->middleware('permission:account,read');
        Route::post('account/messages/{message}/trash', [AccountMessageController::class, 'trash'])->middleware('permission:account,edit');
        Route::post('account/messages/{message}/restore', [AccountMessageController::class, 'restore'])->middleware('permission:account,edit');
        Route::delete('account/messages/{message}', [AccountMessageController::class, 'destroy'])->middleware('permission:account,edit');
        Route::get('account/profile', [AccountController::class, 'profile'])->middleware('permission:account,read');
        Route::put('account/profile', [AccountController::class, 'updateProfile'])->middleware('permission:account,edit');
        Route::get('account/company-profile', [CompanyProfileController::class, 'show'])->middleware('permission:account,read');
        Route::put('account/company-profile', [CompanyProfileController::class, 'update'])->middleware('permission:account,edit');
        Route::post('account/company-profile/logo', [CompanyProfileController::class, 'uploadLogo'])->middleware('permission:account,edit');
        Route::get('account/status', [AccountController::class, 'status'])->middleware('permission:account,read');
        Route::get('account/billing', [AccountController::class, 'billing'])->middleware('permission:account,read');
        Route::get('account/tax-report', [AccountController::class, 'taxReport'])->middleware('permission:account,read');
        Route::put('account/billing', [AccountController::class, 'updateBilling'])->middleware('permission:account,edit');
        Route::get('account/security', [AccountSecurityController::class, 'show'])->middleware('permission:account,read');
        Route::put('account/security', [AccountSecurityController::class, 'update'])->middleware('permission:account,edit');
        Route::put('account/security/password', [AccountSecurityController::class, 'changePassword'])->middleware('permission:account,edit');
        Route::put('account/security/pin', [AccountSecurityController::class, 'changePin'])->middleware('permission:account,edit');
        Route::delete('account/security/devices/{device}', [AccountSecurityController::class, 'removeDevice'])->middleware('permission:account,edit');
        Route::post('account/security/logout-all-devices', [AccountSecurityController::class, 'logoutAllDevices'])->middleware('permission:account,edit');
        Route::get('account/recovery', [AccountController::class, 'recovery'])->middleware('permission:account,read');
        Route::put('account/recovery', [AccountController::class, 'updateRecovery'])->middleware('permission:account,edit');
        Route::get('account/invoices', [AccountController::class, 'invoices'])->middleware('permission:account,read');
        Route::get('lockers', [LockerController::class, 'index'])->middleware(['plan.feature:storage_management', 'permission:parcels,read']);
        Route::get('lockers/{locker}', [LockerController::class, 'show'])->middleware(['plan.feature:storage_management', 'permission:parcels,read']);
        Route::post('lockers', [LockerController::class, 'store'])->middleware(['plan.feature:storage_management', 'permission:parcels,create']);
        Route::put('lockers/{locker}', [LockerController::class, 'update'])->middleware(['plan.feature:storage_management', 'permission:parcels,edit']);
        Route::delete('lockers/{locker}', [LockerController::class, 'destroy'])->middleware(['plan.feature:storage_management', 'permission:parcels,delete']);
        Route::get('locker-accesses', [LockerAccessController::class, 'index'])->middleware(['plan.feature:locker_access_management', 'permission:parcels,read']);
        Route::post('locker-accesses', [LockerAccessController::class, 'store'])->middleware(['plan.feature:locker_access_management', 'permission:parcels,create']);
        Route::put('locker-accesses/{lockerAccess}', [LockerAccessController::class, 'update'])->middleware(['plan.feature:locker_access_management', 'permission:parcels,edit']);
        Route::delete('locker-accesses/{lockerAccess}', [LockerAccessController::class, 'destroy'])->middleware(['plan.feature:locker_access_management', 'permission:parcels,delete']);
        Route::get('plans/current', [PlanController::class, 'current'])->middleware('permission:plans,read');
        Route::post('plans/select', [PlanController::class, 'select'])->middleware('permission:plans,edit');
        Route::get('plans/history', [PlanHistoryController::class, 'index'])->middleware('permission:plans,read');
        Route::get('parcels', [ParcelController::class, 'index'])->middleware('permission:parcels,read');
        Route::post('parcels', [ParcelController::class, 'store'])->middleware('permission:parcels,create');
        Route::get('parcels/{parcel}', [ParcelController::class, 'show'])->middleware('permission:parcels,read');
        Route::put('parcels/{parcel}', [ParcelController::class, 'update'])->middleware('permission:parcels,edit');
        Route::delete('parcels/{parcel}', [ParcelController::class, 'destroy'])->middleware('permission:parcels,delete');
        Route::post('parcels/scan', [ParcelController::class, 'scan'])->middleware('permission:parcels,edit');
        Route::get('parcels/{parcel}/history', [ParcelController::class, 'history'])->middleware('permission:parcels,read');

        Route::get('reports/parcels', [ReportController::class, 'exportParcels'])->middleware(['plan.feature:reporting', 'permission:reports,export']);

        Route::get('admin/users', [UserAdminController::class, 'index'])->middleware(['plan.feature:user_management', 'permission:users,read']);
        Route::post('admin/users', [UserAdminController::class, 'store'])->middleware(['plan.feature:user_management', 'permission:users,create']);
        Route::patch('admin/users/{user}', [UserAdminController::class, 'update'])->middleware(['plan.feature:user_management', 'permission:users,edit']);
        Route::get('admin/users/{user}/permissions', [UserAdminController::class, 'permissions'])->middleware(['plan.feature:user_management', 'permission:users,read']);
        Route::put('admin/users/{user}/permissions', [UserAdminController::class, 'updatePermissions'])->middleware(['plan.feature:user_management', 'permission:users,edit']);

        Route::get('todo', [TodoController::class, 'index']);
        Route::get('todo/assignees', [TodoController::class, 'assignees']);
        Route::post('todo', [TodoController::class, 'store']);
        Route::get('todo/{todo}', [TodoController::class, 'show']);
        Route::put('todo/{todo}', [TodoController::class, 'update']);
        Route::post('todo/{todo}/review', [TodoController::class, 'review']);
        Route::delete('todo/{todo}', [TodoController::class, 'destroy']);

        Route::get('facilities', [FacilityController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('facilities', [FacilityController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('facilities/{facility}', [FacilityController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('facilities/{facility}', [FacilityController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('facilities/{facility}', [FacilityController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('parcel-storages', [ParcelStorageController::class, 'index'])->middleware(['plan.feature:storage_management', 'permission:parcels,read']);
        Route::post('parcel-storages', [ParcelStorageController::class, 'store'])->middleware(['plan.feature:storage_management', 'permission:parcels,create']);
        Route::get('parcel-storages/{parcelStorage}', [ParcelStorageController::class, 'show'])->middleware(['plan.feature:storage_management', 'permission:parcels,read']);
        Route::put('parcel-storages/{parcelStorage}', [ParcelStorageController::class, 'update'])->middleware(['plan.feature:storage_management', 'permission:parcels,edit']);
        Route::delete('parcel-storages/{parcelStorage}', [ParcelStorageController::class, 'destroy'])->middleware(['plan.feature:storage_management', 'permission:parcels,delete']);

        Route::get('recipients', [RecipientController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('recipients', [RecipientController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('recipients/{recipient}', [RecipientController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('recipients/{recipient}', [RecipientController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('recipients/{recipient}', [RecipientController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('couriers', [CourierController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('couriers', [CourierController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('couriers/{courier}', [CourierController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('couriers/{courier}', [CourierController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('couriers/{courier}', [CourierController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('currencies', [CurrencyController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('currencies', [CurrencyController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('currencies/{currency}', [CurrencyController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('currencies/{currency}', [CurrencyController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('currencies/{currency}', [CurrencyController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('delivery-items', [DeliveryItemController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('delivery-items', [DeliveryItemController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('delivery-items/{deliveryItem}', [DeliveryItemController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('delivery-items/{deliveryItem}', [DeliveryItemController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('delivery-items/{deliveryItem}', [DeliveryItemController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('delivery-methods', [DeliveryMethodController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('delivery-methods', [DeliveryMethodController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('delivery-methods/{deliveryMethod}', [DeliveryMethodController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('delivery-methods/{deliveryMethod}', [DeliveryMethodController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('delivery-methods/{deliveryMethod}', [DeliveryMethodController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('sellers', [SellerController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('sellers', [SellerController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('sellers/{seller}', [SellerController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('sellers/{seller}', [SellerController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('sellers/{seller}', [SellerController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('account-holders', [AccountHolderController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('account-holders', [AccountHolderController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('account-holders/{id}/edit', [AccountHolderController::class, 'edit'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('account-holders/{id}', [AccountHolderController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('account-holders/{id}', [AccountHolderController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::get('banks/options', [BankProfileController::class, 'options'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('banks', [BankProfileController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('banks', [BankProfileController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('banks/{bank}', [BankProfileController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('banks/{bank}', [BankProfileController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('banks/{bank}', [BankProfileController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::get('insurance-companies/options', [InsuranceCompanyController::class, 'options'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('insurance-companies', [InsuranceCompanyController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('insurance-companies', [InsuranceCompanyController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('insurance-companies/{insuranceCompany}', [InsuranceCompanyController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('insurance-companies/{insuranceCompany}', [InsuranceCompanyController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('insurance-companies/{insuranceCompany}', [InsuranceCompanyController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::get('fixed-assets/options', [FixedAssetController::class, 'options'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('fixed-assets', [FixedAssetController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('fixed-assets', [FixedAssetController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('fixed-assets/{fixedAsset}', [FixedAssetController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('fixed-assets/{fixedAsset}', [FixedAssetController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('fixed-assets/{fixedAsset}', [FixedAssetController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::get('account-groups/options', [AccountGroupController::class, 'options'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('account-groups', [AccountGroupController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('account-groups', [AccountGroupController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('account-groups/{accountGroup}', [AccountGroupController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('account-groups/{accountGroup}', [AccountGroupController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('account-groups/{accountGroup}', [AccountGroupController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::get('chart-of-accounts/options', [ChartOfAccountController::class, 'options'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('chart-of-accounts', [ChartOfAccountController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('chart-of-accounts', [ChartOfAccountController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('chart-of-accounts/{chartOfAccount}', [ChartOfAccountController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('chart-of-accounts/{chartOfAccount}', [ChartOfAccountController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('chart-of-accounts/{chartOfAccount}', [ChartOfAccountController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('credit-cards/options', [CreditCardController::class, 'options'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('credit-cards', [CreditCardController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('credit-cards', [CreditCardController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('credit-cards/{creditCard}', [CreditCardController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('credit-cards/{creditCard}', [CreditCardController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('credit-cards/{creditCard}', [CreditCardController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('customers', [CustomerProfileController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('customers', [CustomerProfileController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('customers/{customer}', [CustomerProfileController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('customers/{customer}', [CustomerProfileController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('customers/{customer}', [CustomerProfileController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::get('employees', [EmployeeProfileController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('employees', [EmployeeProfileController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('employees/{employee}', [EmployeeProfileController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('employees/{employee}', [EmployeeProfileController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('employees/{employee}', [EmployeeProfileController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('payment-methods', [PaymentMethodController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('payment-methods', [PaymentMethodController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('payment-methods/{id}/edit', [PaymentMethodController::class, 'edit'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('payment-methods/{paymentMethod}', [PaymentMethodController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('payment-methods/{paymentMethod}', [PaymentMethodController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('payment-methods/{paymentMethod}', [PaymentMethodController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('sales-taxes', [SalesTaxController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('sales-taxes', [SalesTaxController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('sales-taxes/{id}/edit', [SalesTaxController::class, 'edit'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('sales-taxes/{salesTax}', [SalesTaxController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('sales-taxes/{salesTax}', [SalesTaxController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('sales-taxes/{salesTax}', [SalesTaxController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('invoice-terms', [InvoiceTermController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('invoice-terms', [InvoiceTermController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('invoice-terms/{id}/edit', [InvoiceTermController::class, 'edit'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('invoice-terms/{invoiceTerm}', [InvoiceTermController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('invoice-terms/{invoiceTerm}', [InvoiceTermController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('invoice-terms/{invoiceTerm}', [InvoiceTermController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);

        Route::get('inventory-items', [ItemController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('inventory-items', [ItemController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('inventory-items/{id}/edit', [ItemController::class, 'edit'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('inventory-items/{item}', [ItemController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('inventory-items/{item}', [ItemController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('inventory-items/{item}', [ItemController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::post('inventory-items/{id}/toggle-status', [ItemController::class, 'toggleStatus'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);

        Route::get('service-items', [ServiceItemController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('service-items', [ServiceItemController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('service-items/{id}/edit', [ServiceItemController::class, 'edit'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('service-items/{item}', [ServiceItemController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('service-items/{item}', [ServiceItemController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('service-items/{item}', [ServiceItemController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::post('service-items/{id}/toggle-status', [ServiceItemController::class, 'toggleStatus'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);

        Route::get('job-sites', [JobSiteController::class, 'index'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::post('job-sites', [JobSiteController::class, 'store'])->middleware(['plan.feature:profiles_core', 'permission:profiles,create']);
        Route::get('job-sites/{id}/edit', [JobSiteController::class, 'edit'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::get('job-sites/{item}', [JobSiteController::class, 'show'])->middleware(['plan.feature:profiles_core', 'permission:profiles,read']);
        Route::put('job-sites/{item}', [JobSiteController::class, 'update'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);
        Route::delete('job-sites/{item}', [JobSiteController::class, 'destroy'])->middleware(['plan.feature:profiles_core', 'permission:profiles,delete']);
        Route::post('job-sites/{id}/toggle-status', [JobSiteController::class, 'toggleStatus'])->middleware(['plan.feature:profiles_core', 'permission:profiles,edit']);

        Route::get('vehicles', [VehicleController::class, 'index']);
        Route::post('vehicles', [VehicleController::class, 'store']);
        Route::get('vehicles/{id}/edit', [VehicleController::class, 'edit']);
        Route::get('vehicles/{id}', [VehicleController::class, 'show']);
        Route::put('vehicles/{id}', [VehicleController::class, 'update']);
        Route::delete('vehicles/{id}', [VehicleController::class, 'destroy']);

        Route::get('drivers', [DriverController::class, 'index']);
        Route::post('drivers', [DriverController::class, 'store']);
        Route::get('drivers/{id}/edit', [DriverController::class, 'edit']);
        Route::get('drivers/{id}', [DriverController::class, 'show']);
        Route::put('drivers/{id}', [DriverController::class, 'update']);
        Route::delete('drivers/{id}', [DriverController::class, 'destroy']);

        Route::get('insurance-policies', [InsurancePolicyController::class, 'index']);
        Route::post('insurance-policies', [InsurancePolicyController::class, 'store']);
        Route::get('insurance-policies/{id}/edit', [InsurancePolicyController::class, 'edit']);
        Route::get('insurance-policies/{id}', [InsurancePolicyController::class, 'show']);
        Route::put('insurance-policies/{id}', [InsurancePolicyController::class, 'update']);
        Route::delete('insurance-policies/{id}', [InsurancePolicyController::class, 'destroy']);
        Route::get('fuel-records', [FuelRecordController::class, 'index']);
        Route::post('fuel-records', [FuelRecordController::class, 'store']);
        Route::put('fuel-records/{fuelRecord}', [FuelRecordController::class, 'update']);
        Route::delete('fuel-records/{fuelRecord}', [FuelRecordController::class, 'destroy']);
        Route::apiResource('repair-maintenance-records', RepairMaintenanceRecordController::class)->only(['index','show','store','update','destroy']);
        Route::apiResource('purchase-orders', PurchaseOrderController::class)->parameters(['purchase-orders' => 'purchaseOrder'])->only(['index','show','store','update','destroy']);
        Route::post('purchase-orders/{purchaseOrder}/workflow', [PurchaseOrderController::class, 'workflow']);
        Route::post('purchase-orders/{purchaseOrder}/documents', [PurchaseOrderController::class, 'addDocument']);
        Route::post('purchase-orders/{purchaseOrder}/attachments', [PurchaseOrderController::class, 'attach']);
        Route::get('purchase-orders/{purchaseOrder}/attachments/{attachment}', [PurchaseOrderController::class, 'download']);
        Route::apiResource('purchase-invoices', PurchaseInvoiceController::class)->parameters(['purchase-invoices' => 'purchaseInvoice'])->only(['index','show','store','update','destroy']);
        Route::post('purchase-invoices/{purchaseInvoice}/workflow', [PurchaseInvoiceController::class, 'workflow']);
        Route::post('purchase-invoices/{purchaseInvoice}/payments', [PurchaseInvoiceController::class, 'pay']);
        Route::post('purchase-invoices/{purchaseInvoice}/attachments', [PurchaseInvoiceController::class, 'attach']);
        Route::get('purchase-invoices/{purchaseInvoice}/attachments/{attachment}', [PurchaseInvoiceController::class, 'download']);
        Route::apiResource('purchase-returns', PurchaseReturnController::class)->parameters(['purchase-returns' => 'purchaseReturn'])->only(['index','show','store','update','destroy']);
        Route::post('purchase-returns/{purchaseReturn}/workflow', [PurchaseReturnController::class, 'workflow']);
        Route::post('purchase-returns/{purchaseReturn}/refunds', [PurchaseReturnController::class, 'refund']);
        Route::post('purchase-returns/{purchaseReturn}/attachments', [PurchaseReturnController::class, 'attach']);
        Route::get('purchase-returns/{purchaseReturn}/attachments/{attachment}', [PurchaseReturnController::class, 'download']);
        Route::apiResource('seller-debit-notes', SellerDebitNoteController::class)->parameters(['seller-debit-notes' => 'sellerDebitNote'])->only(['index','show','store','update','destroy']);
        Route::post('seller-debit-notes/{sellerDebitNote}/workflow', [SellerDebitNoteController::class, 'workflow']);
        Route::post('seller-debit-notes/{sellerDebitNote}/settlements', [SellerDebitNoteController::class, 'settle']);
        Route::post('seller-debit-notes/{sellerDebitNote}/attachments', [SellerDebitNoteController::class, 'attach']);
        Route::get('seller-debit-notes/{sellerDebitNote}/attachments/{attachment}', [SellerDebitNoteController::class, 'download']);
        Route::apiResource('seller-credit-notes', SellerCreditNoteController::class)->parameters(['seller-credit-notes' => 'sellerCreditNote'])->only(['index','show','store','update','destroy']);
        Route::post('seller-credit-notes/{sellerCreditNote}/workflow', [SellerCreditNoteController::class, 'workflow']);
        Route::post('seller-credit-notes/{sellerCreditNote}/attachments', [SellerCreditNoteController::class, 'attach']);
        Route::get('seller-credit-notes/{sellerCreditNote}/attachments/{attachment}', [SellerCreditNoteController::class, 'download']);
        Route::apiResource('bill-payments', BillPaymentController::class)->parameters(['bill-payments' => 'billPayment'])->only(['index','show','store','update','destroy']);
        Route::post('bill-payments/{billPayment}/post', [BillPaymentController::class, 'post']);
        Route::post('bill-payments/{billPayment}/attachments', [BillPaymentController::class, 'attach']);
        Route::get('bill-payments/{billPayment}/attachments/{attachment}', [BillPaymentController::class, 'download']);
        Route::get('sales-orders/options', [SalesOrderController::class, 'options']);
        Route::get('sales-invoices/options', [SalesInvoiceController::class, 'options']);
        Route::apiResource('sales-invoices', SalesInvoiceController::class)->parameters(['sales-invoices' => 'salesInvoice'])->only(['index','show','store','update','destroy']);
        Route::post('sales-invoices/{salesInvoice}/workflow', [SalesInvoiceController::class, 'workflow']);
        Route::post('sales-invoices/{salesInvoice}/payments', [SalesInvoiceController::class, 'pay']);
        Route::apiResource('sales-returns', SalesReturnController::class)->parameters(['sales-returns' => 'salesReturn'])->only(['index','show','store','update','destroy']);
        Route::post('sales-returns/{salesReturn}/workflow', [SalesReturnController::class, 'workflow']);
        Route::post('sales-returns/{salesReturn}/refunds', [SalesReturnController::class, 'refund']);
        Route::post('sales-returns/{salesReturn}/attachments', [SalesReturnController::class, 'attach']);
        Route::get('sales-returns/{salesReturn}/attachments/{attachment}', [SalesReturnController::class, 'download']);
        Route::apiResource('customer-credit-notes', CustomerCreditNoteController::class)->parameters(['customer-credit-notes' => 'customerCreditNote'])->only(['index','show','store','update','destroy']);
        Route::post('customer-credit-notes/{customerCreditNote}/workflow', [CustomerCreditNoteController::class, 'workflow']);
        Route::post('customer-credit-notes/{customerCreditNote}/attachments', [CustomerCreditNoteController::class, 'attach']);
        Route::get('customer-credit-notes/{customerCreditNote}/attachments/{attachment}', [CustomerCreditNoteController::class, 'download']);
        Route::apiResource('sales-orders', SalesOrderController::class)->parameters(['sales-orders' => 'salesOrder'])->only(['index','show','store','update','destroy']);
        Route::post('sales-orders/{salesOrder}/workflow', [SalesOrderController::class, 'workflow']);
        Route::post('sales-orders/{salesOrder}/attachments', [SalesOrderController::class, 'attach']);
        Route::get('sales-orders/{salesOrder}/attachments/{attachment}', [SalesOrderController::class, 'download']);

        Route::get('accident-reports', [AccidentReportController::class, 'index']);
        Route::post('accident-reports', [AccidentReportController::class, 'store']);
        Route::get('accident-reports/{id}/edit', [AccidentReportController::class, 'edit']);
        Route::get('accident-reports/{id}', [AccidentReportController::class, 'show']);
        Route::put('accident-reports/{id}', [AccidentReportController::class, 'update']);
        Route::delete('accident-reports/{id}', [AccidentReportController::class, 'destroy']);

        Route::get('violation-tickets', [ViolationTicketController::class, 'index']);
        Route::post('violation-tickets', [ViolationTicketController::class, 'store']);
        Route::get('violation-tickets/{id}/edit', [ViolationTicketController::class, 'edit']);
        Route::get('violation-tickets/{id}', [ViolationTicketController::class, 'show']);
        Route::put('violation-tickets/{id}', [ViolationTicketController::class, 'update']);
        Route::delete('violation-tickets/{id}', [ViolationTicketController::class, 'destroy']);

        Route::get('daily-logs', [DailyLogController::class, 'index']);
        Route::post('daily-logs', [DailyLogController::class, 'store']);
        Route::get('daily-logs/{id}/edit', [DailyLogController::class, 'edit']);
        Route::get('daily-logs/{id}', [DailyLogController::class, 'show']);
        Route::put('daily-logs/{id}', [DailyLogController::class, 'update']);
        Route::delete('daily-logs/{id}', [DailyLogController::class, 'destroy']);

        Route::get('estimations', [EstimationController::class, 'index'])->middleware('permission:estimations,read');
        Route::post('estimations', [EstimationController::class, 'store'])->middleware('permission:estimations,create');
        Route::get('estimations/options', [EstimationController::class, 'getOptions']);
        Route::get('estimations/customers', [EstimationController::class, 'customers']);
        Route::get('estimations/job-sites', [EstimationController::class, 'jobSites']);
        Route::get('estimations/{estimation}', [EstimationController::class, 'show'])->middleware('permission:estimations,read');
        Route::put('estimations/{estimation}', [EstimationController::class, 'update'])->middleware('permission:estimations,edit');
        Route::delete('estimations/{estimation}', [EstimationController::class, 'destroy'])->middleware('permission:estimations,delete');

        Route::get('quotations', [QuotationController::class, 'index'])->middleware('permission:quotations,read');
        Route::post('quotations', [QuotationController::class, 'store'])->middleware('permission:quotations,create');
        Route::get('quotations/options', [QuotationController::class, 'getOptions']);
        Route::get('quotations/customers', [QuotationController::class, 'customers']);
        Route::get('quotations/job-sites', [QuotationController::class, 'jobSites']);
        Route::get('quotations/estimations', [QuotationController::class, 'estimations']);
        Route::get('quotations/{quotation}', [QuotationController::class, 'show'])->middleware('permission:quotations,read');
        Route::put('quotations/{quotation}', [QuotationController::class, 'update'])->middleware('permission:quotations,edit');
        Route::delete('quotations/{quotation}', [QuotationController::class, 'destroy'])->middleware('permission:quotations,delete');

        Route::get('job-orders', [JobOrderController::class, 'index'])->middleware('permission:job_orders,read');
        Route::post('job-orders', [JobOrderController::class, 'store'])->middleware('permission:job_orders,create');
        Route::get('job-orders/options', [JobOrderController::class, 'getOptions'])->middleware('permission:job_orders,read');
        Route::get('job-orders/customers', [JobOrderController::class, 'customers'])->middleware('permission:job_orders,read');
        Route::get('job-orders/job-sites', [JobOrderController::class, 'jobSites'])->middleware('permission:job_orders,read');
        Route::get('job-orders/quotations', [JobOrderController::class, 'quotations'])->middleware('permission:job_orders,read');
        Route::get('job-orders/estimations', [JobOrderController::class, 'estimations'])->middleware('permission:job_orders,read');
        Route::get('job-orders/{jobOrder}', [JobOrderController::class, 'show'])->middleware('permission:job_orders,read');
        Route::put('job-orders/{jobOrder}', [JobOrderController::class, 'update'])->middleware('permission:job_orders,edit');
        Route::delete('job-orders/{jobOrder}', [JobOrderController::class, 'destroy'])->middleware('permission:job_orders,delete');

        Route::get('job-order-daily-work-logs', [JobOrderDailyWorkLogController::class, 'index'])->middleware('permission:job_orders,read');
        Route::post('job-order-daily-work-logs', [JobOrderDailyWorkLogController::class, 'store'])->middleware('permission:job_orders,create');
        Route::get('job-order-daily-work-logs/job-orders', [JobOrderDailyWorkLogController::class, 'jobOrders'])->middleware('permission:job_orders,read');
        Route::get('job-order-daily-work-logs/{dailyWorkLog}', [JobOrderDailyWorkLogController::class, 'show'])->middleware('permission:job_orders,read');
        Route::put('job-order-daily-work-logs/{dailyWorkLog}', [JobOrderDailyWorkLogController::class, 'update'])->middleware('permission:job_orders,edit');
        Route::delete('job-order-daily-work-logs/{dailyWorkLog}', [JobOrderDailyWorkLogController::class, 'destroy'])->middleware('permission:job_orders,delete');

        Route::get('settings/date-time', [DateTimeSettingsController::class, 'show'])->middleware('permission:settings,read');
        Route::put('settings/date-time', [DateTimeSettingsController::class, 'update'])->middleware('permission:settings,edit');
        Route::get('settings/theme', [ThemeSettingsController::class, 'show'])->middleware('permission:settings,read');
        Route::put('settings/theme', [ThemeSettingsController::class, 'update'])->middleware('permission:settings,edit');
        Route::get('settings/language', [LanguageSettingsController::class, 'show'])->middleware('permission:settings,read');
        Route::put('settings/language', [LanguageSettingsController::class, 'update'])->middleware('permission:settings,edit');
        Route::get('settings/holding-limits', [ParcelHoldingLimitsController::class, 'show'])->middleware('permission:settings,read');
        Route::put('settings/holding-limits', [ParcelHoldingLimitsController::class, 'update'])->middleware('permission:settings,edit');
        Route::get('settings/notifications', [NotificationSettingsController::class, 'show'])->middleware(['plan.feature:notification_center', 'permission:settings,read']);
        Route::put('settings/notifications', [NotificationSettingsController::class, 'update'])->middleware(['plan.feature:notification_center', 'permission:settings,edit']);

        Route::get('calendar-events', [CalendarEventController::class, 'index'])->middleware('permission:calendar,read');
        Route::post('calendar-events', [CalendarEventController::class, 'store'])->middleware('permission:calendar,create');
        Route::get('calendar-events/{event}', [CalendarEventController::class, 'show'])->middleware('permission:calendar,read');
        Route::put('calendar-events/{event}', [CalendarEventController::class, 'update'])->middleware('permission:calendar,edit');
        Route::delete('calendar-events/{event}', [CalendarEventController::class, 'destroy'])->middleware('permission:calendar,delete');
        Route::get('calendar-events/export', [CalendarEventController::class, 'export'])->middleware('permission:calendar,read');
        Route::post('calendar-events/import', [CalendarEventController::class, 'import'])->middleware('permission:calendar,create');

        Route::get('announcements', [AnnouncementController::class, 'index'])->middleware('permission:announcements,read');
        Route::get('announcements/meta', [AnnouncementController::class, 'meta'])->middleware('permission:announcements,read');
        Route::post('announcements', [AnnouncementController::class, 'store'])->middleware('permission:announcements,create');
        Route::get('announcements/{announcement}', [AnnouncementController::class, 'show'])->middleware('permission:announcements,read');
        Route::put('announcements/{announcement}', [AnnouncementController::class, 'update'])->middleware('permission:announcements,edit');
        Route::delete('announcements/{announcement}', [AnnouncementController::class, 'destroy'])->middleware('permission:announcements,delete');
        Route::post('announcements/{announcement}/read', [AnnouncementController::class, 'markRead'])->middleware('permission:announcements,read');
        Route::post('announcements/{announcement}/publish', [AnnouncementController::class, 'publish'])->middleware('permission:announcements,publish');
        Route::post('announcements/{announcement}/archive', [AnnouncementController::class, 'archive'])->middleware('permission:announcements,publish');
        Route::post('announcements/{announcement}/submit', [AnnouncementController::class, 'submit'])->middleware('permission:announcements,edit');
        Route::post('announcements/{announcement}/approve', [AnnouncementController::class, 'approve'])->middleware('permission:announcements,approve');
        Route::post('announcements/{announcement}/reject', [AnnouncementController::class, 'reject'])->middleware('permission:announcements,approve');
        Route::get('announcements/{announcement}/attachments', [AnnouncementController::class, 'attachments'])->middleware('permission:announcements,read');
        Route::post('announcements/{announcement}/attachments', [AnnouncementController::class, 'uploadAttachment'])->middleware('permission:announcements,edit');
        Route::get('announcements/{announcement}/attachments/{attachment}', [AnnouncementController::class, 'downloadAttachment'])->middleware('permission:announcements,read');
        Route::delete('announcements/{announcement}/attachments/{attachment}', [AnnouncementController::class, 'deleteAttachment'])->middleware('permission:announcements,delete');

        Route::get('email/messages', [EmailMessageController::class, 'index'])->middleware('permission:email,read');
        Route::post('email/messages', [EmailMessageController::class, 'store'])->middleware('permission:email,create');
        Route::get('email/messages/{message}', [EmailMessageController::class, 'show'])->middleware('permission:email,read');
        Route::put('email/messages/{message}', [EmailMessageController::class, 'update'])->middleware('permission:email,edit');
        Route::post('email/messages/{message}/send', [EmailMessageController::class, 'send'])->middleware('permission:email,send');
        Route::post('email/messages/{message}/trash', [EmailMessageController::class, 'trash'])->middleware('permission:email,edit');
        Route::post('email/messages/{message}/restore', [EmailMessageController::class, 'restore'])->middleware('permission:email,edit');
        Route::delete('email/messages/{message}', [EmailMessageController::class, 'destroy'])->middleware('permission:email,delete');
        Route::post('email/messages/{message}/attachments', [EmailMessageController::class, 'uploadAttachment'])->middleware('permission:email,edit');
        Route::delete('email/messages/{message}/attachments/{attachment}', [EmailMessageController::class, 'deleteAttachment'])->middleware('permission:email,delete');
        Route::get('email/messages/{message}/attachments/{attachment}', [EmailMessageController::class, 'downloadAttachment'])->middleware('permission:email,read');
        Route::post('email/messages/sync', [EmailMessageController::class, 'sync'])->middleware('permission:email,read');
        Route::get('email/threads/{threadId}', [EmailMessageController::class, 'thread'])->middleware('permission:email,read');
        Route::post('email/threads/{threadId}/mark', [EmailMessageController::class, 'markThread'])->middleware('permission:email,edit');

        Route::get('email/templates', [EmailTemplateController::class, 'index'])->middleware('permission:email,read');
        Route::post('email/templates', [EmailTemplateController::class, 'store'])->middleware('permission:email,create');
        Route::get('email/templates/{template}', [EmailTemplateController::class, 'show'])->middleware('permission:email,read');
        Route::put('email/templates/{template}', [EmailTemplateController::class, 'update'])->middleware('permission:email,edit');
        Route::delete('email/templates/{template}', [EmailTemplateController::class, 'destroy'])->middleware('permission:email,delete');

        Route::get('email/settings', [EmailSettingsController::class, 'show'])->middleware('permission:email,read');
        Route::put('email/settings', [EmailSettingsController::class, 'update'])->middleware('permission:email,edit');
        Route::get('email/stats', [EmailStatsController::class, 'show'])->middleware('permission:email,read');

        Route::get('workforce/daily-reports', [WorkforceDailyReportController::class, 'index'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::post('workforce/daily-reports', [WorkforceDailyReportController::class, 'store'])->middleware(['plan.feature:workforce_management', 'permission:workforce,create']);
        Route::get('workforce/daily-reports/{report}', [WorkforceDailyReportController::class, 'show'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::put('workforce/daily-reports/{report}', [WorkforceDailyReportController::class, 'update'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::delete('workforce/daily-reports/{report}', [WorkforceDailyReportController::class, 'destroy'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::post('workforce/daily-reports/{report}/submit', [WorkforceDailyReportController::class, 'submit'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::post('workforce/daily-reports/{report}/approve', [WorkforceDailyReportController::class, 'approve'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);
        Route::post('workforce/daily-reports/{report}/finalize', [WorkforceDailyReportController::class, 'finalize'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);
        Route::post('workforce/daily-reports/{report}/reject', [WorkforceDailyReportController::class, 'reject'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);

        Route::get('workforce/incident-reports', [WorkforceIncidentReportController::class, 'index'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::post('workforce/incident-reports', [WorkforceIncidentReportController::class, 'store'])->middleware(['plan.feature:workforce_management', 'permission:workforce,create']);
        Route::get('workforce/incident-reports/{incident}', [WorkforceIncidentReportController::class, 'show'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::put('workforce/incident-reports/{incident}', [WorkforceIncidentReportController::class, 'update'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::delete('workforce/incident-reports/{incident}', [WorkforceIncidentReportController::class, 'destroy'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::post('workforce/incident-reports/{incident}/submit', [WorkforceIncidentReportController::class, 'submit'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::post('workforce/incident-reports/{incident}/approve', [WorkforceIncidentReportController::class, 'approve'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);
        Route::post('workforce/incident-reports/{incident}/finalize', [WorkforceIncidentReportController::class, 'finalize'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);
        Route::post('workforce/incident-reports/{incident}/reject', [WorkforceIncidentReportController::class, 'reject'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);

        Route::get('workforce/staff-attendances', [WorkforceStaffAttendanceController::class, 'index'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::post('workforce/staff-attendances', [WorkforceStaffAttendanceController::class, 'store'])->middleware(['plan.feature:workforce_management', 'permission:workforce,create']);
        Route::get('workforce/staff-attendances/{attendance}', [WorkforceStaffAttendanceController::class, 'show'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::put('workforce/staff-attendances/{attendance}', [WorkforceStaffAttendanceController::class, 'update'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::delete('workforce/staff-attendances/{attendance}', [WorkforceStaffAttendanceController::class, 'destroy'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);

        Route::apiResource('workforce/staff-requests', WorkforceStaffRequestController::class)->parameters(['staff-requests' => 'record'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::apiResource('workforce/task-assignments', WorkforceTaskAssignmentController::class)->parameters(['task-assignments' => 'record'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::apiResource('workforce/work-schedules', WorkforceWorkScheduleController::class)->parameters(['work-schedules' => 'record'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);

        Route::get('workforce/timesheets', [WorkforceTimesheetController::class, 'index'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::post('workforce/timesheets', [WorkforceTimesheetController::class, 'store'])->middleware(['plan.feature:workforce_management', 'permission:workforce,create']);
        Route::get('workforce/timesheets/{timesheet}', [WorkforceTimesheetController::class, 'show'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::put('workforce/timesheets/{timesheet}', [WorkforceTimesheetController::class, 'update'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::delete('workforce/timesheets/{timesheet}', [WorkforceTimesheetController::class, 'destroy'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::post('workforce/timesheets/{timesheet}/submit', [WorkforceTimesheetController::class, 'submit'])->middleware(['plan.feature:workforce_management', 'permission:workforce,edit']);
        Route::post('workforce/timesheets/{timesheet}/approve', [WorkforceTimesheetController::class, 'approve'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);
        Route::post('workforce/timesheets/{timesheet}/finalize', [WorkforceTimesheetController::class, 'finalize'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);
        Route::post('workforce/timesheets/{timesheet}/reject', [WorkforceTimesheetController::class, 'reject'])->middleware(['plan.feature:workforce_management', 'permission:workforce,approve']);

        Route::get('workforce/approvals', [WorkforceApprovalController::class, 'index'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::get('workforce/approvals/sla', [WorkforceApprovalController::class, 'slaDashboard'])->middleware(['plan.feature:workforce_management', 'permission:workforce,read']);
        Route::get('workforce/approvals/sla/export', [WorkforceApprovalController::class, 'exportSla'])->middleware(['plan.feature:workforce_management', 'permission:workforce,export']);
        Route::get('workforce/approvals/export', [WorkforceApprovalController::class, 'export'])->middleware(['plan.feature:workforce_management', 'permission:workforce,export']);
        Route::get('settings/approvals', [WorkforceApprovalSettingsController::class, 'show'])->middleware(['plan.feature:workforce_management', 'permission:settings,read']);
        Route::put('settings/approvals', [WorkforceApprovalSettingsController::class, 'update'])->middleware(['plan.feature:workforce_management', 'permission:settings,edit']);

        Route::get('pickup-rules', [PickupRuleController::class, 'index'])->middleware(['plan.feature:pickup_management', 'permission:pickup,read']);
        Route::post('pickup-rules', [PickupRuleController::class, 'store'])->middleware(['plan.feature:pickup_management', 'permission:pickup,create']);
        Route::get('pickup-rules/{pickupRule}/audits', [PickupRuleController::class, 'audits'])->middleware(['plan.feature:pickup_management', 'permission:pickup,read']);
        Route::put('pickup-rules/{pickupRule}', [PickupRuleController::class, 'update'])->middleware(['plan.feature:pickup_management', 'permission:pickup,edit']);
        Route::delete('pickup-rules/{pickupRule}', [PickupRuleController::class, 'destroy'])->middleware(['plan.feature:pickup_management', 'permission:pickup,delete']);
        Route::get('pickup-rules/sla/summary', [PickupRuleController::class, 'slaSummary'])->middleware(['plan.feature:reporting', 'permission:pickup,read']);
        Route::get('pickup-rules/sla/export', [PickupRuleController::class, 'exportSla'])->middleware(['plan.feature:reporting', 'permission:pickup,export']);
    });
});
