<template>
  <AccountLayout bare><main class="statement">
    <header><h1>Account Statement</h1><b>Statement Date: {{ pretty(toDate) }}</b></header>
    <h2>Statement Filter</h2><form class="card filter" @submit.prevent="generate"><label>From Date<span class="date-field"><input :value="pretty(fromDate)" readonly @click="openPicker('from')" /><button type="button" aria-label="Choose from date" @click="openPicker('from')">▣</button><input ref="fromPicker" class="native-picker" v-model="fromDate" type="date" @change="syncDate" /></span></label><label>To Date<span class="date-field"><input :value="pretty(toDate)" readonly @click="openPicker('to')" /><button type="button" aria-label="Choose to date" @click="openPicker('to')">▣</button><input ref="toPicker" class="native-picker" v-model="toDate" type="date" @change="syncDate" /></span></label><button>Generate Statement</button></form>
    <div class="card details"><Info label="Company Name" :value="setup.company_name || 'Not available'"/><Info label="Account Number" :value="accountNumber"/><Info label="Statement Period" :value="`${pretty(fromDate)} – ${pretty(toDate)}`"/><Info label="Currency" :value="setup.currency || 'CAD'"/><Info label="Tax Type" value="GST 5%"/><small>All amounts will include applicable GST when payment processing is enabled.</small></div>
    <h2>Statement Details</h2><div class="card table-wrap"><table><thead><tr><th>No.</th><th>Date</th><th>Transaction No.</th><th>Transaction Type</th><th>Details</th><th>Charge Amount</th><th>Paid Amount</th><th>Credit</th><th>Balance</th></tr></thead><tbody><tr><td colspan="9" class="empty">No account transactions are available yet. Stripe payment records will appear here after integration.</td></tr></tbody></table></div>
    <div class="card totals"><Info label="Opening Balance" :value="money(0)"/><Info label="Total Charges" :value="money(0)"/><Info label="Total Paid" :value="money(0)"/><Info label="Total Credits" :value="money(0)"/><Info label="Closing Balance" :value="money(0)"/></div>
    <div class="actions"><button class="outline" @click="download">⇩ Download Statement</button><button class="outline" @click="print">▣ Print</button><button @click="message='Email delivery will be available after payment-system integration.'">✉ Email Statement</button></div><p v-if="message">{{ message }}</p>
  </main></AccountLayout>
</template>
<script setup>
import { computed, defineComponent, h, onMounted, ref } from 'vue'
import AccountLayout from '../components/AccountLayout.vue'; import client from '../api/client'
const today=new Date(),toDate=ref(today.toISOString().slice(0,10)),fromDate=ref(new Date(today.getFullYear(),today.getMonth(),1).toISOString().slice(0,10)),setup=ref({}),message=ref(''),fromPicker=ref(null),toPicker=ref(null)
const Info=defineComponent({props:{label:String,value:String},setup:p=>()=>h('div',{class:'info'},[h('span',p.label),h('strong',p.value)])})
const accountNumber=computed(()=>setup.value.id?`AC-${String(setup.value.id).padStart(6,'0')}`:'Not available')
const pretty=v=>v?new Intl.DateTimeFormat('en-CA',{month:'long',day:'numeric',year:'numeric'}).format(new Date(`${v}T00:00:00`)):'Not scheduled'; const money=v=>Number(v||0).toLocaleString('en-CA',{style:'currency',currency:setup.value.currency||'CAD'})
const generate=()=>message.value='Statement generated. Transactions will appear once payments are connected.'; const print=()=>window.print(); const download=()=>{const url=URL.createObjectURL(new Blob([`Account Statement\nPeriod: ${fromDate.value} to ${toDate.value}\nNo transactions available.`],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='account-statement.txt';a.click();URL.revokeObjectURL(url)}
const syncDate=()=>{}; const openPicker=type=>{const picker=type==='from'?fromPicker.value:toPicker.value;if(picker?.showPicker) picker.showPicker();else picker?.focus()}
onMounted(async()=>{try{const {data}=await client.get('/account/billing');if(data?.success)setup.value={id:data.data.account_setup_id,company_name:data.data.company_name,currency:data.data.currency}}catch{}})
</script>
<style scoped>
.statement{max-width:1280px;margin:auto;padding:22px 44px 36px;color:#082477;font-family:"Arial Narrow",Arial,sans-serif}.statement header{display:flex;justify-content:space-between;align-items:center}.statement h1{font-size:3.4rem;margin:0 0 10px;font-weight:800;letter-spacing:-.05em}.statement header b{font-size:1.1rem}.statement h2{font-size:1.5rem;margin:8px 0}.card{border:1px solid #b9c1d2;border-radius:8px;background:rgba(255,255,255,.35)}.filter{display:grid;grid-template-columns:1fr 1fr auto;gap:38px;padding:14px 24px;align-items:end}.filter label{display:grid;gap:5px;font-weight:600}.filter input{padding:10px 14px;border:1px solid #aeb7ca;border-radius:6px;font-size:1rem;color:#082477}.date-field{position:relative;display:flex}.date-field>input{width:100%;padding-right:44px}.date-field>button{position:absolute;right:0;top:0;height:100%;padding:0 13px;border:0;background:transparent;color:#082477;font-size:1rem}.date-field .native-picker{position:absolute;opacity:0;pointer-events:none;width:1px;height:1px}.statement button{padding:12px 25px;border:1px solid #0869f7;border-radius:6px;background:#0869f7;color:#fff;font-size:1.05rem}.details,.totals{display:grid;grid-template-columns:repeat(5,1fr);gap:20px;padding:18px 28px;margin:15px 0}.details small{grid-column:1/-1;font-size:1rem;font-weight:600}.info{display:grid;gap:10px;text-align:center}.info span{font-weight:600}.info strong{font-size:1.35rem;white-space:nowrap}.table-wrap{overflow:auto}table{width:100%;min-width:1000px;border-collapse:collapse}th,td{padding:13px;border-bottom:1px solid #d1d5dd;text-align:center;white-space:nowrap}th{font-weight:700}.empty{color:#667085}.totals .info:not(:last-child){border-right:1px solid #b9c1d2}.totals .info strong{font-size:1.65rem}.actions{display:flex;gap:20px;margin-top:16px}.actions .outline{background:transparent;color:#0869f7}.statement p{font-weight:700;color:#087334}@media(max-width:900px){.details,.totals{grid-template-columns:repeat(3,1fr)}.filter{grid-template-columns:1fr 1fr}}@media(max-width:600px){.statement{padding:20px 18px}.statement header{display:block}.statement h1{font-size:2.3rem}.details,.totals,.filter{grid-template-columns:1fr}.actions{gap:8px}.actions button{padding:10px 8px;font-size:.86rem}.totals .info{border:0!important}}</style>
