<template>
  <AccountLayout bare><main class="customers-page">
    <header><div><h1>Customers</h1><p>Dashboard <b>›</b> Customers</p></div><div class="header-actions"><button class="btn btn-outline-primary">⚱ Filter</button><button class="btn btn-primary" disabled title="Customer form will be added in the next design update">＋ New Customer</button></div></header>
    <section class="customer-summary"><div><span>♙</span><small>Total Customers</small><strong>{{ summary.total_customers || 0 }}</strong></div><div><span>✓</span><small>Active Customers</small><strong class="green">{{ summary.active_customers || 0 }}</strong></div><div><span>!</span><small>Inactive Customers</small><strong class="red">{{ summary.inactive_customers || 0 }}</strong></div><div><span>$</span><small>Total Outstanding</small><strong>{{ money(summary.total_outstanding) }}</strong></div></section>
    <section class="customer-table card"><div class="table-controls"><input v-model="search" class="form-control" placeholder="Search customers…" /><select v-model="status" class="form-select"><option value="">All Status</option><option value="1">Active</option><option value="0">Inactive</option></select><select v-model="customerType" class="form-select"><option value="">All Customer Types</option><option>Residential</option><option>Commercial</option></select></div><div v-if="error" class="alert alert-danger m-3">{{ error }}</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th><input type="checkbox" disabled /></th><th>Customer Name</th><th>Customer ID</th><th>Phone</th><th>Email</th><th>Customer Type</th><th>Total Invoices</th><th>Total Outstanding</th><th>Current Balance</th><th>Status</th><th>View Profile</th><th>Actions</th></tr></thead><tbody><tr v-for="customer in customers" :key="customer.id"><td><input type="checkbox" /></td><td><span class="initial">{{ initials(customer.name) }}</span><b>{{ customer.name }}</b></td><td>{{ customer.customer_id }}</td><td>{{ customer.phone || '—' }}</td><td>{{ customer.email || '—' }}</td><td>{{ customer.customer_type }}</td><td>{{ customer.total_invoices }}</td><td class="outstanding">{{ money(customer.total_outstanding) }}</td><td>{{ money(customer.current_balance) }}</td><td><span class="status" :class="customer.status_active?'active':'inactive'">{{ customer.status_active?'Active':'Inactive' }}</span></td><td><button class="link-button" disabled title="Profile view will be added later">View Profile</button></td><td><button class="icon-button" disabled title="Actions will be added later">⋮</button></td></tr><tr v-if="!customers.length && !loading"><td colspan="12" class="text-center text-muted py-5">No customers found for this project.</td></tr></tbody></table></div><footer><span>Showing {{ customers.length }} customer{{ customers.length===1?'':'s' }}</span><span class="pagination">‹ <b>1</b> ›</span></footer></section>
    <section class="bottom-summary"><div><span>▤</span><small>Total Invoices</small><b>{{ invoiceTotal }}</b></div><div><span>▣</span><small>Total Outstanding</small><b class="red">{{ money(summary.total_outstanding) }}</b></div><div><span>▤</span><small>Average Balance</small><b>{{ money(averageBalance) }}</b></div><div><span>!</span><small>Inactive Customers</small><b>{{ summary.inactive_customers || 0 }}</b></div></section>
  </main></AccountLayout>
</template>
<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import client from '../api/client'
import AccountLayout from '../components/AccountLayout.vue'
const customers=ref([]),summary=ref({}),search=ref(''),status=ref(''),customerType=ref(''),error=ref(''),loading=ref(false)
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));const initials=name=>(name||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();const invoiceTotal=computed(()=>customers.value.reduce((n,c)=>n+Number(c.total_invoices||0),0));const averageBalance=computed(()=>customers.value.length?customers.value.reduce((n,c)=>n+Number(c.current_balance||0),0)/customers.value.length:0)
let debounce; const load=async()=>{loading.value=true;error.value='';try{const {data}=await client.get('/customers',{params:{search:search.value,status:status.value,customer_type:customerType.value}});customers.value=data.data;summary.value=data.summary}catch(e){error.value=e.response?.data?.message||'Unable to load customers.'}finally{loading.value=false}};watch([search,status,customerType],()=>{clearTimeout(debounce);debounce=setTimeout(load,250)});onMounted(load)
</script>
<style scoped>
.customers-page{background:#f8faff;min-height:100vh;padding:28px;color:#071b66}.customers-page header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.customers-page h1{font-weight:800;font-size:2rem;margin:0}.customers-page header p{margin:4px 0 0;font-weight:600}.customers-page header p b{margin:0 8px;color:#0a59e8}.header-actions{display:flex;gap:10px}.customer-summary{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #dfe7fa;border-radius:10px;background:#fff;margin-bottom:20px}.customer-summary>div{padding:18px 28px;display:grid;grid-template-columns:40px 1fr;border-right:1px solid #e5eafa}.customer-summary>div:last-child{border:0}.customer-summary span,.bottom-summary span{grid-row:span 2;width:30px;height:30px;display:grid;place-items:center;background:#e7efff;color:#0757eb;border-radius:50%;font-weight:bold}.customer-summary small,.bottom-summary small{font-size:.72rem;font-weight:700}.customer-summary strong{font-size:1.25rem}.green{color:#078543}.red,.outstanding{color:#ef2525!important}.customer-table{border:1px solid #dfe7fa;overflow:hidden}.table-controls{display:flex;gap:14px;padding:14px}.table-controls input{max-width:280px}.table-controls select{max-width:190px}thead{background:linear-gradient(90deg,#0757dd,#0748c9);color:white;font-size:.72rem}th{white-space:nowrap;padding:13px 10px!important}td{font-size:.78rem;color:#10286c;white-space:nowrap;padding:10px!important}td b{font-size:.78rem}.initial{display:inline-grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#3474a4;color:#fff;font-size:.62rem;margin-right:8px}.status{padding:4px 10px;border-radius:20px;font-size:.7rem}.status.active{background:#d9f6e5;color:#007839}.status.inactive{background:#eff1f5;color:#697386}.link-button,.icon-button{background:none;border:0;color:#0757e9;font-weight:700;font-size:.75rem}.icon-button{font-size:1.2rem}footer{display:flex;justify-content:space-between;padding:14px 20px;border-top:1px solid #e6ebf8;font-size:.78rem;font-weight:600}.pagination{display:flex;gap:12px;align-items:center}.pagination b{background:#0757e9;color:#fff;border-radius:5px;padding:4px 9px}.bottom-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;background:#fff;border:1px solid #dfe7fa;border-radius:10px;margin-top:18px;padding:18px}.bottom-summary div{display:grid;grid-template-columns:42px 1fr}.bottom-summary b{font-size:1.15rem}@media(max-width:1000px){.customer-summary,.bottom-summary{grid-template-columns:repeat(2,1fr)}.customer-summary>div:nth-child(2){border-right:0}}@media(max-width:620px){.customers-page{padding:16px}.customers-page header{align-items:flex-start;gap:10px;flex-direction:column}.table-controls{flex-direction:column}.table-controls input,.table-controls select{max-width:none}.customer-summary,.bottom-summary{grid-template-columns:1fr}.customer-summary>div{border-right:0;border-bottom:1px solid #e5eafa}}
</style>
