<template>
  <AccountLayout bare><main class="emp-page">
    <header class="emp-head"><div><h1>Employees</h1><p>Dashboard <ChevronRight :size="14"/> Employees</p></div><button class="emp-btn primary" @click="open()"><UserPlus :size="17"/> New Employee</button></header>
    <div v-if="error" class="emp-alert"><CircleAlert :size="18"/>{{error}}<button @click="error=''">x</button></div>
    <section class="emp-stats"><article v-for="card in cards" :key="card.label"><i :class="card.tone"><component :is="card.icon" :size="28"/></i><div><small>{{card.label}}</small><b>{{card.value}}</b><span>{{card.note}}</span></div></article></section>

    <section v-if="editing" class="emp-editor">
      <header><div><h2>{{form.id?'Edit Employee':'New Employee'}}</h2><p>Employee profile and employment information</p></div><button class="emp-btn secondary" type="button" @click="editing=false"><List :size="16"/> Employee List</button></header>
      <form @submit.prevent="save"><div class="emp-form-grid">
        <label>Full Name *<input v-model.trim="form.account_name" required placeholder="Enter full name"></label><label>Employee ID<input v-model.trim="form.employee_id" placeholder="Auto generated if blank"></label>
        <label>Department *<input v-model.trim="form.department" required placeholder="Enter department"></label><label>Position *<input v-model.trim="form.position" required placeholder="Enter position"></label>
        <label>Hire Date *<input v-model="form.hire_date" required type="date"></label><label>Account No.<input v-model.trim="form.account_no" placeholder="Enter account number"></label>
        <label>Phone<input v-model.trim="form.cell_phone" type="tel" placeholder="Enter phone number"></label><label>Email<input v-model.trim="form.email" type="email" placeholder="Enter email address"></label>
        <label>Screening Expires<input v-model="form.screening_expires_at" type="date"></label><label>Status<select v-model="form.status_active"><option :value="true">Active</option><option :value="false">Inactive</option></select></label>
      </div><footer><button class="emp-btn secondary" type="button" @click="editing=false"><X :size="16"/> Cancel</button><button class="emp-btn primary" :disabled="saving"><Save :size="16"/>{{saving?'Saving...':'Save Employee'}}</button></footer></form>
    </section>

    <section v-else class="emp-directory">
      <div class="emp-tools"><div class="emp-list-title"><Users :size="21"/><h2>Employees List ({{filtered.length}})</h2></div><div class="emp-tabs"><span>Status:</span><button v-for="tab in tabs" :key="tab.value" :class="{active:status===tab.value}" @click="status=tab.value">{{tab.label}}</button></div><label class="emp-search"><Search :size="17"/><input v-model="search" placeholder="Search employees..."></label><button class="tool-btn" @click="filtersOpen=!filtersOpen"><ListFilter :size="16"/> Filter</button><button class="tool-btn" @click="exportCsv"><Download :size="16"/> Export</button><button class="tool-btn icon" title="Refresh" @click="load"><RefreshCw :size="16"/></button></div>
      <div v-if="filtersOpen" class="emp-filters"><label>Department<select v-model="department"><option value="">All Departments</option><option v-for="item in departments" :key="item">{{item}}</option></select></label><label>Screening<select v-model="screening"><option value="">All Screening</option><option value="valid">Valid</option><option value="expired">Expired</option></select></label><button @click="department='';screening=''">Clear filters</button></div>
      <div class="emp-table-wrap"><table><thead><tr><th>#</th><th><button @click="sort('employee_no')">Employee No. <ArrowUpDown :size="12"/></button></th><th>Employee ID</th><th><button @click="sort('full_name')">Full Name <ArrowUpDown :size="12"/></button></th><th>Department</th><th>Position</th><th>Status</th><th><button @click="sort('hire_date')">Hire Date <ArrowUpDown :size="12"/></button></th><th>Account No.</th><th>Screening</th><th>Phone</th><th>Email</th><th class="right">Actions</th></tr></thead><tbody>
        <tr v-for="(e,i) in pageRows" :key="e.id"><td>{{start+i+1}}</td><td class="code">{{e.employee_no}}</td><td class="code">{{e.employee_id}}</td><td><b>{{e.full_name}}</b></td><td>{{e.department}}</td><td>{{e.position}}</td><td><em :class="e.status_active?'active':'inactive'">{{e.status_active?'Active':'Inactive'}}</em></td><td>{{date(e.hire_date)}}</td><td class="code">{{e.account_no||'-'}}</td><td><em :class="e.screening_expired?'expired':'active'">{{e.screening_expired?'Expired':'Valid'}}</em></td><td>{{e.phone||'-'}}</td><td>{{e.email||'-'}}</td><td class="right"><button class="view-btn" @click="profile=e"><Eye :size="13"/> View Profile</button><button class="row-btn" @click="open(e)"><Pencil :size="14"/></button><button class="row-btn delete" @click="remove(e)"><Trash2 :size="14"/></button></td></tr>
        <tr v-if="!pageRows.length"><td colspan="13" class="empty"><Users :size="30"/><b>No employees found</b></td></tr>
      </tbody></table></div>
      <footer class="emp-footer"><span>Showing {{filtered.length?start+1:0}} to {{Math.min(start+pageSize,filtered.length)}} of {{filtered.length}} entries</span><nav><button :disabled="page===1" @click="page--"><ChevronLeft :size="15"/> Previous</button><button class="current">{{page}}</button><button :disabled="page===pages" @click="page++">Next <ChevronRight :size="15"/></button></nav></footer>
      <div class="emp-legend"><span><i class="active"></i>Active</span><span><i class="inactive"></i>Inactive</span><span><i class="expired"></i>Expired Screening</span></div>
    </section>

    <div v-if="profile" class="emp-overlay" @click.self="profile=null"><section class="emp-modal"><button class="close" @click="profile=null"><X :size="17"/></button><div class="avatar"><UserRound :size="28"/></div><h2>{{profile.full_name}}</h2><p>{{profile.position}} · {{profile.department}}</p><dl><div><dt>Employee No.</dt><dd>{{profile.employee_no}}</dd></div><div><dt>Employee ID</dt><dd>{{profile.employee_id}}</dd></div><div><dt>Hire Date</dt><dd>{{date(profile.hire_date)}}</dd></div><div><dt>Account No.</dt><dd>{{profile.account_no||'-'}}</dd></div><div><dt>Phone</dt><dd>{{profile.phone||'-'}}</dd></div><div><dt>Email</dt><dd>{{profile.email||'-'}}</dd></div></dl><button class="emp-btn primary" @click="open(profile);profile=null"><Pencil :size="15"/> Edit Employee</button></section></div>
  </main></AccountLayout>
</template>
<script setup>
import{computed,onMounted,ref,watch}from'vue';import{ArrowUpDown,BadgeAlert,ChevronLeft,ChevronRight,CircleAlert,Download,Eye,List,ListFilter,Pencil,RefreshCw,Save,Search,Trash2,UserCheck,UserMinus,UserPlus,UserRound,Users,X}from'lucide-vue-next';import client from'../api/client';import AccountLayout from'../components/AccountLayout.vue';import'./Employees.css';import'./ProfileTableLayout.css';
const rows=ref([]),editing=ref(false),profile=ref(null),saving=ref(false),error=ref(''),search=ref(''),status=ref(''),department=ref(''),screening=ref(''),filtersOpen=ref(false),page=ref(1),sortKey=ref('employee_no'),sortAsc=ref(true),pageSize=20;
const blank=()=>({account_name:'',employee_id:'',department:'',position:'',hire_date:'',account_no:'',cell_phone:'',email:'',screening_expires_at:'',status_active:true}),form=ref(blank()),tabs=[{label:'All',value:''},{label:'Active',value:'active'},{label:'Inactive',value:'inactive'}];
const active=computed(()=>rows.value.filter(e=>e.status_active).length),expired=computed(()=>rows.value.filter(e=>e.screening_expired).length),pct=n=>rows.value.length?Math.round(n/rows.value.length*100):0;
const cards=computed(()=>[{label:'Total Employees',value:rows.value.length,note:'View all employees',icon:Users,tone:'blue'},{label:'Total Active',value:active.value,note:`${pct(active.value)}% of total`,icon:UserCheck,tone:'green'},{label:'Total Inactive',value:rows.value.length-active.value,note:`${pct(rows.value.length-active.value)}% of total`,icon:UserMinus,tone:'orange'},{label:'Total Expired Screening',value:expired.value,note:`${pct(expired.value)}% of total`,icon:BadgeAlert,tone:'red'}]);
const departments=computed(()=>[...new Set(rows.value.map(e=>e.department).filter(Boolean))].sort()),filtered=computed(()=>rows.value.filter(e=>{const q=search.value.toLowerCase();return(!q||`${e.employee_no} ${e.employee_id} ${e.full_name} ${e.department} ${e.position} ${e.email}`.toLowerCase().includes(q))&&(!status.value||(status.value==='active'?e.status_active:!e.status_active))&&(!department.value||e.department===department.value)&&(!screening.value||(screening.value==='expired'?e.screening_expired:!e.screening_expired))}).sort((a,b)=>String(a[sortKey.value]??'').localeCompare(String(b[sortKey.value]??''),undefined,{numeric:true})*(sortAsc.value?1:-1)));
const pages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/pageSize))),start=computed(()=>(page.value-1)*pageSize),pageRows=computed(()=>filtered.value.slice(start.value,start.value+pageSize));watch([search,status,department,screening],()=>page.value=1);
const date=v=>{if(!v)return'-';const[y,m,d]=v.slice(0,10).split('-');return`${m}/${d}/${y}`};function sort(k){if(sortKey.value===k)sortAsc.value=!sortAsc.value;else{sortKey.value=k;sortAsc.value=true}}async function load(){error.value='';try{rows.value=(await client.get('/employees')).data.data}catch{error.value='Unable to load employees.'}}function open(e=null){form.value=e?{...e,account_name:e.full_name,cell_phone:e.phone}:blank();editing.value=true;scrollTo({top:0,behavior:'smooth'})}async function save(){saving.value=true;try{await(form.value.id?client.put(`/employees/${form.value.id}`,form.value):client.post('/employees',form.value));editing.value=false;await load()}catch(e){error.value=e.response?.data?.message||'Unable to save employee.'}finally{saving.value=false}}async function remove(e){if(confirm(`Delete ${e.full_name}?`)){await client.delete(`/employees/${e.id}`);load()}}function exportCsv(){const data=[['Employee No.','Employee ID','Full Name','Department','Position','Status','Hire Date','Account No.','Phone','Email'],...filtered.value.map(e=>[e.employee_no,e.employee_id,e.full_name,e.department,e.position,e.status_active?'Active':'Inactive',e.hire_date,e.account_no,e.phone,e.email])],csv=data.map(r=>r.map(c=>`"${String(c??'').replaceAll('"','""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='employees.csv';a.click();URL.revokeObjectURL(a.href)}onMounted(load);
</script>
