<template>
  <AccountLayout bare><div class="container py-4">
    <section class="card border-0 shadow-sm mb-4"><div class="card-body d-flex flex-wrap align-items-center justify-content-between gap-3"><div><small class="text-uppercase text-muted fw-bold">Profile Module</small><h2 class="mb-1">Fixed Assets List</h2><span class="text-muted">Dashboard &gt; Profile &gt; Fixed Assets</span></div><div><button v-if="editing" class="btn btn-outline-primary me-2" @click="cancel">Back to List</button><button v-else class="btn btn-primary" @click="startNew">+ New Asset</button></div></div></section>
    <div v-if="error" class="alert alert-danger">{{ error }}</div>
    <template v-if="!editing"><section class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-3"><div v-for="item in summary" :key="item.label" class="col-lg col-md-4"><div class="border rounded p-3 h-100"><small class="text-muted">{{ item.label }}</small><div class="fs-4 fw-bold" :class="item.class">{{ item.value }}</div></div></div></div></div></section><section class="card border-0 shadow-sm mb-4"><div class="card-body row g-3"><div class="col-md-5"><input v-model="search" class="form-control" placeholder="Search assets..." /></div><div class="col-md-3"><select v-model="statusFilter" class="form-select"><option value="">All Statuses</option><option v-for="status in options.statuses" :key="status">{{ status }}</option></select></div></div></section><section class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>No</th><th>Asset ID</th><th>Asset Name</th><th>Asset Group</th><th>Asset Type</th><th>Location</th><th>Status</th><th>Purchase Date</th><th class="text-end">Book Value</th><th>Last Valuation</th><th class="text-end">Action</th></tr></thead><tbody><tr v-for="(asset,index) in filteredAssets" :key="asset.id"><td>{{ index + 1 }}</td><td>{{ asset.asset_no }}</td><td><strong>{{ asset.asset_name }}</strong></td><td>{{ asset.asset_group }}</td><td>{{ asset.asset_type }}</td><td>{{ asset.location }}</td><td><span class="badge" :class="statusClass(asset.status)">{{ asset.status }}</span></td><td>{{ displayDate(asset.purchase_date) }}</td><td class="text-end">{{ money(asset.book_value) }}</td><td>{{ displayDate(asset.last_valuation_date) }}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" @click="edit(asset)">View Details</button></td></tr><tr v-if="!filteredAssets.length"><td colspan="11" class="text-center text-muted py-4">No fixed assets found.</td></tr></tbody></table></div></section></template>
    <form v-else class="row g-3" @submit.prevent="save"><div class="col-lg-6"><Section title="Asset Information"><Field label="Asset Name" required><input v-model.trim="form.asset_name" required class="form-control" placeholder="Enter asset name" /></Field><Field label="Asset Group" required><select v-model="form.asset_group" required class="form-select"><option value="">Select asset group</option><option v-for="group in options.asset_groups" :key="group">{{ group }}</option></select></Field><Field label="Asset Type" required><input v-model.trim="form.asset_type" required class="form-control" placeholder="e.g. Excavator, Pickup, Generator" /></Field><Field label="Location" required><input v-model.trim="form.location" required class="form-control" placeholder="Enter asset location" /></Field></Section></div><div class="col-lg-6"><Section title="Purchase & Valuation"><Field label="Status" required><select v-model="form.status" class="form-select"><option v-for="status in options.statuses" :key="status">{{ status }}</option></select></Field><Field label="Purchase Date" required><input v-model="form.purchase_date" required type="date" class="form-control" /></Field><Field label="Purchase Cost" required><input v-model.number="form.purchase_cost" required min="0" step=".01" type="number" class="form-control" /></Field><Field label="Book Value" required><input v-model.number="form.book_value" required min="0" step=".01" type="number" class="form-control" /></Field><Field label="Last Valuation Date"><input v-model="form.last_valuation_date" type="date" class="form-control" /></Field></Section></div><div class="col-12"><Section title="Notes"><textarea v-model.trim="form.notes" rows="4" class="form-control" placeholder="Enter any additional notes..."></textarea></Section></div><div class="col-12"><button class="btn btn-primary me-2" :disabled="saving">{{ saving ? 'Saving...' : 'Save' }}</button><button v-if="form.id" class="btn btn-outline-danger me-2" type="button" @click="remove(form)">Delete</button><button class="btn btn-outline-secondary" type="button" @click="cancel">Cancel</button></div></form>
  </div></AccountLayout>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import client from '../api/client'
import AccountLayout from '../components/AccountLayout.vue'
const assets=ref([]), search=ref(''), statusFilter=ref(''), editing=ref(false), saving=ref(false), error=ref(''), options=ref({statuses:[],asset_groups:[]})
const blank=()=>({asset_name:'',asset_group:'',asset_type:'',location:'',status:'Active',purchase_date:'',purchase_cost:0,book_value:0,last_valuation_date:'',notes:''})
const form=ref(blank())
const filteredAssets=computed(()=>assets.value.filter(a=>`${a.asset_no} ${a.asset_name} ${a.asset_group} ${a.asset_type} ${a.location}`.toLowerCase().includes(search.value.toLowerCase())&&(!statusFilter.value||a.status===statusFilter.value)))
const summary=computed(()=>[{label:'Total Assets',value:assets.value.length,class:'text-primary'},{label:'Active Assets',value:assets.value.filter(a=>a.status==='Active').length,class:'text-success'},{label:'Under Maintenance',value:assets.value.filter(a=>a.status==='Under Maintenance').length,class:'text-warning'},{label:'Disposed Assets',value:assets.value.filter(a=>a.status==='Disposed').length,class:'text-danger'},{label:'Total Book Value',value:money(assets.value.reduce((total,a)=>total+Number(a.book_value||0),0)),class:'text-primary'}])
const load=async()=>{const [{data:list},{data:optionData}]=await Promise.all([client.get('/fixed-assets'),client.get('/fixed-assets/options')]);assets.value=list.data;options.value=optionData.data}
const startNew=()=>{form.value=blank();error.value='';editing.value=true}
const edit=asset=>{form.value={...blank(),...asset,purchase_date:asset.purchase_date?.slice(0,10)||'',last_valuation_date:asset.last_valuation_date?.slice(0,10)||''};error.value='';editing.value=true}
const cancel=()=>{editing.value=false;form.value=blank();error.value=''}
const save=async()=>{saving.value=true;error.value='';try{await(form.value.id?client.put(`/fixed-assets/${form.value.id}`,form.value):client.post('/fixed-assets',form.value));cancel();await load()}catch(e){error.value=e.response?.data?.message||'Unable to save fixed asset.'}finally{saving.value=false}}
const remove=async asset=>{if(!confirm(`Delete ${asset.asset_name}?`))return;try{await client.delete(`/fixed-assets/${asset.id}`);cancel();await load()}catch(e){error.value=e.response?.data?.message||'Unable to delete fixed asset.'}}
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0))
const displayDate=value=>value?new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString('en-GB'):'—'
const statusClass=status=>status==='Active'?'text-bg-success':status==='Under Maintenance'?'text-bg-warning':'text-bg-danger'
const Section={props:['title'],template:'<section class="card border-0 shadow-sm h-100"><div class="card-body"><h5 class="text-primary text-uppercase fw-bold mb-3">{{ title }}</h5><slot /></div></section>'}
const Field={props:['label','required'],template:'<div class="mb-3"><label class="form-label fw-semibold">{{ label }}<span v-if="required" class="text-danger"> *</span></label><slot /></div>'}
onMounted(()=>load().catch(()=>error.value='Unable to load fixed assets.'))
</script>
