<template>
  <AccountLayout bare><main class="insurance-page">
    <header class="insurance-head"><div class="insurance-title"><i><ShieldCheck :size="31"/></i><div><h1>{{editing?(form.id?'Edit Insurance Company':'New Insurance Company'):'Insurance Companies'}}</h1><p>{{editing?'Add or update an insurance company record':'Manage and view all insurance companies'}}</p></div></div><button v-if="editing" class="ins-btn secondary" @click="cancel"><ArrowLeft :size="17"/> Back to List</button><button v-else class="ins-btn primary" @click="startNew"><CirclePlus :size="17"/> New Insurance Company</button></header>
    <div v-if="error" class="ins-alert"><CircleAlert :size="17"/>{{error}}<button @click="error=''">x</button></div>

    <template v-if="!editing">
      <section class="insurance-stats"><article v-for="card in summary" :key="card.label"><i :class="card.tone"><component :is="card.icon" :size="23"/></i><div><span>{{card.label}}</span><b>{{card.value}}</b><small>{{card.note}}</small></div></article></section>
      <section class="insurance-directory">
        <div class="insurance-tools"><label><Search :size="18"/><input v-model="search" placeholder="Search by company name, policy no..."></label><button class="ins-btn secondary" @click="filtersOpen=!filtersOpen"><ListFilter :size="17"/> Filters</button><button class="ins-btn secondary" @click="exportCsv"><Download :size="17"/> Export</button></div>
        <div v-if="filtersOpen" class="insurance-filters"><select v-model="statusFilter"><option value="">All Statuses</option><option>Active</option><option>Pending</option><option>Inactive</option></select><select v-model="typeFilter"><option value="">All Insurance Types</option><option v-for="type in options.insurance_types" :key="type">{{type}}</option></select><button @click="statusFilter='';typeFilter=''">Clear filters</button></div>
        <div class="insurance-table-wrap"><table><thead><tr><th>#</th><th>Company Name</th><th>Policy No.</th><th>Policy Type</th><th>Status</th><th>Balance</th><th>Expiry Date</th><th class="right">Actions</th></tr></thead><tbody>
          <tr v-for="(company,index) in filtered" :key="company.id"><td>{{index+1}}</td><td><b>{{company.company_name}}</b><small>{{company.company_no}}</small></td><td>{{company.policy_no||'-'}}</td><td>{{company.insurance_type}}</td><td><em :class="company.policy_status.toLowerCase()">{{company.policy_status}}</em></td><td class="money">{{currency(company.balance)}}</td><td :class="{overdue:isExpired(company.expiry_date)}">{{date(company.expiry_date)}}</td><td class="right"><button class="icon-btn" title="View" @click="view(company)"><Eye :size="17"/></button><button class="icon-btn" title="More actions" @click="menu=menu===company.id?null:company.id"><EllipsisVertical :size="18"/></button><div v-if="menu===company.id" class="ins-menu"><button @click="edit(company)"><Pencil :size="14"/> Edit</button><button class="danger" @click="remove(company)"><Trash2 :size="14"/> Delete</button></div></td></tr>
          <tr v-if="!filtered.length"><td colspan="8" class="empty"><ShieldCheck :size="30"/><b>No insurance companies found</b></td></tr>
        </tbody></table></div>
        <footer class="insurance-footer"><span>Showing 1 to {{filtered.length}} of {{filtered.length}} entries</span><nav><button disabled><ChevronLeft :size="15"/></button><button class="active">1</button><button disabled><ChevronRight :size="15"/></button></nav></footer>
        <div class="insurance-legend"><span><em class="active">Active</em> Policy is active and in force</span><span><em class="pending">Pending</em> Policy is pending approval or payment</span><span><em class="inactive">Inactive</em> Policy is expired or cancelled</span></div>
      </section>
    </template>

    <form v-else class="insurance-form" @submit.prevent="save">
      <section><h2>Company Information</h2><label>Company Name *<input v-model.trim="form.company_name" required placeholder="Enter company name"></label><label>Company Type *<select v-model="form.company_type" required><option value="">Select company type</option><option v-for="type in options.company_types" :key="type">{{type}}</option></select></label><label>Status *<select v-model="form.policy_status" required><option>Active</option><option>Pending</option><option>Inactive</option></select></label></section>
      <section><h2>Type of Insurance</h2><label>Type of Insurance *<select v-model="form.insurance_type" required><option value="">Select type of insurance</option><option v-for="type in options.insurance_types" :key="type">{{type}}</option></select></label><label>Policy Number<input v-model.trim="form.policy_no" placeholder="Enter policy number"></label><label>Policy Expiry Date<input v-model="form.expiry_date" type="date"></label><label>Balance<input v-model="form.balance" type="number" min="0" step="0.01" placeholder="0.00"></label></section>
      <section><h2>Agent / Broker Information</h2><label>Agent / Broker Name<input v-model.trim="form.agent_broker_name" placeholder="Enter agent or broker name"></label><label>Phone Number<input v-model.trim="form.agent_broker_phone" placeholder="Enter phone number"></label><label>Email Address<input v-model.trim="form.agent_broker_email" type="email" placeholder="Enter email address"></label></section>
      <section><h2>Contact Information</h2><label>Primary Contact Name *<input v-model.trim="form.primary_contact_name" required placeholder="Enter primary contact name"></label><label>Phone Number *<input v-model.trim="form.primary_contact_phone" required placeholder="Enter phone number"></label><label>Email Address<input v-model.trim="form.primary_contact_email" type="email" placeholder="Enter email address"></label></section>
      <section class="wide"><h2>Mailing Address</h2><div class="address-grid"><label>Street Address *<input v-model.trim="form.street_address" required placeholder="Enter street address"></label><label>City *<input v-model.trim="form.city" required placeholder="Enter city"></label><label>State / Province<input v-model.trim="form.state_province" placeholder="Enter state / province"></label><label>Postal / ZIP Code *<input v-model.trim="form.postal_code" required placeholder="Enter postal / ZIP code"></label><label class="country">Country *<select v-model="form.country_id" required><option :value="null">Select country</option><option v-for="country in options.countries" :key="country.id" :value="country.id">{{country.country_name}}</option></select></label></div></section>
      <section class="wide"><h2>Notes</h2><label>Notes<textarea v-model.trim="form.notes" rows="4" placeholder="Enter any additional notes..."></textarea></label></section>
      <footer class="wide"><button class="ins-btn secondary" type="button" @click="startNew"><CirclePlus :size="16"/> New</button><button class="ins-btn primary" :disabled="saving"><Save :size="16"/>{{saving?'Saving...':'Save'}}</button><button class="ins-btn primary" type="button" @click="save(true)"><Files :size="16"/> Save & New</button><button v-if="form.id" class="ins-btn danger" type="button" @click="remove(form)"><Trash2 :size="16"/> Delete</button><button class="ins-btn secondary" type="button" @click="printPage"><Printer :size="16"/> Print</button><button class="ins-btn secondary cancel" type="button" @click="cancel"><X :size="16"/> Cancel</button></footer>
    </form>

    <div v-if="selected" class="ins-overlay" @click.self="selected=null"><section class="ins-modal"><button @click="selected=null"><X :size="17"/></button><i><ShieldCheck :size="28"/></i><h2>{{selected.company_name}}</h2><p>{{selected.policy_no}} · {{selected.insurance_type}}</p><dl><div><dt>Status</dt><dd>{{selected.policy_status}}</dd></div><div><dt>Balance</dt><dd>{{currency(selected.balance)}}</dd></div><div><dt>Expiry</dt><dd>{{date(selected.expiry_date)}}</dd></div><div><dt>Contact</dt><dd>{{selected.primary_contact_name}}</dd></div></dl><button class="ins-btn primary" @click="edit(selected);selected=null"><Pencil :size="15"/> Edit Company</button></section></div>
  </main></AccountLayout>
</template>
<script setup>
import{computed,onMounted,ref}from'vue';import{ArrowLeft,Building2,CalendarClock,ChevronLeft,ChevronRight,CircleAlert,CircleDollarSign,CirclePlus,Download,EllipsisVertical,Eye,Files,ListFilter,Pencil,Printer,Save,Search,ShieldCheck,Trash2,X}from'lucide-vue-next';import client from'../api/client';import AccountLayout from'../components/AccountLayout.vue';import'./InsuranceCompanies.css';import'./ProfileTableLayout.css';
const companies=ref([]),search=ref(''),statusFilter=ref(''),typeFilter=ref(''),editing=ref(false),saving=ref(false),error=ref(''),filtersOpen=ref(false),menu=ref(null),selected=ref(null),options=ref({countries:[],company_types:[],insurance_types:[]});const blank=()=>({company_name:'',company_type:'',insurance_type:'',policy_no:'',policy_status:'Active',balance:0,expiry_date:'',status_active:true,agent_broker_name:'',agent_broker_phone:'',agent_broker_email:'',primary_contact_name:'',primary_contact_phone:'',primary_contact_email:'',street_address:'',city:'',state_province:'',postal_code:'',country_id:null,notes:''}),form=ref(blank());
const filtered=computed(()=>companies.value.filter(c=>`${c.company_name} ${c.company_no} ${c.policy_no||''}`.toLowerCase().includes(search.value.toLowerCase())&&(!statusFilter.value||c.policy_status===statusFilter.value)&&(!typeFilter.value||c.insurance_type===typeFilter.value))),active=computed(()=>companies.value.filter(c=>c.policy_status==='Active').length),soon=computed(()=>companies.value.filter(c=>{if(!c.expiry_date)return false;const days=(new Date(c.expiry_date)-new Date())/86400000;return days>=0&&days<=30}).length),total=computed(()=>companies.value.reduce((n,c)=>n+Number(c.balance||0),0));const summary=computed(()=>[{label:'Total Companies',value:companies.value.length,note:'All insurance companies',icon:Building2,tone:'blue'},{label:'Active Policies',value:active.value,note:'Currently active',icon:ShieldCheck,tone:'green'},{label:'Total Balance',value:currency(total.value),note:'Total outstanding balance',icon:CircleDollarSign,tone:'green'},{label:'Expiring Soon',value:soon.value,note:'Within next 30 days',icon:CalendarClock,tone:'orange'}]);
const currency=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0)),date=v=>v?new Date(`${v.slice(0,10)}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'}):'-',isExpired=v=>v&&new Date(v)<new Date();async function load(){const[{data:list},{data:opts}]=await Promise.all([client.get('/insurance-companies'),client.get('/insurance-companies/options')]);companies.value=list.data;options.value=opts.data}function startNew(){form.value=blank();editing.value=true;error.value=''}function edit(c){form.value={...blank(),...c,expiry_date:c.expiry_date?.slice(0,10)||''};editing.value=true;menu.value=null}function view(c){selected.value=c}function cancel(){editing.value=false;form.value=blank();error.value=''}async function save(again=false){saving.value=true;error.value='';try{form.value.status_active=form.value.policy_status!=='Inactive';await(form.value.id?client.put(`/insurance-companies/${form.value.id}`,form.value):client.post('/insurance-companies',form.value));await load();if(again)startNew();else cancel()}catch(e){error.value=e.response?.data?.message||'Unable to save insurance company.'}finally{saving.value=false}}async function remove(c){menu.value=null;if(!confirm(`Delete ${c.company_name}?`))return;await client.delete(`/insurance-companies/${c.id}`);cancel();load()}function exportCsv(){const data=[['Company','Policy No.','Type','Status','Balance','Expiry'],...filtered.value.map(c=>[c.company_name,c.policy_no,c.insurance_type,c.policy_status,c.balance,c.expiry_date])],csv=data.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='insurance-companies.csv';a.click();URL.revokeObjectURL(a.href)}const printPage=()=>window.print();onMounted(()=>load().catch(()=>error.value='Unable to load insurance companies.'));
</script>
