<template>
  <AccountLayout bare>
    <main class="po-page" :aria-busy="busy">
      <header class="po-header">
        <div class="po-heading"><FileText :size="30"/><div><h1>Purchase Invoice</h1><p>All Purchase Invoices</p></div></div>
        <div v-if="view === 'list'" class="po-header-search"><Search/><input v-model="filters.search" aria-label="Search invoices" placeholder="Search Invoice No. / PO No. / Seller / Ref. No..."></div>
        <div class="po-actions"><button v-if="view === 'detail'" class="po-btn" @click="backToList"><ArrowLeft/> Back to list</button><span v-if="view === 'detail'" class="po-pill" :class="slug(form.status)">{{ form.status }}</span></div>
      </header>

      <div v-if="error" class="po-alert error" role="alert">{{ error }}</div>
      <div v-if="notice" class="po-alert success" role="status">{{ notice }}</div>

      <template v-if="view === 'list'">
        <section class="po-metrics">
          <article v-for="card in metrics" :key="card.label" :class="card.tone"><component :is="card.icon" :size="30"/><div><h2>{{ card.label }}</h2><strong>{{ card.rows.length }} <small>Invoices</small></strong><b v-for="total in currencyTotals(card.rows)" :key="total.code">{{ money(total.amount) }} {{ total.code }}</b></div></article>
        </section>
        <form class="po-filters" @submit.prevent="page = 1">
          <label>Date Range<span class="po-date-range"><input v-model="filters.from" type="date"><input v-model="filters.to" type="date"></span></label>
          <label>Seller<select v-model="filters.seller"><option value="">All Sellers</option><option v-for="name in sellerNames" :key="name">{{ name }}</option></select></label>
          <label>Status<select v-model="filters.status"><option value="">All Status</option><option v-for="value in statuses" :key="value">{{ value }}</option></select></label>
          <label>Payment Status<select v-model="filters.payment"><option value="">All Status</option><option v-for="value in paymentStatuses" :key="value">{{ value }}</option></select></label>
          <label>Department<select v-model="filters.department"><option value="">All Departments</option><option v-for="value in departments" :key="value">{{ value }}</option></select></label>
          <label>Project<select v-model="filters.project"><option value="">All Projects</option><option v-for="value in projects" :key="value">{{ value }}</option></select></label>
          <button class="po-btn primary" type="submit"><Search/> Search</button><button class="po-btn" type="button" @click="resetFilters"><RotateCcw/> Reset</button>
        </form>
        <section class="po-list">
          <header class="po-section-head"><h2>Purchase Invoice List</h2><div class="po-actions"><button class="po-btn primary" @click="startNew"><Plus/> New Purchase Invoice</button><button class="po-btn green" @click="exportExcel"><Download/> Export</button></div></header>
          <div class="po-table-scroll"><table class="po-list-table"><thead><tr><th>A No.</th><th v-for="col in listColumns" :key="col.key"><button @click="sortBy(col.key)">{{ col.label }} <ArrowUpDown :size="12"/></button></th><th>View</th></tr></thead><tbody>
            <tr v-for="(row, index) in paginatedRows" :key="row.id"><td>{{ (page - 1) * perPage + index + 1 }}</td><td><button class="po-link" @click="openInvoice(row)">{{ row.invoice_no }}</button></td><td>{{ dateLabel(row.invoice_date) }}</td><td>{{ row.po_no || '-' }}</td><td>{{ dateLabel(row.purchase_order?.po_date) }}</td><td>{{ row.seller_no || '-' }}</td><td>{{ row.seller_name }}</td><td class="po-positive">{{ money(sellerBalance(row)) }}</td><td class="po-number">{{ money(row.total) }}</td><td class="po-number">{{ money(row.paid) }}</td><td class="po-number">{{ money(due(row)) }}</td><td><span class="po-pill" :class="slug(displayPaymentStatus(row))">{{ displayPaymentStatus(row) }}</span></td><td><span class="po-pill" :class="slug(row.status)">{{ row.status }}</span></td><td>{{ row.invoice_type }}</td><td><button class="po-btn compact" @click="openInvoice(row)"><Eye/> View</button></td></tr>
            <tr v-if="!paginatedRows.length"><td colspan="16" class="po-empty">{{ busy ? 'Loading purchase invoices...' : 'No purchase invoices found.' }}</td></tr>
          </tbody></table></div>
          <footer class="po-pagination"><span>Showing {{ filteredRows.length ? (page - 1) * perPage + 1 : 0 }} to {{ Math.min(page * perPage, filteredRows.length) }} of {{ filteredRows.length }} entries</span><div class="po-actions"><select v-model.number="perPage"><option :value="15">15</option><option :value="30">30</option><option :value="50">50</option></select><button class="po-icon" title="Previous page" :disabled="page === 1" @click="page--"><ChevronLeft/></button><b>{{ page }} / {{ pageCount }}</b><button class="po-icon" title="Next page" :disabled="page === pageCount" @click="page++"><ChevronRight/></button></div></footer>
          <div class="po-action-bar"><b>Action Bar:</b><button class="po-btn primary" @click="printPage"><Printer/> Print</button><button class="po-btn green" @click="savePdf"><FileDown/> Save PDF</button><button class="po-btn" @click="emailInvoice"><Mail/> Email</button></div>
        </section>
      </template>

      <div v-else class="po-workspace">
        <section class="po-document">
          <header class="po-document-head"><div class="po-heading"><FileText/><h2>Purchase Invoice</h2></div><div class="po-actions"><b>{{ form.invoice_no || 'New invoice' }}</b><span class="po-pill" :class="slug(form.status)">{{ form.status }}</span><button class="po-icon" title="Print invoice" @click="printPage"><Printer/></button><button class="po-icon" title="Email invoice" @click="emailInvoice"><Mail/></button></div></header>
          <div class="po-document-body">
            <div class="po-details-grid">
              <section><h3>Sellers</h3><div v-if="editing" class="po-field"><label>Seller</label><i>:</i><SearchableSelect v-model="form.seller_id" :options="sellers" option-label="seller_name" option-value="id" :description-keys="['contact_person','email','phone']" placeholder="Search seller..." @select="applySeller"/></div><Field label="Vendor ID" :model-value="form.seller_no"/><Field label="Company Name" v-model="form.seller_name" :editable="editing && !form.seller_id"/><Field v-for="field in sellerFields" :key="field.key" :label="field.label" v-model="form.seller_details[field.key]" :editable="editing && !form.seller_id" :multiline="field.key === 'address'"/></section>
              <section><h3>Requested By</h3><Field label="Department" v-model="form.department" :editable="editing"/><Field label="Contact Person" v-model="form.requested_by" :editable="editing"/><Field v-for="field in requesterFields" :key="field.key" :label="field.label" v-model="form.requester_details[field.key]" :editable="editing" :multiline="field.key === 'address'"/><Field label="Project" v-model="form.project" :editable="editing"/></section>
              <section><h3>Invoice Details</h3><Field label="Invoice No." v-model="form.invoice_no" :editable="editing"/><div v-if="editing" class="po-field"><label>Purchase Order</label><i>:</i><select v-model="form.purchase_order_id" @change="applyOrder"><option :value="null">No purchase order</option><option v-for="order in orders" :key="order.id" :value="order.id">{{ order.po_no }} - {{ order.seller_name }}</option></select></div><Field v-else label="PO No." :model-value="form.po_no"/><Field label="Invoice Date" v-model="form.invoice_date" :editable="editing" type="date" :display-value="dateLabel(form.invoice_date)"/><Field label="Due Date" v-model="form.due_date" :editable="editing" type="date" :display-value="dateLabel(form.due_date)"/><Field label="Delivery Date" v-model="form.delivery_date" :editable="editing" type="date" :display-value="dateLabel(form.delivery_date)"/><Field label="Delivery Location" v-model="form.delivery_location" :editable="editing"/><Field label="Currency" v-model="form.currency_code" :editable="editing" :options="currencies"/><Field label="Invoice Type" v-model="form.invoice_type" :editable="editing" :options="invoiceTypes"/><Field label="Payment Term" v-model="form.payment_term" :editable="editing" :options="paymentTerms"/><Field label="Payment Method" v-model="form.payment_method" :editable="editing" :options="paymentMethods"/></section>
            </div>
            <section class="po-items"><div v-if="editing" class="po-section-head"><h3>Items / Services</h3><button class="po-btn compact primary" @click="addItem"><Plus/> Add item</button></div><div class="po-table-scroll"><table><thead><tr><th>Item / Service</th><th>Item Code / SKU</th><th>UOM</th><th>Qty</th><th>Cost Rate</th><th>Sub Total</th><th>Sales Tax</th><th>Total</th><th v-if="editing"></th></tr></thead><tbody><tr v-for="(item,index) in form.items" :key="index"><td><SearchableSelect v-if="editing" v-model="item.name" :options="catalog" option-label="name" option-value="name" :description-keys="['code','uom']" placeholder="Search item..." @select="applyCatalog(item,$event)"/><span v-else>{{ item.name }}</span></td><td><input v-if="editing" v-model="item.code"><span v-else>{{ item.code || '-' }}</span></td><td><input v-if="editing" v-model="item.uom"><span v-else>{{ item.uom }}</span></td><td><input v-if="editing" v-model.number="item.quantity" type="number" min="0.01" step="0.01"><span v-else>{{ money(item.quantity) }}</span></td><td><input v-if="editing" v-model.number="item.cost_rate" type="number" min="0" step="0.01"><span v-else>{{ money(item.cost_rate) }}</span></td><td>{{ money(lineSubtotal(item)) }}</td><td><input v-if="editing" v-model.number="item.sales_tax" type="number" min="0" step="0.01"><span v-else>{{ money(item.sales_tax) }}</span></td><td>{{ money(lineTotal(item)) }}</td><td v-if="editing"><button class="po-icon danger" title="Remove item" @click="form.items.splice(index,1)"><Trash2/></button></td></tr><tr v-if="!form.items.length"><td :colspan="editing ? 9 : 8" class="po-empty">No items added.</td></tr></tbody><tfoot><tr><th colspan="5">Total</th><th>{{ money(subtotal) }}</th><th>{{ money(taxTotal) }}</th><th>{{ money(grandTotal) }}</th><th v-if="editing"></th></tr></tfoot></table></div></section>
            <div class="po-bottom-grid"><section><h3>Terms &amp; Conditions</h3><textarea v-if="editing" v-model="form.terms" rows="4"/><p v-else class="po-terms">{{ form.terms || '-' }}</p><div class="po-metadata"><Field label="Last modification" :model-value="dateTimeLabel(form.updated_at)"/><Field label="Created By" :model-value="form.creator?.name"/><Field label="Created Date" :model-value="dateTimeLabel(form.created_at)"/></div></section><section><h3>Delivery Information</h3><Field label="Delivery Date" :model-value="dateLabel(form.delivery_date)"/><Field label="Delivery Location" :model-value="form.delivery_location"/><Field label="Delivery Contact" v-model="form.delivery_details.contact_person" :editable="editing"/><Field label="Delivery Phone" v-model="form.delivery_details.phone" :editable="editing"/><Field label="Delivery Instructions" v-model="form.notes" :editable="editing" multiline/></section><section class="po-totals"><Field label="Sub Total" :model-value="money(subtotal)"/><Field label="Sales Tax (Total)" :model-value="money(taxTotal)"/><Field label="Paid" :model-value="money(form.paid)"/><div><span>Balance ({{ form.currency_code }})</span><strong>{{ money(due(form)) }}</strong></div><div><span>Grand Total ({{ form.currency_code }})</span><strong>{{ money(grandTotal) }}</strong></div></section></div>
            <section v-if="form.attachments.length" class="po-attachments"><h3>Attachments</h3><button v-for="file in form.attachments" :key="file.id" class="po-btn compact" @click="downloadAttachment(file)"><Paperclip/> {{ file.name }}</button></section>
          </div>
          <footer class="po-document-footer"><div class="po-actions"><button class="po-btn" @click="startNew"><Plus/> New</button><button class="po-btn" :disabled="editing || Number(form.paid) > 0" @click="editing = true"><Pencil/> Edit</button><button class="po-btn danger" :disabled="!form.id || Number(form.paid) > 0" @click="deleteInvoice"><Trash2/> Delete</button><button class="po-btn primary" :disabled="!editing" @click="saveInvoice"><Save/> Save</button><button v-if="editing" class="po-btn" @click="cancelEdit"><X/> Cancel</button><button class="po-btn" @click="printPage"><Printer/> Print</button><button class="po-btn" @click="savePdf"><FileDown/> Save PDF</button><button class="po-btn" @click="emailInvoice"><Mail/> Email</button><button class="po-btn green" :disabled="!canDecide" @click="workflow('approve')"><Check/> Approve</button><button class="po-btn danger" :disabled="!canDecide" @click="workflow('reject')"><X/> Reject</button><button class="po-btn" :disabled="!form.id || editing" @click="duplicateInvoice"><Copy/> Duplicate Invoice</button></div><div class="po-actions"><button class="po-btn green" :disabled="!canPay" @click="openPayment"><BadgeDollarSign/> Receive Payment</button><button class="po-btn" :disabled="!form.id" @click="fileInput.click()"><Paperclip/> Attach File</button><input ref="fileInput" class="po-hidden" type="file" @change="uploadAttachment"><button class="po-btn" :disabled="!form.id" @click="modal='audit'"><History/> View Audit Log</button><button class="po-btn" :disabled="!canSubmit" @click="workflow('submit')"><Send/> Send for Approval</button><button class="po-btn green" @click="exportExcel"><FileSpreadsheet/> Export Excel</button></div></footer>
        </section>
        <aside class="po-sidebar"><section><h3>Transaction Tracker</h3><div class="po-table-scroll"><table class="po-tracker"><thead><tr><th>Doc. Type</th><th>No.</th><th>Date</th><th>Total</th></tr></thead><tbody><tr v-if="form.po_no"><td>Purchase Order</td><td>{{ form.po_no }}</td><td>{{ dateLabel(form.purchase_order?.po_date) }}</td><td>{{ money(form.total) }}</td></tr><tr><td>Purchase Invoice</td><td>{{ form.invoice_no }}</td><td>{{ dateLabel(form.invoice_date) }}</td><td>{{ money(form.total) }}</td></tr><tr v-for="payment in form.payments" :key="payment.id"><td>Bill Payment</td><td>{{ payment.payment_no }}</td><td>{{ dateLabel(payment.payment_date) }}</td><td>-{{ money(payment.amount) }}</td></tr></tbody><tfoot><tr><th>Balance</th><th colspan="2">{{ form.currency_code }}</th><th>{{ money(due(form)) }}</th></tr></tfoot></table></div></section><section><h3>Quick Reports</h3><button v-for="report in reports" :key="report.label" class="po-report-link"><span>{{ report.label }}</span><b>{{ report.count }}</b></button></section><section><h3>Current Invoice Details</h3><Field label="Invoice No." :model-value="form.invoice_no"/><Field label="PO No." :model-value="form.po_no"/><Field label="Invoice Date" :model-value="dateLabel(form.invoice_date)"/><Field label="Due Date" :model-value="dateLabel(form.due_date)"/><Field label="Delivery Date" :model-value="dateLabel(form.delivery_date)"/><Field label="Currency" :model-value="form.currency_code"/><Field label="Status" :model-value="form.status"/><Field label="Payment Status" :model-value="displayPaymentStatus(form)"/><Field label="Payment Term" :model-value="form.payment_term"/><Field label="Payment Method" :model-value="form.payment_method"/></section></aside>
      </div>

      <div v-if="modal" class="po-modal-backdrop" @click.self="modal=''" @keydown.esc="modal=''"> <section class="po-modal" role="dialog" aria-modal="true"><header><h2>{{ modal === 'payment' ? 'Receive Payment' : 'Purchase Invoice Audit Log' }}</h2><button class="po-icon" title="Close" @click="modal=''"> <X/></button></header><div v-if="modalError" class="po-alert error">{{ modalError }}</div><form v-if="modal === 'payment'" @submit.prevent="receivePayment"><Field label="Payment No." v-model="paymentForm.payment_no" editable/><Field label="Payment Date" v-model="paymentForm.payment_date" editable type="date"/><Field label="Amount" v-model="paymentForm.amount" editable type="number"/><Field label="Method" v-model="paymentForm.method" editable :options="paymentMethods"/><Field label="Reference" v-model="paymentForm.reference" editable/><Field label="Notes" v-model="paymentForm.notes" editable multiline/><button class="po-btn green" :disabled="busy"><BadgeDollarSign/> Receive Payment</button></form><div v-else class="po-table-scroll"><table><thead><tr><th>Date / Time</th><th>User</th><th>Action</th><th>Details</th></tr></thead><tbody><tr v-for="entry in form.activities" :key="entry.id"><td>{{ dateTimeLabel(entry.created_at) }}</td><td>{{ entry.actor }}</td><td>{{ entry.action }}</td><td>{{ activityDetails(entry.changes) }}</td></tr></tbody></table></div></section></div>
    </main>
  </AccountLayout>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { FileText, Search, Plus, RotateCcw, Download, Printer, Mail, FileDown, FileSpreadsheet, ArrowLeft, ArrowUpDown, Eye, Pencil, Save, Trash2, X, Check, Copy, Paperclip, History, Send, BadgeDollarSign, ChevronLeft, ChevronRight, WalletCards, BadgeCheck, Clock, CircleX } from 'lucide-vue-next'
import AccountLayout from '../components/AccountLayout.vue'
import Field from '../components/PurchaseOrderField.vue'
import SearchableSelect from '../components/SearchableSelect.vue'
import client from '../api/client'
import { authState } from '../store/auth'
import { roundMoney, lineSubtotal, lineTotal, today, money, dateLabel, dateTimeLabel } from '../utils/purchaseOrders'

const view=ref('list'), rows=ref([]), sellers=ref([]), orders=ref([]), catalog=ref([]), currencies=ref(['USD','CAD']), paymentTerms=ref([]), paymentMethods=ref([])
const busy=ref(false), editing=ref(false), error=ref(''), notice=ref(''), modal=ref(''), modalError=ref(''), fileInput=ref(null), page=ref(1), perPage=ref(15), sort=ref({key:'invoice_date',direction:-1})
const statuses=['Draft','Pending','Approved','Rejected'], paymentStatuses=['Unpaid','Partial','Paid','Overdue'], invoiceTypes=['Regular','Credit Note']
const sellerFields=[{key:'contact_person',label:'Contact Person'},{key:'phone',label:'Phone'},{key:'email',label:'Email'},{key:'address',label:'Address'},{key:'website',label:'Website'},{key:'tax_number',label:'Tax Number'},{key:'vendor_category',label:'Vendor Category'}]
const requesterFields=[{key:'phone',label:'Phone'},{key:'email',label:'Email'},{key:'company_name',label:'Company Name'},{key:'address',label:'Address'}]
const listColumns=[{key:'invoice_no',label:'Invoice No.'},{key:'invoice_date',label:'Invoice Date'},{key:'po_no',label:'PO No.'},{key:'po_date',label:'PO Date'},{key:'seller_no',label:'Seller No.'},{key:'seller_name',label:'Seller Name'},{key:'balance',label:'Seller Balance'},{key:'total',label:'Total'},{key:'paid',label:'Paid'},{key:'due',label:'Due'},{key:'payment_status',label:'Payment Status'},{key:'status',label:'Status'},{key:'invoice_type',label:'Invoice Type'}]
const initialFilters=()=>({search:'',from:'',to:'',seller:'',status:'',payment:'',department:'',project:''}), filters=ref(initialFilters())
const blank=()=>({id:null,invoice_no:'',purchase_order_id:null,po_no:'',seller_id:null,seller_no:'',seller_name:'',seller_details:Object.fromEntries(sellerFields.map(x=>[x.key,''])),requested_by:authState.user?.name||'',department:'',project:'',requester_details:{phone:'',email:authState.user?.email||'',company_name:'',address:''},invoice_date:today(),due_date:'',delivery_date:'',delivery_location:'',delivery_details:{contact_person:'',phone:'',email:''},currency_code:'CAD',status:'Draft',payment_status:'Unpaid',invoice_type:'Regular',payment_term:'',payment_method:'',paid:0,items:[],terms:'',notes:'',payments:[],activities:[],attachments:[],purchase_order:null})
const form=ref(blank()), paymentForm=ref({}), unique=v=>[...new Set(v.filter(Boolean))].sort(), slug=v=>String(v||'').toLowerCase().replace(/\s+/g,'-')
const sellerNames=computed(()=>unique([...sellers.value.map(x=>x.seller_name),...rows.value.map(x=>x.seller_name)])), departments=computed(()=>unique(rows.value.map(x=>x.department))), projects=computed(()=>unique(rows.value.map(x=>x.project)))
const due=row=>roundMoney(Number(row.total||0)-Number(row.paid||0)), displayPaymentStatus=row=>due(row)<=0?'Paid':Number(row.paid)>0?'Partial':(row.due_date&&String(row.due_date).slice(0,10)<today()?'Overdue':'Unpaid')
const sameSeller=(a,b)=>a.seller_id&&b.seller_id?Number(a.seller_id)===Number(b.seller_id):a.seller_name===b.seller_name
const sellerBalance=row=>roundMoney(rows.value.filter(x=>sameSeller(x,row)&&x.currency_code===row.currency_code).reduce((sum,x)=>sum+due(x),0))
const filteredRows=computed(()=>rows.value.filter(row=>{const f=filters.value,q=f.search.toLowerCase(),d=String(row.invoice_date).slice(0,10);return(!q||[row.invoice_no,row.po_no,row.seller_name,row.seller_no].some(x=>String(x||'').toLowerCase().includes(q)))&&(!f.seller||row.seller_name===f.seller)&&(!f.status||row.status===f.status)&&(!f.payment||displayPaymentStatus(row)===f.payment)&&(!f.department||row.department===f.department)&&(!f.project||row.project===f.project)&&(!f.from||d>=f.from)&&(!f.to||d<=f.to)}).sort((a,b)=>{const val=(x,k)=>['total','paid'].includes(k)?Number(x[k]):k==='due'?due(x):k==='balance'?sellerBalance(x):k==='payment_status'?displayPaymentStatus(x):k==='po_date'?x.purchase_order?.po_date||'':x[k]||'';const x=val(a,sort.value.key),y=val(b,sort.value.key);return(typeof x==='number'?x-y:String(x).localeCompare(String(y),undefined,{numeric:true}))*sort.value.direction}))
const pageCount=computed(()=>Math.max(1,Math.ceil(filteredRows.value.length/perPage.value))), paginatedRows=computed(()=>filteredRows.value.slice((page.value-1)*perPage.value,page.value*perPage.value))
const metrics=computed(()=>[{label:'Total Invoices',tone:'blue',icon:WalletCards,rows:filteredRows.value},{label:'Total Paid',tone:'green',icon:BadgeCheck,rows:filteredRows.value.filter(x=>displayPaymentStatus(x)==='Paid')},{label:'Total Partial',tone:'amber',icon:Clock,rows:filteredRows.value.filter(x=>displayPaymentStatus(x)==='Partial')},{label:'Total Overdue',tone:'red',icon:CircleX,rows:filteredRows.value.filter(x=>displayPaymentStatus(x)==='Overdue')},{label:'Total Credit Note',tone:'purple',icon:FileText,rows:filteredRows.value.filter(x=>x.invoice_type==='Credit Note')}])
const subtotal=computed(()=>roundMoney(form.value.items.reduce((s,x)=>s+lineSubtotal(x),0))), taxTotal=computed(()=>roundMoney(form.value.items.reduce((s,x)=>s+Number(x.sales_tax||0),0))), grandTotal=computed(()=>roundMoney(subtotal.value+taxTotal.value))
const canSubmit=computed(()=>form.value.id&&!editing.value&&form.value.status==='Draft'), canDecide=computed(()=>form.value.id&&!editing.value&&['Draft','Pending'].includes(form.value.status)), canPay=computed(()=>form.value.id&&!editing.value&&form.value.status==='Approved'&&due(form.value)>0)
const reports=computed(()=>[{label:'Purchase Documents',count:rows.value.length+orders.value.length},{label:'Payment List',count:rows.value.reduce((s,x)=>s+(x.payments?.length||0),0)},{label:'Unpaid Invoices',count:rows.value.filter(x=>due(x)>0).length},{label:'AP Aging Report',count:rows.value.filter(x=>displayPaymentStatus(x)==='Overdue').length},{label:'Account Statement',count:rows.value.length},{label:'Sellers Paid Sales Taxes',count:rows.value.filter(x=>Number(x.paid)>0&&Number(x.sales_tax)>0).length}])
function currencyTotals(list){const out={};list.forEach(x=>out[x.currency_code]=(out[x.currency_code]||0)+Number(x.total));return Object.entries(out).map(([code,amount])=>({code,amount}))}
function normalize(x){const base=blank();return{...base,...x,seller_id:x.seller_id?Number(x.seller_id):null,purchase_order_id:x.purchase_order_id?Number(x.purchase_order_id):null,invoice_date:String(x.invoice_date||today()).slice(0,10),due_date:String(x.due_date||'').slice(0,10),delivery_date:String(x.delivery_date||'').slice(0,10),seller_details:{...base.seller_details,...x.seller_details},requester_details:{...base.requester_details,...x.requester_details},delivery_details:{...base.delivery_details,...x.delivery_details},items:(x.items||[]).map(i=>({...i})),payments:x.payments||[],activities:x.activities||[],attachments:x.attachments||[]}}
const apiError=e=>Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||e.message||'Unable to complete this request.'
async function fetchAll(url,params={}){let current=1,last=1,out=[];do{const{data}=await client.get(url,{params:{...params,per_page:100,page:current}}),body=data.data;out.push(...(Array.isArray(body)?body:body?.data||[]));last=data.meta?.last_page||body?.last_page||1;current++}while(current<=last);return out}
async function load(){rows.value=await fetchAll('/purchase-invoices')}
async function loadOptions(){const results=await Promise.allSettled([fetchAll('/sellers',{is_active:1}),fetchAll('/purchase-orders'),fetchAll('/service-items',{status:1}),fetchAll('/currencies'),fetchAll('/invoice-terms'),fetchAll('/payment-methods')]),val=i=>results[i].status==='fulfilled'?results[i].value:[];sellers.value=val(0);orders.value=val(1);catalog.value=val(2).map(x=>({name:x.item_name,code:x.item_no,uom:x.unit_of_measure||'PCS',price:Number(x.price||0)}));if(val(3).length)currencies.value=unique(val(3).map(x=>x.currency_code));paymentTerms.value=unique(val(4).filter(x=>Number(x.status)===1).map(x=>x.term_name));paymentMethods.value=unique(val(5).filter(x=>x.status_active).map(x=>x.name))}
function startNew(){form.value=blank();editing.value=true;view.value='detail';error.value='';notice.value=''}
async function openInvoice(row){busy.value=true;try{const{data}=await client.get('/purchase-invoices/'+row.id);form.value=normalize(data.data);editing.value=false;view.value='detail'}catch(e){error.value=apiError(e)}finally{busy.value=false}}
function backToList(){view.value='list';editing.value=false;error.value=''}
async function cancelEdit(){if(form.value.id)await openInvoice(form.value);else backToList()}
function applySeller(s){form.value.seller_id=s?.id||null;form.value.seller_name=s?.seller_name||'';form.value.seller_no=s?'SLR-'+String(s.id).padStart(3,'0'):'';form.value.seller_details=Object.fromEntries(sellerFields.map(x=>[x.key,s?.[x.key]||'']))}
function applyOrder(){const order=orders.value.find(x=>x.id===Number(form.value.purchase_order_id));if(!order)return;form.value=normalize({...form.value,purchase_order_id:order.id,po_no:order.po_no,seller_id:order.seller_id,seller_no:order.seller_no,seller_name:order.seller_name,seller_details:order.seller_details,requested_by:order.requested_by,department:order.department,project:order.project,requester_details:order.requester_details,delivery_date:String(order.expected_delivery_at||'').slice(0,10),delivery_location:order.delivery_location,delivery_details:order.delivery_details,currency_code:order.currency_code,payment_term:order.payment_term,payment_method:order.payment_method,items:order.items,terms:order.terms,notes:order.notes});editing.value=true}
function addItem(){form.value.items.push({name:'',code:'',uom:'PCS',quantity:1,cost_rate:0,sales_tax:0})} function applyCatalog(item,x){if(x)Object.assign(item,{name:x.name,code:x.code,uom:x.uom,cost_rate:x.price})}
async function saveInvoice(){if(!form.value.seller_name.trim()||!form.value.items.length){error.value='Select a seller and add at least one item.';return}busy.value=true;try{const{data}=form.value.id?await client.put('/purchase-invoices/'+form.value.id,form.value):await client.post('/purchase-invoices',form.value);form.value=normalize(data.data);editing.value=false;await load();notice.value='Purchase invoice saved.'}catch(e){error.value=apiError(e)}finally{busy.value=false}}
async function workflow(action){busy.value=true;try{const{data}=await client.post('/purchase-invoices/'+form.value.id+'/workflow',{action});form.value=normalize(data.data);await load();notice.value='Invoice '+form.value.status.toLowerCase()+'.'}catch(e){error.value=apiError(e)}finally{busy.value=false}}
async function deleteInvoice(){if(!confirm('Delete '+form.value.invoice_no+'?'))return;try{await client.delete('/purchase-invoices/'+form.value.id);await load();backToList();notice.value='Purchase invoice deleted.'}catch(e){error.value=apiError(e)}}
function duplicateInvoice(){form.value={...normalize(form.value),id:null,invoice_no:'',status:'Draft',payment_status:'Unpaid',paid:0,payments:[],activities:[],attachments:[],created_at:null,updated_at:null};editing.value=true}
function openPayment(){paymentForm.value={payment_no:'BPAY-'+String(Date.now()).slice(-6),payment_date:today(),amount:due(form.value),method:form.value.payment_method||'',reference:'',notes:''};modal.value='payment'}
async function receivePayment(){busy.value=true;modalError.value='';try{const{data}=await client.post('/purchase-invoices/'+form.value.id+'/payments',paymentForm.value);form.value=normalize(data.data);await load();modal.value='';notice.value='Payment received.'}catch(e){modalError.value=apiError(e)}finally{busy.value=false}}
async function uploadAttachment(e){const file=e.target.files[0];if(!file)return;const body=new FormData();body.append('file',file);try{const{data}=await client.post('/purchase-invoices/'+form.value.id+'/attachments',body,{headers:{'Content-Type':'multipart/form-data'}});form.value=normalize(data.data);notice.value='File attached.'}catch(x){error.value=apiError(x)}finally{e.target.value=''}}
async function downloadAttachment(file){try{const{data}=await client.get('/purchase-invoices/'+form.value.id+'/attachments/'+file.id,{responseType:'blob'});downloadBlob(data,file.name)}catch(e){error.value=apiError(e)}}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function activityDetails(value){try{const x=typeof value==='string'?JSON.parse(value):value;return Array.isArray(x)?x.join(', '):Object.entries(x||{}).map(([k,v])=>k+': '+v).join(', ')}catch{return''}}
function resetFilters(){filters.value=initialFilters();page.value=1} function sortBy(key){sort.value={key,direction:sort.value.key===key?-sort.value.direction:1}}
async function exportExcel(){const{default:ExcelJS}=await import('exceljs'),book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Purchase Invoices');sheet.addRow(listColumns.map(x=>x.label));filteredRows.value.forEach(x=>sheet.addRow([x.invoice_no,dateLabel(x.invoice_date),x.po_no,dateLabel(x.purchase_order?.po_date),x.seller_no,x.seller_name,sellerBalance(x),Number(x.total),Number(x.paid),due(x),displayPaymentStatus(x),x.status,x.invoice_type]));sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF102A83'}};sheet.columns.forEach(x=>x.width=20);downloadBlob(new Blob([await book.xlsx.writeBuffer()]),'purchase-invoices.xlsx')}
function printPage(){window.print()} async function savePdf(){const{default:jsPDF}=await import('jspdf'),pdf=new jsPDF();let y=18;const text=(x,size=10)=>{pdf.setFontSize(size);pdf.splitTextToSize(String(x||'-'),180).forEach(line=>{if(y>278){pdf.addPage();y=18}pdf.text(line,15,y);y+=7})};text(view.value==='list'?'Purchase Invoice List':'Purchase Invoice '+form.value.invoice_no,18);if(view.value==='list')filteredRows.value.forEach(x=>text([x.invoice_no,dateLabel(x.invoice_date),x.seller_name,x.currency_code+' '+money(x.total),displayPaymentStatus(x)].join(' | ')));else{text('Seller: '+form.value.seller_name+' | PO: '+(form.value.po_no||'-'));text('Invoice date: '+dateLabel(form.value.invoice_date)+' | Due: '+dateLabel(form.value.due_date));form.value.items.forEach(x=>text(x.name+' | '+x.quantity+' '+x.uom+' | '+money(lineTotal(x))));text('Total: '+form.value.currency_code+' '+money(grandTotal.value),14);text('Paid: '+money(form.value.paid)+' | Balance: '+money(due(form.value)))}pdf.save(view.value==='list'?'purchase-invoices.pdf':(form.value.invoice_no||'purchase-invoice')+'.pdf')}
function emailInvoice(){const list=view.value==='list',subject=list?'Purchase Invoices':'Purchase Invoice '+form.value.invoice_no,body=list?filteredRows.value.map(x=>x.invoice_no+' - '+x.seller_name+': '+x.currency_code+' '+money(x.total)).join('\n'):subject+'\nSeller: '+form.value.seller_name+'\nPO: '+(form.value.po_no||'-')+'\nTotal: '+form.value.currency_code+' '+money(grandTotal.value)+'\nBalance: '+money(due(form.value));window.location.href='mailto:'+(list?'':encodeURIComponent(form.value.seller_details.email||''))+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)}
watch([filters,perPage],()=>page.value=1,{deep:true});watch(pageCount,x=>page.value=Math.min(page.value,x));onMounted(async()=>{busy.value=true;try{await Promise.all([load(),loadOptions()])}catch(e){error.value=apiError(e)}finally{busy.value=false}})
</script>

<style src="../assets/purchase-orders.css"></style>
