<template>
  <AccountLayout bare>
    <main class="po-page" :aria-busy="busy">
      <header class="po-header"><div class="po-heading"><Undo2 :size="30"/><div><h1>Purchase Return</h1><p>Purchase Invoice Returns</p></div></div><div v-if="view==='list'" class="po-header-search"><Search/><input v-model="filters.search" placeholder="Search seller, invoice or return no..." aria-label="Search returns"></div><div class="po-actions"><button v-if="view==='detail'" class="po-btn" @click="backToList"><ArrowLeft/> Back to list</button><span v-if="view==='detail'" class="po-pill" :class="slug(form.status)">{{ form.status }}</span></div></header>
      <div v-if="error" class="po-alert error">{{ error }}</div><div v-if="notice" class="po-alert success">{{ notice }}</div>

      <template v-if="view==='list'">
        <section class="po-metrics"><article v-for="card in metrics" :key="card.label" :class="card.tone"><component :is="card.icon" :size="30"/><div><h2>{{ card.label }}</h2><strong v-if="card.count">{{ card.count }}</strong><strong v-else>{{ negative(card.amount) }}</strong><b v-if="!card.count">{{ card.currency }}</b></div></article></section>
        <form class="po-filters" @submit.prevent="page=1"><label>Period<span class="po-date-range"><input v-model="filters.from" type="date"><input v-model="filters.to" type="date"></span></label><label>Seller<select v-model="filters.seller"><option value="">All Sellers</option><option v-for="name in sellerNames" :key="name">{{ name }}</option></select></label><label>Status<select v-model="filters.status"><option value="">All Status</option><option v-for="status in statuses" :key="status">{{ status }}</option></select></label><label>Refund Status<select v-model="filters.refund"><option value="">All Status</option><option v-for="status in refundStatuses" :key="status">{{ status }}</option></select></label><button class="po-btn primary"><Search/> Filter</button><button class="po-btn" type="button" @click="filters=initialFilters()"><RotateCcw/> Reset</button></form>
        <section class="po-list"><header class="po-section-head"><h2>Purchase Return List</h2><div class="po-actions"><button class="po-btn primary" @click="startNew"><Plus/> New Purchase Return</button><button class="po-btn green" @click="exportExcel"><Download/> Export</button></div></header><div class="po-table-scroll"><table class="po-list-table"><thead><tr><th>No</th><th>Sellers</th><th>Invoice No.</th><th>Invoice Date</th><th>Invoice Amount</th><th>Return No.</th><th>Return Date</th><th>Return Amount</th><th>Refunded</th><th>Status</th><th>Return Reason</th><th>Action</th></tr></thead><tbody><tr v-for="(row,index) in paginatedRows" :key="row.id"><td>{{ (page-1)*perPage+index+1 }}</td><td>{{ invoice(row).seller_name }}</td><td>{{ invoice(row).invoice_no }}</td><td>{{ dateLabel(invoice(row).invoice_date) }}</td><td>{{ money(invoice(row).total) }}</td><td><button class="po-link" @click="openReturn(row)">{{ row.return_no }}</button></td><td>{{ dateLabel(row.return_date) }}</td><td class="po-negative">{{ negative(row.total) }}</td><td class="po-positive">{{ money(row.refunded) }}</td><td><span class="po-pill" :class="slug(row.status)">{{ row.status }}</span><small class="po-payment-status">{{ row.refund_status }}</small></td><td>{{ row.reason }}</td><td><button class="po-btn compact" @click="openReturn(row)"><Eye/> View</button></td></tr><tr v-if="!paginatedRows.length"><td colspan="12" class="po-empty">No purchase returns found.</td></tr></tbody></table></div><footer class="po-pagination"><span>Showing {{ filteredRows.length?(page-1)*perPage+1:0 }} to {{ Math.min(page*perPage,filteredRows.length) }} of {{ filteredRows.length }} entries</span><div class="po-actions"><button class="po-icon" :disabled="page===1" @click="page--"><ChevronLeft/></button><b>{{ page }} / {{ pageCount }}</b><button class="po-icon" :disabled="page===pageCount" @click="page++"><ChevronRight/></button><select v-model.number="perPage"><option :value="15">15 / page</option><option :value="30">30 / page</option></select></div></footer></section>
      </template>

      <div v-else class="po-workspace">
        <section class="po-document"><header class="po-document-head"><div class="po-heading"><Undo2/><h2>Purchase Invoice Return</h2></div><div class="po-actions"><b>{{ form.return_no||'New return' }}</b><span class="po-pill" :class="slug(form.status)">{{ form.status }}</span><button class="po-icon" title="Print" @click="printPage"><Printer/></button><button class="po-icon" title="Email" @click="emailReturn"><Mail/></button></div></header>
          <div class="po-document-body"><div class="po-details-grid"><section><h3>Sellers</h3><Field label="Vendor ID" :model-value="source.seller_no"/><Field label="Company Name" :model-value="source.seller_name"/><Field v-for="field in sellerFields" :key="field.key" :label="field.label" :model-value="source.seller_details?.[field.key]" :multiline="field.key==='address'"/></section><section><h3>Requested By</h3><Field label="Department" :model-value="source.department"/><Field label="Contact Person" :model-value="source.requested_by"/><Field v-for="field in requesterFields" :key="field.key" :label="field.label" :model-value="source.requester_details?.[field.key]" :multiline="field.key==='address'"/><Field label="Project" :model-value="source.project"/></section><section><h3>Return Details</h3><div v-if="editing" class="po-field"><label>Invoice No.</label><i>:</i><select v-model="form.purchase_invoice_id" @change="applyInvoice"><option :value="null" disabled>Select invoice</option><option v-for="item in invoices" :key="item.id" :value="item.id">{{ item.invoice_no }} - {{ item.seller_name }}</option></select></div><Field v-else label="Invoice No." :model-value="source.invoice_no"/><Field label="PO No." :model-value="source.po_no"/><Field label="Return No." v-model="form.return_no" :editable="editing"/><Field label="Return Invoice Date" v-model="form.return_date" :editable="editing" type="date" :display-value="dateLabel(form.return_date)"/><Field label="Return Due Date" v-model="form.return_due_date" :editable="editing" type="date" :display-value="dateLabel(form.return_due_date)"/><Field label="Original Invoice Date" :model-value="dateLabel(source.invoice_date)"/><Field label="Original Delivery Date" :model-value="dateLabel(source.delivery_date)"/><Field label="Delivery Location" :model-value="source.delivery_location"/><Field label="Currency" :model-value="source.currency_code"/><Field label="Status" :model-value="form.status"/><Field label="Payment Term" :model-value="source.payment_term"/><Field label="Payment Method" :model-value="source.payment_method"/></section></div>
            <section class="po-items"><div v-if="editing" class="po-section-head"><h3>Returned Items / Services</h3><button class="po-btn compact" @click="restoreItems"><RotateCcw/> Restore invoice items</button></div><div class="po-table-scroll"><table><thead><tr><th>Item / Service</th><th>Item Code / SKU</th><th>UOM</th><th>Return Qty</th><th>Cost Rate</th><th>Sub Total</th><th>Sales Tax</th><th>Total</th><th v-if="editing"></th></tr></thead><tbody><tr v-for="(item,index) in form.items" :key="item.invoice_item_index"><td class="po-negative">{{ item.name }}</td><td>{{ item.code||'-' }}</td><td>{{ item.uom }}</td><td><input v-if="editing" v-model.number="item.quantity" type="number" min="0.01" :max="source.items?.[item.invoice_item_index]?.quantity" step="0.01" @input="recalculateTax(item)"><span v-else class="po-negative">({{ money(item.quantity) }})</span></td><td>{{ money(item.cost_rate) }}</td><td class="po-negative">{{ negative(lineSubtotal(item)) }}</td><td class="po-negative">{{ negative(item.sales_tax) }}</td><td class="po-negative">{{ negative(lineTotal(item)) }}</td><td v-if="editing"><button class="po-icon danger" title="Remove item" @click="form.items.splice(index,1)"><Trash2/></button></td></tr><tr v-if="!form.items.length"><td :colspan="editing?9:8" class="po-empty">Select an invoice or restore its items.</td></tr></tbody><tfoot><tr><th colspan="5">Total</th><th class="po-negative">{{ negative(subtotal) }}</th><th class="po-negative">{{ negative(taxTotal) }}</th><th class="po-negative">{{ negative(grandTotal) }}</th><th v-if="editing"></th></tr></tfoot></table></div></section>
            <div class="po-bottom-grid"><section><h3>Return Reason</h3><Field label="Reason" v-model="form.reason" :editable="editing" :options="reasons"/><textarea v-if="editing" v-model="form.notes" rows="4" placeholder="Return notes"/><p v-else class="po-terms">{{ form.notes||'-' }}</p><div class="po-metadata"><Field label="Last modification" :model-value="dateTimeLabel(form.updated_at)"/><Field label="Created By" :model-value="form.creator?.name"/><Field label="Created Date" :model-value="dateTimeLabel(form.created_at)"/></div></section><section><h3>Delivery Information</h3><Field label="Original Delivery Date" :model-value="dateLabel(source.delivery_date)"/><Field label="Delivery Location" :model-value="source.delivery_location"/><Field label="Delivery Contact" :model-value="source.delivery_details?.contact_person"/><Field label="Delivery Phone" :model-value="source.delivery_details?.phone"/><Field label="Delivery Instructions" :model-value="source.notes" multiline/></section><section class="po-totals"><Field label="Sub Total" :model-value="negative(subtotal)"/><Field label="Sales Tax (Total)" :model-value="negative(taxTotal)"/><Field label="Refunded" :model-value="money(form.refunded)"/><div><span>Grand Total ({{ source.currency_code||'CAD' }})</span><strong class="po-negative">{{ negative(grandTotal) }}</strong></div><div><span>Refund Balance</span><strong>{{ money(refundBalance) }}</strong></div></section></div><section v-if="form.attachments.length" class="po-attachments"><h3>Attachments</h3><button v-for="file in form.attachments" :key="file.id" class="po-btn compact" @click="downloadAttachment(file)"><Paperclip/> {{ file.name }}</button></section>
          </div><footer class="po-document-footer"><div class="po-actions"><button class="po-btn" @click="startNew"><Plus/> New</button><button class="po-btn" :disabled="editing||Number(form.refunded)>0" @click="editing=true"><Pencil/> Edit</button><button class="po-btn danger" :disabled="!form.id||Number(form.refunded)>0" @click="deleteReturn"><Trash2/> Delete</button><button class="po-btn primary" :disabled="!editing" @click="saveReturn"><Save/> Save</button><button v-if="editing" class="po-btn" @click="cancelEdit"><X/> Cancel</button><button class="po-btn" @click="printPage"><Printer/> Print</button><button class="po-btn" @click="savePdf"><FileDown/> Save PDF</button><button class="po-btn" @click="emailReturn"><Mail/> Email</button><button class="po-btn green" :disabled="!canDecide" @click="workflow('approve')"><Check/> Approve Return</button><button class="po-btn danger" :disabled="!canDecide" @click="workflow('reject')"><X/> Reject</button></div><div class="po-actions"><button class="po-btn green" :disabled="!canRefund" @click="openRefund"><BadgeDollarSign/> Receive Refund</button><button class="po-btn" :disabled="!form.id" @click="fileInput.click()"><Paperclip/> Attach File</button><input ref="fileInput" class="po-hidden" type="file" @change="uploadAttachment"><button class="po-btn" :disabled="!form.id" @click="modal='audit'"><History/> View Audit Log</button><button class="po-btn" :disabled="!canSubmit" @click="workflow('submit')"><Send/> Send for Approval</button><button class="po-btn green" @click="exportExcel"><FileSpreadsheet/> Export Excel</button></div></footer>
        </section>
        <aside class="po-sidebar"><section><h3>Transaction Tracker</h3><div class="po-table-scroll"><table class="po-tracker"><thead><tr><th>Doc. Type</th><th>No.</th><th>Date</th><th>Total</th></tr></thead><tbody><tr><td>Purchase Order</td><td>{{ source.po_no||'-' }}</td><td>{{ dateLabel(source.purchase_order?.po_date) }}</td><td>{{ money(source.total) }}</td></tr><tr><td>Purchase Invoice</td><td>{{ source.invoice_no||'-' }}</td><td>{{ dateLabel(source.invoice_date) }}</td><td>{{ money(source.total) }}</td></tr><tr><td>Purchase Invoice Return</td><td>{{ form.return_no||'-' }}</td><td>{{ dateLabel(form.return_date) }}</td><td class="po-negative">{{ negative(grandTotal) }}</td></tr><tr v-for="refund in form.refunds" :key="refund.id"><td>Refund</td><td>{{ refund.refund_no }}</td><td>{{ dateLabel(refund.refund_date) }}</td><td>{{ money(refund.amount) }}</td></tr></tbody><tfoot><tr><th>Balance</th><th colspan="2">{{ source.currency_code }}</th><th>{{ money(refundBalance) }}</th></tr></tfoot></table></div></section><section><h3>Quick Reports</h3><button v-for="report in reports" :key="report.label" class="po-report-link"><span>{{ report.label }}</span><b>{{ report.count }}</b></button></section><section><h3>Current Return Details</h3><Field label="Invoice No." :model-value="source.invoice_no"/><Field label="PO No." :model-value="source.po_no"/><Field label="Return No." :model-value="form.return_no"/><Field label="Return Date" :model-value="dateLabel(form.return_date)"/><Field label="Return Due Date" :model-value="dateLabel(form.return_due_date)"/><Field label="Currency" :model-value="source.currency_code"/><Field label="Status" :model-value="form.status"/><Field label="Refund Status" :model-value="form.refund_status"/><Field label="Payment Term" :model-value="source.payment_term"/></section></aside>
      </div>

      <div v-if="modal" class="po-modal-backdrop" @click.self="modal=''"> <section class="po-modal" role="dialog"><header><h2>{{ modal==='refund'?'Receive Seller Refund':'Purchase Return Audit Log' }}</h2><button class="po-icon" @click="modal=''"><X/></button></header><div v-if="modalError" class="po-alert error">{{ modalError }}</div><form v-if="modal==='refund'" @submit.prevent="receiveRefund"><Field label="Refund No." v-model="refundForm.refund_no" editable/><Field label="Refund Date" v-model="refundForm.refund_date" editable type="date"/><Field label="Amount" v-model="refundForm.amount" editable type="number"/><Field label="Method" v-model="refundForm.method" editable/><Field label="Reference" v-model="refundForm.reference" editable/><Field label="Notes" v-model="refundForm.notes" editable multiline/><button class="po-btn green"><BadgeDollarSign/> Receive Refund</button></form><div v-else class="po-table-scroll"><table><thead><tr><th>Date / Time</th><th>User</th><th>Action</th><th>Details</th></tr></thead><tbody><tr v-for="entry in form.activities" :key="entry.id"><td>{{ dateTimeLabel(entry.created_at) }}</td><td>{{ entry.actor }}</td><td>{{ entry.action }}</td><td>{{ activityDetails(entry.changes) }}</td></tr></tbody></table></div></section></div>
    </main>
  </AccountLayout>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { Undo2, Search, Plus, RotateCcw, Download, Printer, Mail, ArrowLeft, Eye, ChevronLeft, ChevronRight, Trash2, Pencil, Save, X, FileDown, Check, BadgeDollarSign, Paperclip, History, Send, FileSpreadsheet, WalletCards, CircleDollarSign, BadgeCheck, Clock } from 'lucide-vue-next'
import AccountLayout from '../components/AccountLayout.vue'; import Field from '../components/PurchaseOrderField.vue'; import client from '../api/client'
import { roundMoney, lineSubtotal, lineTotal, today, money, dateLabel, dateTimeLabel } from '../utils/purchaseOrders'
const rows=ref([]),invoices=ref([]),view=ref('list'),form=ref({}),editing=ref(false),busy=ref(false),error=ref(''),notice=ref(''),modal=ref(''),modalError=ref(''),refundForm=ref({}),fileInput=ref(null),page=ref(1),perPage=ref(15)
const statuses=['Draft','Pending','Returned','Rejected'],refundStatuses=['Unpaid','Partial','Paid'],reasons=['Material defect','Wrong item delivered','Quality issue','Damaged in transit','Over order','Not as specified','Received extra items','Changed requirement']
const sellerFields=[{key:'contact_person',label:'Contact Person'},{key:'phone',label:'Phone'},{key:'email',label:'Email'},{key:'address',label:'Address'},{key:'website',label:'Website'},{key:'tax_number',label:'Tax Number'},{key:'vendor_category',label:'Vendor Category'}],requesterFields=[{key:'phone',label:'Phone'},{key:'email',label:'Email'},{key:'company_name',label:'Company Name'},{key:'address',label:'Address'}]
const initialFilters=()=>({search:'',from:'',to:'',seller:'',status:'',refund:''}),filters=ref(initialFilters()),blank=()=>({id:null,return_no:'',purchase_invoice_id:null,return_date:today(),return_due_date:'',status:'Draft',refund_status:'Unpaid',reason:'',refunded:0,items:[],notes:'',refunds:[],activities:[],attachments:[],purchase_invoice:null})
const invoice=row=>row.purchase_invoice||{},source=computed(()=>invoice(form.value)),slug=x=>String(x||'').toLowerCase().replace(/\s+/g,'-'),negative=x=>'('+money(x)+')'
const sellerNames=computed(()=>[...new Set(rows.value.map(x=>invoice(x).seller_name).filter(Boolean))].sort()),filteredRows=computed(()=>rows.value.filter(row=>{const f=filters.value,i=invoice(row),q=f.search.toLowerCase(),d=String(row.return_date).slice(0,10);return(!q||[row.return_no,i.invoice_no,i.po_no,i.seller_name].some(x=>String(x||'').toLowerCase().includes(q)))&&(!f.seller||i.seller_name===f.seller)&&(!f.status||row.status===f.status)&&(!f.refund||row.refund_status===f.refund)&&(!f.from||d>=f.from)&&(!f.to||d<=f.to)})),pageCount=computed(()=>Math.max(1,Math.ceil(filteredRows.value.length/perPage.value))),paginatedRows=computed(()=>filteredRows.value.slice((page.value-1)*perPage.value,page.value*perPage.value))
const totals=computed(()=>({amount:filteredRows.value.reduce((s,x)=>s+Number(x.total),0),refunded:filteredRows.value.reduce((s,x)=>s+Number(x.refunded),0)})),metrics=computed(()=>[{label:'Total Returns',count:filteredRows.value.length,icon:WalletCards,tone:'blue'},{label:'Total Return Amount',amount:totals.value.amount,currency:'CAD',icon:CircleDollarSign,tone:'red'},{label:'Total Refunded Amount',amount:totals.value.refunded,currency:'CAD',icon:BadgeCheck,tone:'green'},{label:'Total Unpaid (Net Balance)',amount:totals.value.amount-totals.value.refunded,currency:'CAD',icon:Clock,tone:'amber'}])
const subtotal=computed(()=>roundMoney((form.value.items||[]).reduce((s,x)=>s+lineSubtotal(x),0))),taxTotal=computed(()=>roundMoney((form.value.items||[]).reduce((s,x)=>s+Number(x.sales_tax||0),0))),grandTotal=computed(()=>roundMoney(subtotal.value+taxTotal.value)),refundBalance=computed(()=>roundMoney(grandTotal.value-Number(form.value.refunded||0)))
const canSubmit=computed(()=>form.value.id&&!editing.value&&form.value.status==='Draft'),canDecide=computed(()=>form.value.id&&!editing.value&&['Draft','Pending'].includes(form.value.status)),canRefund=computed(()=>form.value.id&&!editing.value&&form.value.status==='Returned'&&refundBalance.value>0),reports=computed(()=>[{label:'Purchase Documents',count:invoices.value.length+rows.value.length},{label:'Refund List',count:rows.value.reduce((s,x)=>s+(x.refunds?.length||0),0)},{label:'Unpaid Returns',count:rows.value.filter(x=>Number(x.total)>Number(x.refunded)).length},{label:'Return Aging Report',count:rows.value.filter(x=>x.return_due_date&&String(x.return_due_date).slice(0,10)<today()&&Number(x.total)>Number(x.refunded)).length},{label:'Account Statement',count:rows.value.length}])
const apiError=e=>Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||e.message||'Unable to complete request.'
async function fetchAll(url){let p=1,last=1,out=[];do{const{data}=await client.get(url,{params:{per_page:100,page:p}}),body=data.data;out.push(...(body?.data||body||[]));last=body?.last_page||data.meta?.last_page||1;p++}while(p<=last);return out}
async function load(){[rows.value,invoices.value]=await Promise.all([fetchAll('/purchase-returns'),fetchAll('/purchase-invoices')])}
function normalize(x){const b=blank();return{...b,...x,purchase_invoice_id:x.purchase_invoice_id?Number(x.purchase_invoice_id):null,return_date:String(x.return_date||today()).slice(0,10),return_due_date:String(x.return_due_date||'').slice(0,10),items:(x.items||[]).map(i=>{const original=x.purchase_invoice?.items?.[i.invoice_item_index]||i;return{...i,original_quantity:Number(original.quantity||i.quantity),original_sales_tax:Number(original.sales_tax||i.sales_tax||0)}}),refunds:x.refunds||[],activities:x.activities||[],attachments:x.attachments||[]}}
function startNew(){form.value=blank();editing.value=true;view.value='detail';error.value='';notice.value=''} async function openReturn(row){busy.value=true;try{const{data}=await client.get('/purchase-returns/'+row.id);form.value=normalize(data.data);editing.value=false;view.value='detail'}catch(e){error.value=apiError(e)}finally{busy.value=false}} function backToList(){view.value='list';editing.value=false} async function cancelEdit(){form.value.id?await openReturn(form.value):backToList()}
function returnItems(inv){return(inv.items||[]).map((x,index)=>({invoice_item_index:index,name:x.name,code:x.code||'',uom:x.uom||'PCS',quantity:Number(x.quantity),original_quantity:Number(x.quantity),cost_rate:Number(x.cost_rate),sales_tax:Number(x.sales_tax||0),original_sales_tax:Number(x.sales_tax||0)}))} function recalculateTax(item){item.sales_tax=roundMoney(item.original_sales_tax*(Number(item.quantity)||0)/item.original_quantity)} function applyInvoice(){const inv=invoices.value.find(x=>x.id===Number(form.value.purchase_invoice_id));if(!inv)return;form.value={...form.value,purchase_invoice:inv,items:returnItems(inv),return_due_date:inv.due_date?String(inv.due_date).slice(0,10):''}} function restoreItems(){if(source.value.id)form.value.items=returnItems(source.value)}
async function saveReturn(){if(!form.value.purchase_invoice_id||!form.value.reason||!form.value.items.length){error.value='Select an invoice, return reason, and at least one item.';return}busy.value=true;try{const{data}=form.value.id?await client.put('/purchase-returns/'+form.value.id,form.value):await client.post('/purchase-returns',form.value);form.value=normalize(data.data);editing.value=false;await load();notice.value='Purchase return saved.'}catch(e){error.value=apiError(e)}finally{busy.value=false}}
async function workflow(action){busy.value=true;try{const{data}=await client.post('/purchase-returns/'+form.value.id+'/workflow',{action});form.value=normalize(data.data);await load();notice.value='Purchase return '+form.value.status.toLowerCase()+'.'}catch(e){error.value=apiError(e)}finally{busy.value=false}} async function deleteReturn(){if(!confirm('Delete '+form.value.return_no+'?'))return;try{await client.delete('/purchase-returns/'+form.value.id);await load();backToList();notice.value='Purchase return deleted.'}catch(e){error.value=apiError(e)}}
function openRefund(){refundForm.value={refund_no:'RFND-'+String(Date.now()).slice(-6),refund_date:today(),amount:refundBalance.value,method:source.value.payment_method||'',reference:'',notes:''};modal.value='refund'} async function receiveRefund(){busy.value=true;try{const{data}=await client.post('/purchase-returns/'+form.value.id+'/refunds',refundForm.value);form.value=normalize(data.data);await load();modal.value='';notice.value='Seller refund received.'}catch(e){modalError.value=apiError(e)}finally{busy.value=false}}
async function uploadAttachment(e){const file=e.target.files[0];if(!file)return;const body=new FormData();body.append('file',file);try{const{data}=await client.post('/purchase-returns/'+form.value.id+'/attachments',body,{headers:{'Content-Type':'multipart/form-data'}});form.value=normalize(data.data)}catch(x){error.value=apiError(x)}finally{e.target.value=''}} async function downloadAttachment(file){const{data}=await client.get('/purchase-returns/'+form.value.id+'/attachments/'+file.id,{responseType:'blob'});downloadBlob(data,file.name)} function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function activityDetails(value){try{const x=typeof value==='string'?JSON.parse(value):value;return Object.entries(x||{}).map(([k,v])=>k+': '+v).join(', ')}catch{return''}} function printPage(){window.print()} async function exportExcel(){const{default:ExcelJS}=await import('exceljs'),book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Purchase Returns');sheet.addRow(['Seller','Invoice No.','Invoice Date','Return No.','Return Date','Return Amount','Refunded','Status','Reason']);filteredRows.value.forEach(x=>{const i=invoice(x);sheet.addRow([i.seller_name,i.invoice_no,dateLabel(i.invoice_date),x.return_no,dateLabel(x.return_date),-Number(x.total),Number(x.refunded),x.status,x.reason])});sheet.getRow(1).font={bold:true};sheet.columns.forEach(x=>x.width=22);downloadBlob(new Blob([await book.xlsx.writeBuffer()]),'purchase-returns.xlsx')}
async function savePdf(){const{default:jsPDF}=await import('jspdf'),pdf=new jsPDF();pdf.setFontSize(18);pdf.text(view.value==='list'?'Purchase Return List':'Purchase Invoice Return '+form.value.return_no,15,18);pdf.setFontSize(10);let y=30;(view.value==='list'?filteredRows.value:form.value.items).forEach(x=>{const text=view.value==='list'?[invoice(x).seller_name,x.return_no,dateLabel(x.return_date),negative(x.total)].join(' | '):[x.name,x.quantity+' '+x.uom,negative(lineTotal(x))].join(' | ');pdf.text(text,15,y);y+=7;if(y>280){pdf.addPage();y=18}});pdf.save(view.value==='list'?'purchase-returns.pdf':(form.value.return_no||'purchase-return')+'.pdf')} function emailReturn(){const subject='Purchase Return '+(form.value.return_no||''),body=subject+'\nInvoice: '+(source.value.invoice_no||'')+'\nSeller: '+(source.value.seller_name||'')+'\nReturn total: '+negative(grandTotal.value);window.location.href='mailto:'+encodeURIComponent(source.value.seller_details?.email||'')+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)}
watch([filters,perPage],()=>page.value=1,{deep:true});watch(pageCount,x=>page.value=Math.min(page.value,x));onMounted(async()=>{busy.value=true;try{await load()}catch(e){error.value=apiError(e)}finally{busy.value=false}})
</script>
<style src="../assets/purchase-orders.css"></style>
