<template>
  <AccountLayout bare>
    <main class="po-page sr-page" :aria-busy="busy">
      <header class="po-header"><div class="po-heading"><Undo2/><div><h1>Sales Invoice Return</h1><p>Accounting / Sales</p></div></div><div v-if="view==='list'" class="po-header-search"><Search/><input v-model="filters.search" placeholder="Search customer, invoice or return no."></div><div class="po-actions"><button v-if="view==='detail'" class="po-btn" @click="back"><ArrowLeft/> Back to list</button><span v-if="view==='detail'" class="po-pill" :class="slug(form.status)">{{ form.status }}</span></div></header>
      <div v-if="error" class="po-alert error">{{ error }}</div><div v-if="notice" class="po-alert success">{{ notice }}</div>

      <template v-if="view==='list'">
        <section class="po-metrics"><article v-for="card in metrics" :key="card.label" :class="card.tone"><component :is="card.icon"/><div><h2>{{ card.label }}</h2><strong v-if="card.count!==undefined">{{ card.count }}</strong><strong v-else>{{ negative(card.amount) }}</strong><b v-if="card.currency">{{ card.currency }}</b></div></article></section>
        <form class="po-filters" @submit.prevent="page=1"><label>From Date<input v-model="filters.from" type="date"></label><label>To Date<input v-model="filters.to" type="date"></label><label>Customer<select v-model="filters.customer"><option value="">All Customers</option><option v-for="name in customerNames" :key="name">{{ name }}</option></select></label><label>Status<select v-model="filters.status"><option value="">All Status</option><option v-for="x in statuses" :key="x">{{ x }}</option></select></label><label>Refund Status<select v-model="filters.refund"><option value="">All Status</option><option>Unpaid</option><option>Partial</option><option>Paid</option></select></label><button class="po-btn primary"><Search/> Filter</button><button class="po-btn" type="button" @click="filters=initialFilters()"><RotateCcw/> Reset</button></form>
        <section class="po-list"><header class="po-section-head"><h2>Sales Return List</h2><div class="po-actions"><button class="po-btn primary" @click="startNew"><Plus/> New Sales Return</button><button class="po-btn green" @click="exportExcel"><Download/> Export</button></div></header><div class="po-table-scroll"><table class="po-list-table"><thead><tr><th>No</th><th>Customer</th><th>Invoice No.</th><th>Invoice Date</th><th>Invoice Amount</th><th>Return No.</th><th>Return Date</th><th>Return Amount</th><th>Refunded</th><th>Status</th><th>Reason</th><th>Action</th></tr></thead><tbody><tr v-for="(row,index) in paginated" :key="row.id"><td>{{ (page-1)*perPage+index+1 }}</td><td>{{ customer(row).name||'-' }}</td><td>{{ invoice(row).invoice_no }}</td><td>{{ dateLabel(invoice(row).invoice_date) }}</td><td>{{ money(invoice(row).total) }}</td><td><button class="po-link" @click="openReturn(row)">{{ row.return_no }}</button></td><td>{{ dateLabel(row.return_date) }}</td><td class="po-negative">{{ negative(row.total) }}</td><td>{{ money(row.refunded) }}</td><td><span class="po-pill" :class="slug(row.status)">{{ row.status }}</span><small class="po-payment-status">{{ row.refund_status }}</small></td><td>{{ row.reason }}</td><td><button class="po-btn compact" @click="openReturn(row)"><Eye/> View</button></td></tr><tr v-if="!paginated.length"><td colspan="12" class="po-empty">No sales returns found.</td></tr></tbody></table></div><footer class="po-pagination"><span>Showing {{ filtered.length?(page-1)*perPage+1:0 }} to {{ Math.min(page*perPage,filtered.length) }} of {{ filtered.length }}</span><div class="po-actions"><button class="po-icon" :disabled="page===1" @click="page--"><ChevronLeft/></button><b>{{ page }} / {{ pageCount }}</b><button class="po-icon" :disabled="page===pageCount" @click="page++"><ChevronRight/></button></div></footer></section>
      </template>

      <div v-else class="po-workspace">
        <section class="po-document"><header class="po-document-head"><div class="po-heading"><Undo2/><h2>Sales Invoice Return</h2></div><div class="po-actions"><b>{{ form.return_no||'New return' }}</b><span class="po-pill" :class="slug(form.status)">{{ form.status }}</span><button class="po-icon" title="Print" @click="printPage"><Printer/></button><button class="po-icon" title="Preview" @click="printPage"><Eye/></button><button class="po-icon" title="Email" @click="emailReturn"><Mail/></button></div></header>
          <div class="po-document-body">
            <div class="sr-info-grid">
              <section><h3>1. Customer Information</h3><Field label="Customer ID" :model-value="customer().customer_no"/><Field label="Customer Name" :model-value="customer().name"/><Field label="Contact Person" :model-value="customer().contact_person"/><Field label="Phone" :model-value="customer().phone"/><Field label="Email" :model-value="customer().email"/><Field label="Address" :model-value="customer().address" multiline/><hr><Field label="Customer Balance" :model-value="currency(customer().balance)"/><Field label="Customer Credit Limit" :model-value="currency(customer().credit_limit)"/><Field label="Available Credit" :model-value="currency(availableCredit)"/></section>
              <section><h3>2. Return Information</h3><Field label="Return No." v-model="form.return_no" :editable="editing"/><Field label="Return Date" v-model="form.return_date" :editable="editing" type="date" :display-value="dateLabel(form.return_date)"/><div v-if="editing" class="po-field"><label>Invoice No.</label><i>:</i><select v-model="form.sales_invoice_id" @change="applyInvoice"><option :value="null" disabled>Select invoice</option><option v-for="x in eligibleInvoices" :key="x.id" :value="x.id">{{ x.invoice_no }} - {{ x.customer_details?.name }}</option></select></div><Field v-else label="Invoice No." :model-value="source.invoice_no"/><Field label="Invoice Date" :model-value="dateLabel(source.invoice_date)"/><Field label="Customer PO No." :model-value="source.customer_po_no"/><Field label="Salesperson" :model-value="source.salesperson"/><Field label="Sales Department" :model-value="source.department"/><Field label="Currency" :model-value="source.currency_code"/><Field label="Exchange Rate" :model-value="source.exchange_rate"/><Field label="Return Reason" v-model="form.reason" :editable="editing" :options="reasons"/><Field label="Sales Channel" :model-value="source.sales_channel"/></section>
              <section><h3>3. Return & Other Details</h3><Field label="Warehouse" v-model="form.warehouse" :editable="editing" :options="warehouses"/><Field label="Return Type" v-model="form.return_type" :editable="editing" :options="returnTypes"/><Field label="Shipping Method" v-model="form.shipping_method" :editable="editing"/><Field label="Expected Pickup Date" v-model="form.expected_pickup_date" :editable="editing" type="date" :display-value="dateLabel(form.expected_pickup_date)"/><Field label="Payment Terms" :model-value="source.payment_terms"/><Field label="Reference" v-model="form.reference" :editable="editing"/><Field label="Remarks / Memo" v-model="form.notes" :editable="editing" multiline/></section>
            </div>

            <section class="po-items"><div class="po-section-head"><h3>4. Returned Item / Service Details</h3><button v-if="editing" class="po-btn compact" @click="restoreItems"><RotateCcw/> Restore invoice items</button></div><div class="po-table-scroll"><table><thead><tr><th>#</th><th>Item / Service</th><th>Description</th><th>Warehouse</th><th>Returned Qty</th><th>UOM</th><th>Unit Price</th><th>Discount (%)</th><th>Tax</th><th>Amount</th><th v-if="editing">Action</th></tr></thead><tbody><tr v-for="(item,index) in form.items" :key="item.invoice_item_index"><td>{{ index+1 }}</td><td>{{ item.name }}</td><td>{{ item.description||'-' }}</td><td>{{ form.warehouse||'-' }}</td><td><input v-if="editing" v-model.number="item.quantity" type="number" min="0.01" :max="source.items?.[item.invoice_item_index]?.quantity" step="0.01"><span v-else class="po-negative">({{ money(item.quantity) }})</span></td><td>{{ item.uom }}</td><td class="po-negative">{{ negative(item.unit_price) }}</td><td>{{ money(item.discount) }}</td><td>{{ money(item.tax_rate) }}%</td><td class="po-negative">{{ negative(itemTotal(item)) }}</td><td v-if="editing"><button class="po-icon danger" title="Remove item" @click="form.items.splice(index,1)"><Trash2/></button></td></tr><tr v-if="!form.items.length"><td :colspan="editing?11:10" class="po-empty">Select an invoice to load its items.</td></tr></tbody></table></div></section>

            <div class="sr-bottom-grid"><section><h3>5. Terms & Conditions</h3><textarea v-if="editing" v-model="form.terms" rows="7" placeholder="Return terms and conditions"></textarea><p v-else class="po-terms">{{ form.terms||'-' }}</p><div v-if="form.attachments.length" class="po-attachments"><button v-for="file in form.attachments" :key="file.id" class="po-btn compact" @click="downloadAttachment(file)"><Paperclip/> {{ file.name }}</button></div></section><section><h3>6. Tax Summary</h3><div class="po-table-scroll"><table><thead><tr><th>Tax Type</th><th>Rate</th><th>Taxable Amount</th><th>Tax Amount</th></tr></thead><tbody><tr><td>Sales Tax</td><td>{{ averageTax }}%</td><td class="po-negative">{{ negative(taxable) }}</td><td class="po-negative">{{ negative(taxTotal) }}</td></tr></tbody><tfoot><tr><th colspan="3">Total Tax</th><th class="po-negative">{{ negative(taxTotal) }}</th></tr></tfoot></table></div></section><section><h3>7. Approval Status</h3><div class="sr-steps"><span v-for="step in approvalSteps" :key="step" :class="{current:step===form.status,done:isStepDone(step)}"><Check v-if="isStepDone(step)"/><i></i><b>{{ step }}</b></span></div><Field label="Approved By" :model-value="form.status==='Returned'?(source.approved_by||form.creator?.name):'-'"/><Field label="Approved Date" :model-value="form.status==='Returned'?dateLabel(form.updated_at):'-'"/></section><section><h3>8. Customer Signature</h3><div class="sr-signature">Authorized signature</div><Field label="Authorized By" model-value=""/><Field label="Date" model-value=""/></section></div>
          </div>
          <footer class="po-document-footer"><div class="po-actions"><button class="po-btn" @click="startNew"><Plus/> New</button><button class="po-btn" :disabled="editing||Number(form.refunded)>0" @click="editing=true"><Pencil/> Edit</button><button class="po-btn danger" :disabled="!form.id||Number(form.refunded)>0" @click="deleteReturn"><Trash2/> Delete</button><button class="po-btn primary" :disabled="!editing" @click="saveReturn"><Save/> Save</button><button v-if="editing" class="po-btn" @click="cancelEdit"><X/> Cancel</button><button class="po-btn" @click="savePdf"><FileDown/> Save PDF</button><button class="po-btn" @click="printPage"><Printer/> Preview</button><button class="po-btn" @click="emailReturn"><Mail/> Email</button><button class="po-btn" :disabled="!form.id" @click="fileInput.click()"><Paperclip/> Attach File</button><input ref="fileInput" class="po-hidden" type="file" @change="uploadAttachment"><button class="po-btn amber" :disabled="!canSubmit" @click="workflow('submit')"><Send/> Send for Approval</button><button class="po-btn green" :disabled="!canDecide" @click="workflow('approve')"><Check/> Approve</button><button class="po-btn green" :disabled="!canRefund" @click="openRefund"><BadgeDollarSign/> Customer Refund</button></div></footer>
        </section>

        <aside class="po-sidebar"><section><h3>Transaction Tracker</h3><div class="po-table-scroll"><table class="po-tracker"><thead><tr><th>Doc. Type</th><th>No.</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr><td>Sales Estimate</td><td>{{ source.sales_order?.estimation?.estimation_no||'-' }}</td><td>{{ dateLabel(source.sales_order?.estimation?.issue_date) }}</td><td>{{ money(source.total) }}</td><td>Converted</td></tr><tr><td>Sales Order</td><td>{{ source.sales_order?.order_no||'-' }}</td><td>{{ dateLabel(source.sales_order?.order_date) }}</td><td>{{ money(source.total) }}</td><td>Completed</td></tr><tr><td>Sales Invoice</td><td>{{ source.invoice_no||'-' }}</td><td>{{ dateLabel(source.invoice_date) }}</td><td>{{ money(source.total) }}</td><td>{{ source.status||'-' }}</td></tr><tr><td>Sales Invoice Return</td><td>{{ form.return_no||'-' }}</td><td>{{ dateLabel(form.return_date) }}</td><td class="po-negative">{{ negative(grandTotal) }}</td><td>{{ form.status }}</td></tr></tbody></table></div></section><section><h3>Return Summary</h3><Field label="Sub Total" :model-value="negative(subtotal)"/><Field label="Discount Amount" :model-value="negative(discountTotal)"/><Field label="Taxable Amount" :model-value="negative(taxable)"/><Field label="Total Tax" :model-value="negative(taxTotal)"/><div class="sr-grand"><span>Grand Total ({{ source.currency_code||'USD' }})</span><strong>{{ negative(grandTotal) }}</strong></div></section><section><h3>Payment Status</h3><span class="sr-payment" :class="slug(form.refund_status)">{{ form.refund_status }}</span><Field label="Refunded Amount" :model-value="money(form.refunded)"/><Field label="Balance Due" :model-value="negative(refundBalance)"/></section><section><h3>Credit Information</h3><Field label="Customer Credit Limit" :model-value="currency(customer().credit_limit)"/><Field label="Available Credit" :model-value="currency(availableCredit)"/><Field label="Credit Usage" :model-value="creditUsage+'%'"/></section><section><h3>Return Details</h3><Field label="Project Name" :model-value="source.job_site_name"/><Field label="Project Site Address" :model-value="source.job_site_address" multiline/><Field label="Tax Registration No." :model-value="source.tax_registration_no"/><Field label="Internal Notes" :model-value="source.internal_notes" multiline/><Field label="Prepared By" :model-value="form.creator?.name"/><Field label="Approved By" :model-value="source.approved_by"/></section></aside>
      </div>

      <div v-if="modal==='refund'" class="po-modal-backdrop" @click.self="modal=''"> <section class="po-modal" role="dialog"><header><h2>Record Customer Refund</h2><button class="po-icon" @click="modal=''"> <X/></button></header><form @submit.prevent="receiveRefund"><Field label="Refund No." v-model="refundForm.refund_no" editable/><Field label="Refund Date" v-model="refundForm.refund_date" editable type="date"/><Field label="Amount" v-model="refundForm.amount" editable type="number"/><Field label="Method" v-model="refundForm.method" editable/><Field label="Reference" v-model="refundForm.reference" editable/><Field label="Notes" v-model="refundForm.notes" editable multiline/><button class="po-btn green"><BadgeDollarSign/> Record Refund</button></form></section></div>
    </main>
  </AccountLayout>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { Undo2, Search, Plus, RotateCcw, Download, Printer, Mail, ArrowLeft, Eye, ChevronLeft, ChevronRight, Trash2, Pencil, Save, X, FileDown, Check, BadgeDollarSign, Paperclip, Send, WalletCards, CircleDollarSign, BadgeCheck, Clock } from 'lucide-vue-next'
import AccountLayout from '../components/AccountLayout.vue'; import Field from '../components/PurchaseOrderField.vue'; import client from '../api/client'
import { roundMoney, today, money, dateLabel } from '../utils/purchaseOrders'

const rows=ref([]),invoices=ref([]),view=ref('list'),form=ref({}),editing=ref(false),busy=ref(false),error=ref(''),notice=ref(''),modal=ref(''),refundForm=ref({}),fileInput=ref(null),page=ref(1),perPage=ref(15)
const statuses=['Draft','Pending','Returned','Rejected'],reasons=['Damaged items','Wrong item supplied','Quality issue','Incorrect size','Customer cancellation','Not as described','Excess quantity'],warehouses=['Main Warehouse','Site Warehouse','Returns Warehouse'],returnTypes=['Goods Return','Service Reversal','Exchange']
const initialFilters=()=>({search:'',from:'',to:'',customer:'',status:'',refund:''}),filters=ref(initialFilters())
const blank=()=>({id:null,return_no:'',sales_invoice_id:null,return_date:today(),expected_pickup_date:'',status:'Draft',refund_status:'Unpaid',reason:'',return_type:'Goods Return',warehouse:'Main Warehouse',shipping_method:'',reference:'',items:[],terms:'Goods returned must be in original condition with all original packaging and accessories.',notes:'',refunded:0,refunds:[],activities:[],attachments:[],sales_invoice:null})
const invoice=row=>row?.sales_invoice||{},source=computed(()=>invoice(form.value)),customer=row=>invoice(row||form.value).customer_details||{},slug=x=>String(x||'').toLowerCase().replace(/\s+/g,'-'),negative=x=>'('+money(x)+')',currency=x=>money(x)+' '+(source.value.currency_code||'USD')
const eligibleInvoices=computed(()=>invoices.value.filter(x=>['Open','Paid'].includes(x.status))),customerNames=computed(()=>[...new Set(rows.value.map(x=>customer(x).name).filter(Boolean))].sort())
const filtered=computed(()=>rows.value.filter(row=>{const f=filters.value,i=invoice(row),q=f.search.toLowerCase(),d=String(row.return_date||'').slice(0,10);return(!q||[row.return_no,i.invoice_no,customer(row).name].some(x=>String(x||'').toLowerCase().includes(q)))&&(!f.customer||customer(row).name===f.customer)&&(!f.status||row.status===f.status)&&(!f.refund||row.refund_status===f.refund)&&(!f.from||d>=f.from)&&(!f.to||d<=f.to)})),pageCount=computed(()=>Math.max(1,Math.ceil(filtered.value.length/perPage.value))),paginated=computed(()=>filtered.value.slice((page.value-1)*perPage.value,page.value*perPage.value))
const lineBase=x=>Number(x.quantity||0)*Number(x.unit_price||0),lineDiscount=x=>lineBase(x)*Number(x.discount||0)/100,lineTax=x=>(lineBase(x)-lineDiscount(x))*Number(x.tax_rate||0)/100,itemTotal=x=>roundMoney(lineBase(x)-lineDiscount(x)+lineTax(x))
const subtotal=computed(()=>roundMoney((form.value.items||[]).reduce((s,x)=>s+lineBase(x),0))),discountTotal=computed(()=>roundMoney((form.value.items||[]).reduce((s,x)=>s+lineDiscount(x),0))),taxable=computed(()=>roundMoney(subtotal.value-discountTotal.value)),taxTotal=computed(()=>roundMoney((form.value.items||[]).reduce((s,x)=>s+lineTax(x),0))),grandTotal=computed(()=>roundMoney(taxable.value+taxTotal.value)),refundBalance=computed(()=>roundMoney(grandTotal.value-Number(form.value.refunded||0))),averageTax=computed(()=>taxable.value?money(taxTotal.value/taxable.value*100):'0.00')
const availableCredit=computed(()=>Math.max(0,Number(customer().credit_limit||0)-Number(customer().balance||0)+grandTotal.value)),creditUsage=computed(()=>{const limit=Number(customer().credit_limit||0);return limit?money(Math.max(0,Number(customer().balance||0)-grandTotal.value)/limit*100):'0.00'})
const canSubmit=computed(()=>form.value.id&&!editing.value&&['Draft','Rejected'].includes(form.value.status)),canDecide=computed(()=>form.value.id&&!editing.value&&['Draft','Pending'].includes(form.value.status)),canRefund=computed(()=>form.value.id&&!editing.value&&form.value.status==='Returned'&&refundBalance.value>0)
const totals=computed(()=>({amount:filtered.value.reduce((s,x)=>s+Number(x.total),0),refunded:filtered.value.reduce((s,x)=>s+Number(x.refunded),0)})),metrics=computed(()=>[{label:'Total Returns',count:filtered.value.length,icon:WalletCards,tone:'blue'},{label:'Total Return Amount',amount:totals.value.amount,currency:'USD',icon:CircleDollarSign,tone:'red'},{label:'Total Refunded',amount:totals.value.refunded,currency:'USD',icon:BadgeCheck,tone:'green'},{label:'Outstanding Refunds',amount:totals.value.amount-totals.value.refunded,currency:'USD',icon:Clock,tone:'amber'}])
const approvalSteps=['Draft','Pending','Returned'],apiError=e=>Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||e.message||'Unable to complete request.'
async function fetchAll(url){let p=1,last=1,out=[];do{const{data}=await client.get(url,{params:{per_page:100,page:p}}),body=data.data;out.push(...(body?.data||body||[]));last=body?.last_page||data.meta?.last_page||1;p++}while(p<=last);return out}
async function load(){[rows.value,invoices.value]=await Promise.all([fetchAll('/sales-returns'),fetchAll('/sales-invoices')])}
function normalize(x){return{...blank(),...x,items:(x.items||[]).map(y=>({...y})),refunds:x.refunds||[],attachments:x.attachments||[]}}
function startNew(){form.value=blank();editing.value=true;view.value='detail';error.value='';notice.value=''}
async function openReturn(row){busy.value=true;try{const{data}=await client.get('/sales-returns/'+row.id);form.value=normalize(data.data);editing.value=false;view.value='detail'}catch(e){error.value=apiError(e)}finally{busy.value=false}}
function back(){view.value='list';editing.value=false} async function cancelEdit(){form.value.id?await openReturn(form.value):back()}
function applyInvoice(){const x=invoices.value.find(i=>i.id===form.value.sales_invoice_id);if(!x)return;form.value.sales_invoice=x;form.value.shipping_method=x.shipping_method||'';restoreItems()}
function restoreItems(){form.value.items=(source.value.items||[]).map((x,index)=>({invoice_item_index:index,name:x.name,description:x.description||'',uom:x.uom||'PCS',quantity:Number(x.quantity),unit_price:Number(x.unit_price),discount:Number(x.discount||0),tax_rate:Number(x.tax_rate||0)}))}
async function saveReturn(){if(!form.value.sales_invoice_id||!form.value.reason||!form.value.items.length){error.value='Select an invoice, return reason, and at least one item.';return}busy.value=true;try{const{data}=form.value.id?await client.put('/sales-returns/'+form.value.id,form.value):await client.post('/sales-returns',form.value);form.value=normalize(data.data);editing.value=false;await load();notice.value='Sales return saved.'}catch(e){error.value=apiError(e)}finally{busy.value=false}}
async function workflow(action){busy.value=true;try{const{data}=await client.post('/sales-returns/'+form.value.id+'/workflow',{action});form.value=normalize(data.data);await load();notice.value='Sales return '+form.value.status.toLowerCase()+'.'}catch(e){error.value=apiError(e)}finally{busy.value=false}}
async function deleteReturn(){if(!confirm('Delete '+form.value.return_no+'?'))return;try{await client.delete('/sales-returns/'+form.value.id);await load();back();notice.value='Sales return deleted.'}catch(e){error.value=apiError(e)}}
function openRefund(){refundForm.value={refund_no:'CRF-'+String(Date.now()).slice(-6),refund_date:today(),amount:refundBalance.value,method:'',reference:'',notes:''};modal.value='refund'}
async function receiveRefund(){try{const{data}=await client.post('/sales-returns/'+form.value.id+'/refunds',refundForm.value);form.value=normalize(data.data);await load();modal.value='';notice.value='Customer refund recorded.'}catch(e){error.value=apiError(e)}}
async function uploadAttachment(e){const file=e.target.files[0];if(!file)return;const body=new FormData();body.append('file',file);try{const{data}=await client.post('/sales-returns/'+form.value.id+'/attachments',body,{headers:{'Content-Type':'multipart/form-data'}});form.value=normalize(data.data)}catch(x){error.value=apiError(x)}finally{e.target.value=''}}
async function downloadAttachment(file){const{data}=await client.get('/sales-returns/'+form.value.id+'/attachments/'+file.id,{responseType:'blob'});downloadBlob(data,file.name)} function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function printPage(){window.print()} function emailReturn(){const subject='Sales Return '+(form.value.return_no||''),body=subject+'\nInvoice: '+(source.value.invoice_no||'')+'\nCustomer: '+(customer().name||'')+'\nReturn total: '+negative(grandTotal.value);window.location.href='mailto:'+encodeURIComponent(customer().email||'')+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)}
async function savePdf(){const{default:jsPDF}=await import('jspdf'),pdf=new jsPDF();pdf.setFontSize(18);pdf.text('Sales Invoice Return '+(form.value.return_no||''),15,18);pdf.setFontSize(10);pdf.text('Customer: '+(customer().name||'-'),15,30);pdf.text('Invoice: '+(source.value.invoice_no||'-'),15,37);let y=50;form.value.items.forEach(x=>{pdf.text([x.name,x.quantity+' '+x.uom,negative(itemTotal(x))].join(' | '),15,y);y+=7});pdf.text('Grand Total: '+negative(grandTotal.value),15,y+7);pdf.save((form.value.return_no||'sales-return')+'.pdf')}
async function exportExcel(){const{default:ExcelJS}=await import('exceljs'),book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Sales Returns');sheet.addRow(['Customer','Invoice No.','Return No.','Return Date','Amount','Refunded','Status','Reason']);filtered.value.forEach(x=>sheet.addRow([customer(x).name,invoice(x).invoice_no,x.return_no,dateLabel(x.return_date),-Number(x.total),Number(x.refunded),x.status,x.reason]));sheet.getRow(1).font={bold:true};sheet.columns.forEach(x=>x.width=22);downloadBlob(new Blob([await book.xlsx.writeBuffer()]),'sales-returns.xlsx')}
function isStepDone(step){const current=approvalSteps.indexOf(form.value.status),target=approvalSteps.indexOf(step);return current>=target&&current>=0}
watch([filtered,perPage],()=>{page.value=Math.min(page.value,pageCount.value)});onMounted(load)
</script>

<style src="../assets/purchase-orders.css"></style>
<style>
.sr-page .sr-info-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}.sr-page .sr-info-grid>section,.sr-page .sr-bottom-grid>section{border:1px solid #dce3ef;padding:12px;min-width:0}.sr-page .sr-info-grid h3,.sr-page .sr-bottom-grid h3{color:#06278f;margin:0 0 12px}.sr-page .sr-bottom-grid{display:grid;grid-template-columns:1.3fr 1.1fr .95fr .9fr;gap:12px;margin-top:12px}.sr-page textarea{width:100%;border:1px solid #cfd8e8;padding:9px;resize:vertical}.sr-steps{display:flex;justify-content:space-between;margin:25px 0 32px}.sr-steps span{align-items:center;display:flex;flex-direction:column;gap:6px;position:relative;flex:1}.sr-steps i{width:24px;height:24px;border:2px solid #9ca8ba;border-radius:50%;background:#fff}.sr-steps svg{position:absolute;width:16px;top:4px;color:#fff;z-index:1}.sr-steps .done i{background:#f58220;border-color:#f58220}.sr-steps b{font-size:11px;text-align:center}.sr-signature{height:88px;display:grid;place-items:end center;border:1px solid #dce3ef;font-style:italic;color:#6d7890;margin-bottom:10px}.sr-grand{display:flex;justify-content:space-between;color:#061a88;font-weight:700;font-size:16px;padding-top:10px;border-top:1px solid #dce3ef}.sr-grand strong{color:#e00000}.sr-payment{display:block;width:110px;margin:8px auto 14px;text-align:center;color:#fff;background:#e00000;border-radius:14px;padding:4px 12px;font-weight:700}.sr-payment.paid{background:#07853b}.sr-payment.partial{background:#d17800}@media(max-width:1200px){.sr-page .sr-info-grid{grid-template-columns:1fr 1fr}.sr-page .sr-bottom-grid{grid-template-columns:1fr 1fr}}@media(max-width:760px){.sr-page .sr-info-grid,.sr-page .sr-bottom-grid{grid-template-columns:1fr}}
</style>
