<template>
  <AccountLayout bare><div class="container py-4">
    <section class="card border-0 shadow-sm mb-4"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><small class="text-uppercase text-muted fw-bold">Profiles Module</small><h2 class="mb-1">{{ heading }}</h2><span class="text-muted">Dashboard &gt; Profiles &gt; Account Holders &gt; Sellers</span></div><div><button v-if="mode !== 'list'" class="btn btn-outline-primary me-2" @click="showList">☷ List</button><button v-if="mode === 'view'" class="btn btn-primary" @click="startEdit">✎ Edit Seller</button><button v-if="mode === 'list'" class="btn btn-primary" @click="startNew">＋ New Seller</button></div></div></section>
    <div v-if="error" class="alert alert-danger">{{ error }}</div>
    <template v-if="mode === 'list'"><section class="card shadow-sm border-0 mb-4"><div class="card-body row g-3"><div class="col-md-5"><input v-model="search" class="form-control" placeholder="Search sellers..." /></div><div class="col-md-7 text-md-end"><strong>Total Sellers: {{ sellers.length }}</strong><span class="ms-4 text-success">Active: {{ active }}</span><span class="ms-4">Outstanding: {{ money(outstanding) }}</span></div></div></section><section class="card shadow-sm border-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Acc. No</th><th>Company</th><th>Primary Contact</th><th>Phone</th><th>Email</th><th class="text-end">Current Balance</th><th class="text-end">Outstanding</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="seller in filtered" :key="seller.id"><td>{{ seller.system_no }}</td><td><strong>{{ seller.company_name || seller.account_name }}</strong><div class="small text-muted">{{ seller.supplier_type || 'Seller' }}</div></td><td>{{ seller.primary_contact_name || seller.account_name }}</td><td>{{ seller.office_phone || seller.cell_phone }}</td><td>{{ seller.email }}</td><td class="text-end">{{ money(seller.current_balance) }}</td><td class="text-end">{{ money(seller.total_outstanding) }}</td><td><span class="badge" :class="seller.status_active ? 'text-bg-success' : 'text-bg-secondary'">{{ seller.status_active ? 'Active' : 'Inactive' }}</span></td><td><button class="btn btn-sm btn-outline-primary me-1" @click="view(seller)">View</button><button class="btn btn-sm btn-outline-secondary" @click="edit(seller)">Edit</button></td></tr></tbody></table></div></section></template>
    <section v-else-if="mode === 'view'" class="card shadow-sm border-0"><div class="card-body"><div class="row g-3"><Info title="Company Information" :rows="[['Company Name', selected.company_name], ['Legal Company Name', selected.legal_company_name], ['Seller No.', selected.system_no], ['Supplier Type', selected.supplier_type], ['Business Fields', selected.business_fields], ['Industry', selected.industry], ['Website', selected.website]]" /><Info title="Contact Information" :rows="[['Primary Contact', selected.primary_contact_name], ['Job Title', selected.job_title], ['Main Phone', selected.office_phone], ['Mobile', selected.mobile_phone || selected.cell_phone], ['Main Email', selected.email], ['Accounts Email', selected.accounts_email]]" /><Info title="Billing Address" :rows="[['Address', selected.address], ['City', selected.city], ['State / Province', selected.state], ['Zip / Postal Code', selected.zip_code]]" /><Info title="Payment Method & Invoice Terms" :rows="[['Payment Terms', selected.payment_terms], ['Invoice Terms', selected.invoice_terms], ['Credit Limit', money(selected.credit_limit)], ['Current Balance', money(selected.current_balance)], ['Total Outstanding', money(selected.total_outstanding)]]" /><Info title="Notes" :rows="[['Seller Notes', selected.seller_notes]]" /></div></div></section>
    <form v-else class="row g-3" @submit.prevent="save"><Section title="Company Information"><Field label="Company Name" required><input v-model.trim="form.company_name" required class="form-control" /></Field><Field label="Legal Company Name"><input v-model.trim="form.legal_company_name" class="form-control" /></Field><Field label="Supplier Type"><input v-model.trim="form.supplier_type" class="form-control" /></Field><Field label="Tax Number"><input v-model.trim="form.tax_number" class="form-control" /></Field><Field label="Website"><input v-model.trim="form.website" type="url" class="form-control" /></Field><Field label="Address"><textarea v-model.trim="form.address" class="form-control" rows="3" /></Field><Field label="Business Fields"><input v-model.trim="form.business_fields" class="form-control" /></Field></Section><Section title="Contact Information"><Field label="Primary Contact"><input v-model.trim="form.primary_contact_name" class="form-control" /></Field><Field label="Phone" required><input v-model.trim="form.cell_phone" required class="form-control" /></Field><Field label="Email" required><input v-model.trim="form.email" required type="email" class="form-control" /></Field><Field label="Accounts Email"><input v-model.trim="form.accounts_email" type="email" class="form-control" /></Field></Section><Section title="Payment & Terms"><Field label="Credit Limit"><input v-model.number="form.credit_limit" type="number" min="0" class="form-control" /></Field><Field label="Payment Terms"><input v-model.trim="form.payment_terms" class="form-control" /></Field><Field label="Invoice Terms"><input v-model.trim="form.invoice_terms" class="form-control" /></Field><Field label="Status"><select v-model="form.status_active" class="form-select"><option :value="true">Active</option><option :value="false">Inactive</option></select></Field></Section><div class="col-12"><label class="form-label fw-semibold">Seller Notes</label><textarea v-model="form.seller_notes" class="form-control" rows="3" /></div><div class="col-12"><button class="btn btn-primary me-2" :disabled="saving">{{ saving ? 'Saving...' : 'Save Seller' }}</button><button type="button" class="btn btn-outline-secondary" @click="showList">Cancel</button></div></form>
  </div></AccountLayout>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'; import client from '../api/client'; import AccountLayout from '../components/AccountLayout.vue';
const sellers=ref([]),search=ref(''),selected=ref(null),mode=ref('list'),form=ref({}),saving=ref(false),error=ref('');
const heading=computed(()=>mode.value==='list'?'Sellers':mode.value==='new'?'New Seller':'Seller Profile - '+(selected.value?.account_name||form.value.company_name||'')); const filtered=computed(()=>sellers.value.filter(s=>`${s.system_no} ${s.account_name} ${s.company_name||''} ${s.email}`.toLowerCase().includes(search.value.toLowerCase()))); const active=computed(()=>sellers.value.filter(s=>s.status_active).length); const outstanding=computed(()=>sellers.value.reduce((t,s)=>t+Number(s.total_outstanding||0),0)); const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
const blank=()=>({account_name:'',company_name:'',legal_company_name:'',supplier_type:'Seller',business_fields:'',primary_contact_name:'',cell_phone:'',email:'',accounts_email:'',credit_limit:0,payment_terms:'',invoice_terms:'',seller_notes:'',status_active:true,website:'',address:'',tax_number:''}); const showList=()=>{mode.value='list';selected.value=null;error.value=''}; const view=s=>{selected.value=s;mode.value='view'}; const edit=s=>{selected.value=s;form.value={...blank(),...s};mode.value='edit'}; const startEdit=()=>edit(selected.value); const startNew=()=>{form.value=blank();selected.value=null;mode.value='new'};
const presentSeller=(seller)=>({
  ...seller,
  system_no:`SLR-${String(seller.id).padStart(4,'0')}`,
  account_name:seller.seller_name,
  company_name:seller.seller_name,
  primary_contact_name:seller.contact_person || '',
  office_phone:seller.phone,
  cell_phone:seller.phone,
  status_active:!!seller.is_active,
  seller_notes:seller.notes||'',
  current_balance:0,
  total_outstanding:0,
  supplier_type:seller.vendor_category || 'Seller',
});
const load=async()=>{const {data}=await client.get('/sellers',{params:{per_page:100}});sellers.value=(Array.isArray(data?.data)?data.data:[]).map(presentSeller)}; const save=async()=>{saving.value=true;error.value='';try{const payload={seller_name:String(form.value.company_name||form.value.account_name||'').trim(),contact_person:String(form.value.primary_contact_name||'').trim()||null,address:String(form.value.address||'').trim()||null,tax_number:String(form.value.tax_number||'').trim()||null,vendor_category:String(form.value.supplier_type||'').trim()||null,email:String(form.value.email||'').trim()||null,phone:String(form.value.cell_phone||'').trim()||null,website:String(form.value.website||'').trim()||null,is_active:!!form.value.status_active,notes:String(form.value.seller_notes||'').trim()||null};const request=selected.value?client.put(`/sellers/${selected.value.id}`,payload):client.post('/sellers',payload);await request;await load();showList()}catch(e){error.value=e.response?.data?.message||Object.values(e.response?.data?.errors||{})[0]?.[0]||'Unable to save seller.'}finally{saving.value=false}};
const Info={props:['title','rows'],template:'<div class="col-lg-4"><div class="border rounded p-3 h-100"><h5 class="text-primary fw-bold mb-3">{{title}}</h5><div v-for="row in rows" :key="row[0]" class="row mb-2"><div class="col-5 text-muted small">{{row[0]}}</div><div class="col-7 fw-semibold small text-break">{{row[1]||"—"}}</div></div></div></div>'}; const Section={props:['title'],template:'<div class="col-lg-4"><section class="card border-0 shadow-sm h-100"><div class="card-body"><h5 class="text-primary fw-bold">{{title}}</h5><slot/></div></section></div>'}; const Field={props:['label','required'],template:'<div class="mb-3"><label class="form-label fw-semibold">{{label}}<span v-if="required" class="text-danger"> *</span></label><slot/></div>'}; onMounted(()=>load().catch(()=>error.value='Unable to load sellers.'));
</script>
