<template>
  <SuperAdminLayout>
    <section class="report-page">
      <header><div><h1>{{ config.title }}</h1><small>{{ config.description }}</small></div><div class="generated">Report date &amp; time<br><b>{{ generatedAt }}</b></div></header>
      <form class="filters" @submit.prevent="load"><label>Date from<input v-model="filters.from" type="date"></label><label>Date to<input v-model="filters.to" type="date"></label><label>Customer / user<input v-model="filters.search" placeholder="Search customer, invoice, user or IP"></label><label>Status<select v-model="filters.status"><option value="">All</option><option>Paid</option><option>Active</option><option>Failed</option><option>Blocked</option></select></label><button :disabled="loading">{{ loading ? 'Loading…' : 'Search' }}</button><button type="button" class="secondary" @click="reset">Reset</button></form>
      <div v-if="error" class="error">{{ error }}</div>
      <section class="summary"><article v-for="(value,label) in summary" :key="label"><span>{{ label }}</span><strong>{{ display(value, label) }}</strong></article></section>
      <section class="table-card"><div class="caption"><b>{{ config.title }}</b><span>{{ filteredRows.length }} records</span></div><div class="table-wrap"><table><thead><tr><th v-for="column in columns" :key="column">{{ label(column) }}</th></tr></thead><tbody><tr v-for="(row,index) in filteredRows" :key="index"><td v-for="column in columns" :key="column" :class="tone(column,row[column])">{{ display(row[column], column) }}</td></tr><tr v-if="!loading && !filteredRows.length"><td :colspan="columns.length" class="empty">No report records found for these filters.</td></tr></tbody></table></div></section>
      <footer><span>Total records: {{ filteredRows.length }}</span><div><button class="secondary" @click="exportCsv">Export CSV</button><button class="secondary" @click="print">Print</button><button @click="exportCsv">Save report</button></div></footer>
    </section>
  </SuperAdminLayout>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import client from '../api/client'
import SuperAdminLayout from '../components/SuperAdminLayout.vue'
const configs={
 'plan-history':{number:'12.11',title:'Service Plan History Report',description:'Customer service plan changes, upgrades, and plan updates.'},
 'audit-log':{number:'12.12',title:'Audit Log Report',description:'Platform administrator, customer, login, and security activity.'},
 'emergency-shutdown':{number:'12.13',title:'Emergency Shutdown Report',description:'Emergency shutdown incidents, restoration status, and approvals.'},
 'system-usage':{number:'12.14',title:'System Usage Report',description:'User login and platform usage statistics.'},
 'customer-master':{number:'12.15',title:'Customer Master Report',description:'Master customer account, plan, billing, and payment information.'},
 'sales-master':{number:'12.16',title:'Sales Master Report',description:'Sales invoices, tax, payments received, and outstanding balances.'},
 'sales-master-all':{number:'12.16.1',title:'Sales Master Report — All Customers / All Invoices',description:'All customer invoices in the selected reporting period.'},
 'sales-master-customer':{number:'12.16.1',title:'Sales Master Report — Each Customer Total Sales',description:'Total sales, tax, payments, and balances for each customer account.'},
 'sales-tax-master':{number:'12.17',title:'Sales Tax Master Report',description:'Taxable sales, sales tax, filing status, and outstanding tax balances.'},
 'sales-tax-all':{number:'12.17.1',title:'Sales Tax Master Report — All Customers / All Invoices',description:'Invoice-level sales tax details across the platform.'},
 'sales-tax-customer':{number:'12.17.2',title:'Sales Tax Master Report — Each Customer Total Sales',description:'Sales tax totals and filing position by customer.'},
 'suspected-license-sharing':{number:'12.18',title:'Suspected Users Licence Sharing',description:'Users flagged from multiple devices or IP locations.'},
 'sign-up-created-accounts':{number:'12.19',title:'Sign Up and Created Account Report',description:'Platform sign-ups, approved accounts, and review status.'},
 'failed-logins':{number:'12.7',title:'Failed Login Report',description:'Unsuccessful platform login attempts and related access details.'},
 'suspicious-devices':{number:'12.8',title:'Suspicious Device Access Report',description:'Flagged device and access attempts.'},
 'suspicious-activities':{number:'12.9',title:'Suspicious Activities Report',description:'High-risk platform access and security activity.'},
 'payment-failures':{number:'12.9',title:'Payment Failure & NSF Report',description:'Incomplete invoices, payment failures, and outstanding balances.'},
 'customer-revenue':{number:'12.10',title:'Customer Revenue Report',description:'Revenue, billing, payments, and outstanding balances by customer.'},
}
const route=useRoute(), key=computed(()=>route.meta.report), config=computed(()=>configs[key.value]||configs['sales-master']), rows=ref([]), summary=ref({}), loading=ref(false), error=ref(''), filters=reactive({from:'',to:'',search:'',status:''})
const generatedAt=new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date())
const columns=computed(()=>{const first=filteredRows.value[0]||rows.value[0];return first?Object.keys(first):[]})
const filteredRows=computed(()=>rows.value.filter(row=>{const hay=Object.values(row).join(' ').toLowerCase(), needle=filters.search.toLowerCase();if(needle&&!hay.includes(needle))return false;if(filters.status&&!Object.values(row).some(v=>String(v).toLowerCase()===filters.status.toLowerCase()))return false;if(filters.from&&String(row.date||'').slice(0,10)<filters.from)return false;if(filters.to&&String(row.date||'').slice(0,10)>filters.to)return false;return true}))
function label(key){return String(key).replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}function display(value,key=''){if(value===null||value===undefined||value==='')return '—';if(typeof value==='number'&&/(sales|payment|revenue|subtotal|tax|total|paid|outstanding|amount|billing)/i.test(key))return new Intl.NumberFormat(undefined,{style:'currency',currency:'CAD'}).format(value);return value}function tone(key,value){return /status|result|risk/i.test(key)?String(value).toLowerCase().replaceAll(' ','-'):''}
async function load(){loading.value=true;error.value='';try{const {data}=await client.get(`/super-admin/reports/data/${key.value}`);rows.value=data.data.rows||[];summary.value=data.data.summary||{}}catch(e){error.value=e.response?.data?.message||'Could not load this report.'}finally{loading.value=false}}
function reset(){Object.assign(filters,{from:'',to:'',search:'',status:''});load()}function exportCsv(){const header=columns.value;const csv=[header,...filteredRows.value.map(r=>header.map(k=>JSON.stringify(r[k]??'')))].map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${key.value}-report.csv`;a.click();URL.revokeObjectURL(a.href)}function print(){window.print()}onMounted(load)
</script>
<style scoped>
.report-page{color:#13254b}.report-page header{display:flex;justify-content:space-between;gap:20px;margin-bottom:18px}.report-page h1{margin:3px 0 5px;font-size:2rem}.report-page small{color:#63708a}.generated{text-align:right;font-size:.8rem;color:#65718b}.generated b{color:#113d91}.filters{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr)) auto auto;gap:12px;align-items:end;background:#fff;border:1px solid #dfe7f2;border-radius:8px;padding:16px}.filters label{font-size:.75rem;font-weight:700;display:grid;gap:5px}.filters input,.filters select{height:37px;border:1px solid #ccd8e8;border-radius:4px;padding:0 10px;color:#243553;background:#fff}.filters button,footer button{height:37px;border:0;border-radius:4px;background:#062e78;color:#fff;padding:0 18px;font-weight:700;white-space:nowrap}.filters .secondary,footer .secondary{background:#fff;color:#123d88;border:1px solid #9db5df}.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin:16px 0}.summary article{min-height:90px;background:#fff;border:1px solid #dfe7f2;border-radius:7px;padding:17px;display:grid;gap:7px}.summary span{font-size:.78rem}.summary strong{color:#0750bc;font-size:1.4rem}.table-card{background:#fff;border:1px solid #dfe7f2;border-radius:7px}.caption{padding:12px 15px;display:flex;justify-content:space-between;color:#123f92;font-size:.85rem}.table-wrap{overflow:auto;max-height:590px}table{width:100%;border-collapse:collapse;font-size:.76rem}th{position:sticky;top:0;background:linear-gradient(100deg,#03205f,#0751c7)!important;color:#fff!important;white-space:nowrap}th,td{padding:10px 12px;border:1px solid #e2e8f1;text-align:left;white-space:nowrap}td{color:#17233e}.paid,.active,.success,.allowed,.completed{color:#08772e;font-weight:700}.failed,.blocked,.critical,.high,.overdue,.void{color:#d12626;font-weight:700}.medium,.partial,.attention{color:#ed7100;font-weight:700}.empty{text-align:center;padding:35px}.error{margin-top:12px;color:#b42318}footer{display:flex;justify-content:space-between;align-items:center;padding:18px 4px;background:#fff!important;background-image:none!important;font-size:.82rem}footer div{display:flex;gap:10px}@media(max-width:1050px){.filters{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.report-page header,footer{display:block}.generated{text-align:left;margin-top:12px}.filters{grid-template-columns:1fr}.filters button{width:100%}footer div{margin-top:12px;flex-wrap:wrap}}@media print{.filters,footer,.sa-sidebar{display:none!important}.table-wrap{max-height:none}.report-page h1{font-size:1.5rem}}
</style>
